[package]
name = "dynamic-filter-tokio-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
tokio-postgres = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
test-context = { workspace = true }
test-utils = { workspace = true }
