//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.12

pub const LIST_AUTHORS_BY_I_DS: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsParams<'a> {
    pub ids: &'a [i64],
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByIDsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub async fn list_authors_by_i_ds<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    params: ListAuthorsByIDsParams<'_>,
) -> Result<Vec<ListAuthorsByIDsRow>, sqlx::Error> {
    let sql = LIST_AUTHORS_BY_I_DS;
    let sql = match params.ids.len() {
        0 => sql.replace("/*SLICE:ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:ids*/?", &to)
        }
    };
    let q = sqlx::query_as::<_, ListAuthorsByIDsRow>(&sql);
    let q = params.ids.iter().fold(q, |q, item| q.bind(item));
    let q = q.persistent(false);
    q.fetch_all(executor).await
}
pub const LIST_AUTHORS_BY_TWO_ID_LISTS: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
   OR id IN (/*SLICE:backup_ids*/?)
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByTwoIdListsParams<'a> {
    pub ids: &'a [i64],
    pub backup_ids: &'a [i64],
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByTwoIdListsRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub async fn list_authors_by_two_id_lists<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, sqlx::Error> {
    let sql = LIST_AUTHORS_BY_TWO_ID_LISTS;
    let sql = match params.ids.len() {
        0 => sql.replace("/*SLICE:ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:ids*/?", &to)
        }
    };
    let sql = match params.backup_ids.len() {
        0 => sql.replace("/*SLICE:backup_ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:backup_ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:backup_ids*/?", &to)
        }
    };
    let q = sqlx::query_as::<_, ListAuthorsByTwoIdListsRow>(&sql);
    let q = params.ids.iter().fold(q, |q, item| q.bind(item));
    let q = params.backup_ids.iter().fold(q, |q, item| q.bind(item));
    let q = q.persistent(false);
    q.fetch_all(executor).await
}
pub const LIST_AUTHORS_BY_I_DS_MIXED: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?)
  AND id >= ?
  AND id NOT IN (/*SLICE:skip_ids*/?)
  AND name <> ?
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsMixedParams<'a> {
    pub ids: &'a [i64],
    pub id: i64,
    pub skip_ids: &'a [i64],
    pub name: &'a str,
}
#[derive(sqlx::FromRow)]
pub struct ListAuthorsByIDsMixedRow {
    #[sqlx(rename = "id")]
    pub id: i64,
    #[sqlx(rename = "name")]
    pub name: String,
}
pub async fn list_authors_by_i_ds_mixed<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, sqlx::Error> {
    let sql = LIST_AUTHORS_BY_I_DS_MIXED;
    let sql = match params.ids.len() {
        0 => sql.replace("/*SLICE:ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:ids*/?", &to)
        }
    };
    let sql = match params.skip_ids.len() {
        0 => sql.replace("/*SLICE:skip_ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:skip_ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:skip_ids*/?", &to)
        }
    };
    let q = sqlx::query_as::<_, ListAuthorsByIDsMixedRow>(&sql);
    let q = params.ids.iter().fold(q, |q, item| q.bind(item));
    let q = q.bind(params.id);
    let q = params.skip_ids.iter().fold(q, |q, item| q.bind(item));
    let q = q.bind(params.name);
    let q = q.persistent(false);
    q.fetch_all(executor).await
}
pub const DELETE_AUTHORS_BY_I_DS: &str = r"DELETE FROM authors
WHERE id IN (/*SLICE:ids*/?)";
#[derive(Debug, Clone, Default)]
pub struct DeleteAuthorsByIDsParams<'a> {
    pub ids: &'a [i64],
}
pub async fn delete_authors_by_i_ds<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    params: DeleteAuthorsByIDsParams<'_>,
) -> Result<(), sqlx::Error> {
    let sql = DELETE_AUTHORS_BY_I_DS;
    let sql = match params.ids.len() {
        0 => sql.replace("/*SLICE:ids*/?", "NULL"),
        1 => sql.replace("/*SLICE:ids*/?", "?"),
        n => {
            let to = core::iter::once("?")
                .chain(core::iter::repeat(",?").take(n - 1))
                .collect::<String>();
            sql.replace("/*SLICE:ids*/?", &to)
        }
    };
    let q = sqlx::query(&sql);
    let q = params.ids.iter().fold(q, |q, item| q.bind(item));
    let q = q.persistent(false);
    q.execute(executor).await.map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("ListAuthorsByIDs", LIST_AUTHORS_BY_I_DS),
    ("ListAuthorsByTwoIDLists", LIST_AUTHORS_BY_TWO_ID_LISTS),
    ("ListAuthorsByIDsMixed", LIST_AUTHORS_BY_I_DS_MIXED),
    ("DeleteAuthorsByIDs", DELETE_AUTHORS_BY_I_DS),
];
