//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.2.0

pub const GET_AUTHOR: &str = r"SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1";
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl GetAuthorRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub async fn prepare_get_author(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_AUTHOR).await
}
pub async fn get_author(
    client: &impl deadpool_postgres::GenericClient,
    id: i64,
) -> Result<GetAuthorRow, deadpool_postgres::tokio_postgres::Error> {
    self::get_author_with(client, GET_AUTHOR, id).await
}
pub async fn get_author_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    id: i64,
) -> Result<GetAuthorRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&id];
    let row = client.query_one(statement, values).await?;
    GetAuthorRow::from_row(&row)
}
pub async fn get_author_opt(
    client: &impl deadpool_postgres::GenericClient,
    id: i64,
) -> Result<Option<GetAuthorRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_author_opt_with(client, GET_AUTHOR, id).await
}
pub async fn get_author_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    id: i64,
) -> Result<Option<GetAuthorRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&id];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| GetAuthorRow::from_row(&row))
        .transpose()
}
pub const LIST_AUTHORS: &str = r"SELECT id, name, bio FROM authors
ORDER BY name";
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl ListAuthorsRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub async fn prepare_list_authors(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(LIST_AUTHORS).await
}
pub async fn list_authors(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<Vec<ListAuthorsRow>, deadpool_postgres::tokio_postgres::Error> {
    self::list_authors_with(client, LIST_AUTHORS).await
}
pub async fn list_authors_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
) -> Result<Vec<ListAuthorsRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[];
    let rows = client.query(statement, values).await?;
    rows.iter().map(ListAuthorsRow::from_row).collect()
}
pub async fn list_authors_stream(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    self::list_authors_stream_with(client, LIST_AUTHORS).await
}
pub async fn list_authors_stream_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[];
    client.query_raw(statement, values.iter().copied()).await
}
pub const COUNT_AUTHORS: &str = r"SELECT COUNT(*) FROM authors";
pub struct CountAuthorsRow {
    pub count: i64,
}
impl CountAuthorsRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            count: row.try_get(0)?,
        })
    }
}
pub async fn prepare_count_authors(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(COUNT_AUTHORS).await
}
pub async fn count_authors(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<CountAuthorsRow, deadpool_postgres::tokio_postgres::Error> {
    self::count_authors_with(client, COUNT_AUTHORS).await
}
pub async fn count_authors_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
) -> Result<CountAuthorsRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[];
    let row = client.query_one(statement, values).await?;
    CountAuthorsRow::from_row(&row)
}
pub async fn count_authors_opt(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<Option<CountAuthorsRow>, deadpool_postgres::tokio_postgres::Error> {
    self::count_authors_opt_with(client, COUNT_AUTHORS).await
}
pub async fn count_authors_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
) -> Result<Option<CountAuthorsRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| CountAuthorsRow::from_row(&row))
        .transpose()
}
pub const CREATE_AUTHOR: &str = r"INSERT INTO authors (
          name, bio
) VALUES (
  $1, $2
)
RETURNING id, name, bio";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub struct CreateAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl CreateAuthorRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub async fn prepare_create_author(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(CREATE_AUTHOR).await
}
pub async fn create_author(
    client: &impl deadpool_postgres::GenericClient,
    params: CreateAuthorParams<'_>,
) -> Result<CreateAuthorRow, deadpool_postgres::tokio_postgres::Error> {
    self::create_author_with(client, CREATE_AUTHOR, params).await
}
pub async fn create_author_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: CreateAuthorParams<'_>,
) -> Result<CreateAuthorRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.name, &params.bio];
    let row = client.query_one(statement, values).await?;
    CreateAuthorRow::from_row(&row)
}
pub async fn create_author_opt(
    client: &impl deadpool_postgres::GenericClient,
    params: CreateAuthorParams<'_>,
) -> Result<Option<CreateAuthorRow>, deadpool_postgres::tokio_postgres::Error> {
    self::create_author_opt_with(client, CREATE_AUTHOR, params).await
}
pub async fn create_author_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: CreateAuthorParams<'_>,
) -> Result<Option<CreateAuthorRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.name, &params.bio];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| CreateAuthorRow::from_row(&row))
        .transpose()
}
pub const DELETE_AUTHOR: &str = r"DELETE FROM authors
WHERE id = $1";
pub async fn prepare_delete_author(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(DELETE_AUTHOR).await
}
pub async fn delete_author(
    client: &impl deadpool_postgres::GenericClient,
    id: i64,
) -> Result<(), deadpool_postgres::tokio_postgres::Error> {
    self::delete_author_with(client, DELETE_AUTHOR, id).await
}
pub async fn delete_author_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    id: i64,
) -> Result<(), deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&id];
    client.execute(statement, values).await.map(|_| ())
}
pub const GET_KEYWORD_IDENT: &str = r"SELECT id, type FROM keyword_idents
WHERE type = $1 LIMIT 1";
pub struct GetKeywordIdentRow {
    pub id: i64,
    pub r#type: String,
}
impl GetKeywordIdentRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            r#type: row.try_get(1)?,
        })
    }
}
pub async fn prepare_get_keyword_ident(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_KEYWORD_IDENT).await
}
pub async fn get_keyword_ident(
    client: &impl deadpool_postgres::GenericClient,
    r#type: &str,
) -> Result<GetKeywordIdentRow, deadpool_postgres::tokio_postgres::Error> {
    self::get_keyword_ident_with(client, GET_KEYWORD_IDENT, r#type).await
}
pub async fn get_keyword_ident_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    r#type: &str,
) -> Result<GetKeywordIdentRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&r#type];
    let row = client.query_one(statement, values).await?;
    GetKeywordIdentRow::from_row(&row)
}
pub async fn get_keyword_ident_opt(
    client: &impl deadpool_postgres::GenericClient,
    r#type: &str,
) -> Result<Option<GetKeywordIdentRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_keyword_ident_opt_with(client, GET_KEYWORD_IDENT, r#type).await
}
pub async fn get_keyword_ident_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(
         impl deadpool_postgres::tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    r#type: &str,
) -> Result<Option<GetKeywordIdentRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&r#type];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| GetKeywordIdentRow::from_row(&row))
        .transpose()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetAuthor", GET_AUTHOR),
    ("ListAuthors", LIST_AUTHORS),
    ("CountAuthors", COUNT_AUTHORS),
    ("CreateAuthor", CREATE_AUTHOR),
    ("DeleteAuthor", DELETE_AUTHOR),
    ("GetKeywordIdent", GET_KEYWORD_IDENT),
];
pub async fn prepare_dynfilter_variants(
    _client: &deadpool_postgres::ClientWrapper,
) -> Result<(), deadpool_postgres::tokio_postgres::Error> {
    Ok(())
}
pub const DYNFILTER_VARIANT_COUNT: usize = 0;
