//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.2.0

pub mod dynfilter {
    use std::collections::{HashMap, HashSet};
    use std::fmt::Write as _;
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Arg {
        Active,
        Inactive,
        Slice(Option<usize>),
        Flag(bool),
    }
    impl Arg {
        pub fn from_option<T>(value: &Option<T>) -> Self {
            value.as_ref().map_or(Self::Inactive, |_| Self::Active)
        }
        fn active(self) -> bool {
            match self {
                Self::Active => true,
                Self::Inactive => false,
                Self::Slice(length) => length.is_some(),
                Self::Flag(value) => value,
            }
        }
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Bind {
        Arg(usize),
        Elem(usize, usize),
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Placeholders {
        Numbered,
        NumberedSqlite,
        Question,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Connector {
        And,
        Or,
        Comma,
    }
    impl Connector {
        /// The text that leads every item but the first; a comma trails items instead.
        fn line_prefix(self) -> Option<&'static str> {
            match self {
                Self::And => Some("AND "),
                Self::Or => Some("OR "),
                Self::Comma => None,
            }
        }
    }
    /// Line indices into the annotated SQL: the clause header and the first line of each item.
    pub struct Clause<'a> {
        pub header: usize,
        pub connector: Connector,
        pub items: &'a [usize],
    }
    pub struct Compiled {
        segments: Vec<Segment>,
        connectors: Vec<Connector>,
        placeholders: Placeholders,
    }
    /// Bare `?` placeholders take the next argument number not yet claimed, in field order.
    struct PlaceholderState<'a> {
        arg_order: &'a [usize],
        seen_arg_nums: HashSet<usize>,
    }
    impl PlaceholderState<'_> {
        /// A bare `?` is a bind only where the engine uses it; PostgreSQL's `?` is a JSON
        /// operator, so the argument order is never consulted for it.
        fn unnumbered(&self, placeholders: Placeholders) -> Option<usize> {
            match placeholders {
                Placeholders::Numbered => None,
                Placeholders::NumberedSqlite | Placeholders::Question => self
                    .arg_order
                    .iter()
                    .copied()
                    .find(|number| !self.seen_arg_nums.contains(number)),
            }
        }
    }
    #[derive(Clone, Copy)]
    enum Role {
        Plain,
        Header(usize),
        Item(usize),
    }
    struct Segment {
        parts: Vec<String>,
        arg_nums: Vec<usize>,
        cond_idxs: Vec<usize>,
        role: Role,
    }
    impl Segment {
        fn active(&self, args: &[Arg]) -> bool {
            self.cond_idxs
                .iter()
                .all(|index| args.get(*index).is_some_and(|arg| arg.active()))
        }
    }
    impl Compiled {
        pub fn build(&self, args: &[Arg]) -> (String, Vec<Bind>) {
            let mut query = String::new();
            let mut writer = Writer {
                placeholders: self.placeholders,
                binds: Vec::new(),
                next_placeholder: 1,
                scalar_placeholders: HashMap::new(),
                slice_placeholders: HashMap::new(),
            };
            let mut pending_headers = vec![None; self.connectors.len()];
            for segment in self.segments.iter().filter(|segment| segment.active(args)) {
                match segment.role {
                    Role::Plain => writer.write(&mut query, segment, args, None),
                    Role::Header(clause) => {
                        let mut header = String::new();
                        writer.write(&mut header, segment, args, None);
                        pending_headers[clause] = Some(header);
                    }
                    Role::Item(clause) => match pending_headers[clause].take() {
                        Some(header) => {
                            query.push_str(&header);
                            writer.write(&mut query, segment, args, None);
                        }
                        None => {
                            writer.write(&mut query, segment, args, Some(self.connectors[clause]))
                        }
                    },
                }
            }
            (query, writer.binds)
        }
    }
    struct Writer {
        placeholders: Placeholders,
        binds: Vec<Bind>,
        next_placeholder: usize,
        scalar_placeholders: HashMap<usize, usize>,
        slice_placeholders: HashMap<usize, Vec<usize>>,
    }
    impl Writer {
        fn write(
            &mut self,
            query: &mut String,
            segment: &Segment,
            args: &[Arg],
            connector: Option<Connector>,
        ) {
            let mut skip = 0;
            match connector.map(Connector::line_prefix) {
                Some(Some(prefix)) => {
                    let part = &segment.parts[0];
                    skip = part.len() - part.trim_start().len();
                    query.push_str(&part[..skip]);
                    query.push_str(prefix);
                }
                Some(None) => query.push(','),
                None => {}
            }
            for (index, part) in segment.parts.iter().enumerate() {
                let part = if index == 0 {
                    &part[skip..]
                } else {
                    part.as_str()
                };
                if let Some(before) = slice_prefix(part).filter(|_| index < segment.arg_nums.len())
                {
                    let arg_index = segment.arg_nums[index] - 1;
                    if let Some(Arg::Slice(Some(length))) = args.get(arg_index) {
                        query.push_str(before);
                        if self.placeholders == Placeholders::Question {
                            self.write_slice(query, arg_index, *length);
                        } else if let Some(numbers) = self.slice_placeholders.get(&arg_index) {
                            write_placeholders(query, self.placeholders, numbers);
                        } else {
                            let numbers = self.write_slice(query, arg_index, *length);
                            self.slice_placeholders.insert(arg_index, numbers);
                        }
                        continue;
                    }
                    if args.get(arg_index).is_none() {
                        query.push_str(before);
                        query.push_str("NULL");
                        continue;
                    }
                }
                query.push_str(part);
                let Some(arg_number) = segment.arg_nums.get(index) else {
                    continue;
                };
                let arg_index = arg_number - 1;
                if self.placeholders != Placeholders::Question {
                    if let Some(number) = self.scalar_placeholders.get(&arg_index) {
                        write_placeholder(query, self.placeholders, *number);
                    } else {
                        write_placeholder(query, self.placeholders, self.next_placeholder);
                        self.scalar_placeholders
                            .insert(arg_index, self.next_placeholder);
                        self.next_placeholder += 1;
                        self.binds.push(Bind::Arg(arg_index));
                    }
                } else {
                    write_placeholder(query, self.placeholders, self.next_placeholder);
                    self.next_placeholder += 1;
                    self.binds.push(Bind::Arg(arg_index));
                }
            }
        }
        fn write_slice(
            &mut self,
            query: &mut String,
            arg_index: usize,
            length: usize,
        ) -> Vec<usize> {
            if length == 0 {
                query.push_str("NULL");
                return Vec::new();
            }
            let mut numbers = Vec::new();
            for element_index in 0..length {
                if element_index > 0 {
                    query.push(',');
                }
                let number = self.next_placeholder;
                write_placeholder(query, self.placeholders, number);
                self.next_placeholder += 1;
                if self.placeholders != Placeholders::Question {
                    numbers.push(number);
                }
                self.binds.push(Bind::Elem(arg_index, element_index));
            }
            numbers
        }
    }
    pub fn compile_with_arg_order(
        annotated_sql: &str,
        placeholders: Placeholders,
        arg_order: &[usize],
        plan: &[Clause<'_>],
    ) -> Compiled {
        let config = LexerConfig::new(placeholders);
        let roles = line_roles(plan);
        let strips = connector_lines(plan);
        let mut segments = Vec::new();
        let mut static_sql = String::new();
        let mut placeholder_state = PlaceholderState {
            arg_order,
            seen_arg_nums: HashSet::new(),
        };
        let mut state = LexState::default();
        for (index, line) in annotated_sql.split('\n').enumerate() {
            let separator = if index == 0 { "" } else { "\n" };
            if state.open() {
                state = line_end_state(line, state, config);
                static_sql.push_str(separator);
                static_sql.push_str(line);
                continue;
            }
            let (conditions, cleaned) = extract_conditions(line, config);
            let role = roles.get(&index).copied();
            let strip = strips.get(&index).copied();
            if conditions.is_empty() && role.is_none() && strip.is_none() {
                state = line_end_state(line, state, config);
                static_sql.push_str(separator);
                static_sql.push_str(line);
                continue;
            }
            flush_static(
                &mut segments,
                &mut static_sql,
                &mut placeholder_state,
                config,
            );
            state = line_end_state(&cleaned, state, config);
            let cleaned = match strip {
                Some(connector) => strip_connector(&cleaned, connector),
                None => cleaned,
            };
            let (parts, arg_nums) = split_placeholders(
                &format!("{separator}{cleaned}"),
                &mut placeholder_state,
                config,
            );
            segments.push(Segment {
                parts,
                arg_nums,
                cond_idxs: conditions,
                role: role.unwrap_or(Role::Plain),
            });
        }
        flush_static(
            &mut segments,
            &mut static_sql,
            &mut placeholder_state,
            config,
        );
        Compiled {
            segments,
            connectors: plan.iter().map(|clause| clause.connector).collect(),
            placeholders,
        }
    }
    fn line_roles(plan: &[Clause<'_>]) -> HashMap<usize, Role> {
        plan.iter()
            .enumerate()
            .flat_map(|(index, clause)| {
                std::iter::once((clause.header, Role::Header(index))).chain(
                    clause
                        .items
                        .iter()
                        .map(move |line| (*line, Role::Item(index))),
                )
            })
            .collect()
    }
    /// Lines whose connector text is removed at compile time and re-added by `build` only when an
    /// earlier item of the clause survives: `AND` leads every item but the first, and `,` trails
    /// every item but the last.
    fn connector_lines(plan: &[Clause<'_>]) -> HashMap<usize, Connector> {
        plan.iter()
            .flat_map(|clause| {
                let lines = match clause.connector {
                    Connector::And | Connector::Or => {
                        clause.items.iter().skip(1).copied().collect::<Vec<_>>()
                    }
                    Connector::Comma => clause.items.windows(2).map(|pair| pair[1] - 1).collect(),
                };
                lines.into_iter().map(move |line| (line, clause.connector))
            })
            .collect()
    }
    fn strip_connector(text: &str, connector: Connector) -> String {
        match connector.line_prefix() {
            Some(prefix) => {
                let indentation = text.len() - text.trim_start().len();
                let rest = &text[indentation..];
                format!(
                    "{}{}",
                    &text[..indentation],
                    rest.strip_prefix(prefix).unwrap_or(rest)
                )
            }
            None => {
                let trimmed = text.trim_end();
                trimmed.strip_suffix(',').unwrap_or(trimmed).to_string()
            }
        }
    }
    pub fn nilable<T>(slice: &[T]) -> Option<&[T]> {
        (!slice.is_empty()).then_some(slice)
    }
    fn flush_static(
        segments: &mut Vec<Segment>,
        static_sql: &mut String,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) {
        if static_sql.is_empty() {
            return;
        }
        let (parts, arg_nums) = split_placeholders(static_sql, placeholder_state, config);
        segments.push(Segment {
            parts,
            arg_nums,
            cond_idxs: Vec::new(),
            role: Role::Plain,
        });
        static_sql.clear();
    }
    fn write_placeholders(query: &mut String, placeholders: Placeholders, numbers: &[usize]) {
        if numbers.is_empty() {
            query.push_str("NULL");
            return;
        }
        for (index, number) in numbers.iter().enumerate() {
            if index > 0 {
                query.push(',');
            }
            write_placeholder(query, placeholders, *number);
        }
    }
    fn write_placeholder(query: &mut String, placeholders: Placeholders, number: usize) {
        match placeholders {
            Placeholders::Numbered | Placeholders::NumberedSqlite => {
                let _ = write!(query, "${number}");
            }
            Placeholders::Question => query.push('?'),
        }
    }
    fn slice_prefix(part: &str) -> Option<&str> {
        let start = part.rfind("/*SLICE:")?;
        part.ends_with("*/").then_some(&part[..start])
    }
    fn extract_conditions(line: &str, config: LexerConfig) -> (Vec<usize>, String) {
        let Some(start) = annotation_start(line, config) else {
            return (Vec::new(), line.to_string());
        };
        let mut conditions = Vec::new();
        let mut rest = &line[start..];
        while let Some(position) = rest.find(" -- :if $") {
            let after_marker = &rest[position + 9..];
            let digits = after_marker.bytes().take_while(u8::is_ascii_digit).count();
            if let Ok(number) = after_marker[..digits].parse::<usize>()
                && number > 0
            {
                conditions.push(number - 1);
            }
            rest = &rest[position + 1..];
        }
        (conditions, line[..start].trim_end().to_string())
    }
    /// The plugin strips ordinary line comments before appending gate markers, so the first line
    /// comment that is not a marker ends the search: prose mentioning a marker never gates a line.
    fn annotation_start(line: &str, config: LexerConfig) -> Option<usize> {
        let bytes = line.as_bytes();
        let mut index = 0;
        while index < bytes.len() {
            if bytes[index..].starts_with(b" -- :if $") {
                return Some(index);
            }
            if starts_line_comment(line, index, config) {
                return None;
            }
            let next = skip_quoted_or_block(line, index, config);
            index = if next > index { next } else { index + 1 };
        }
        None
    }
    fn split_placeholders(
        text: &str,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) -> (Vec<String>, Vec<usize>) {
        let bytes = text.as_bytes();
        let mut parts = Vec::new();
        let mut arg_nums = Vec::new();
        let mut part_start = 0;
        let mut index = 0;
        while index < bytes.len() {
            let next = skip_token(text, index, config);
            if next > index {
                index = next;
                continue;
            }
            if bytes[index] != b'$' && bytes[index] != b'?' {
                index += 1;
                continue;
            }
            let mut end = index + 1;
            while bytes.get(end).is_some_and(u8::is_ascii_digit) {
                end += 1;
            }
            let number = match (bytes[index], end > index + 1, config.placeholders) {
                (b'$', true, _) => parse_number(&text[index + 1..end]),
                (b'?', true, Placeholders::NumberedSqlite | Placeholders::Question) => {
                    parse_number(&text[index + 1..end])
                }
                (b'?', false, _) => placeholder_state.unnumbered(config.placeholders),
                _ => None,
            };
            let Some(number) = number.filter(|number| *number > 0) else {
                index = end;
                continue;
            };
            placeholder_state.seen_arg_nums.insert(number);
            parts.push(text[part_start..index].to_string());
            arg_nums.push(number);
            part_start = end;
            index = end;
        }
        parts.push(text[part_start..].to_string());
        (parts, arg_nums)
    }
    fn parse_number(text: &str) -> Option<usize> {
        text.parse().ok()
    }
    fn skip_token(text: &str, index: usize, config: LexerConfig) -> usize {
        if starts_line_comment(text, index, config) {
            return text[index..]
                .find('\n')
                .map_or(text.len(), |end| index + end);
        }
        skip_quoted_or_block(text, index, config)
    }
    /// MySQL also comments with `#`, and its `--` needs a following whitespace or control byte.
    fn starts_line_comment(text: &str, index: usize, config: LexerConfig) -> bool {
        let bytes = &text.as_bytes()[index..];
        if config.mysql && bytes.first() == Some(&b'#') {
            return true;
        }
        bytes.starts_with(b"--")
            && (!config.mysql
                || bytes
                    .get(2)
                    .is_none_or(|byte| byte.is_ascii_whitespace() || byte.is_ascii_control()))
    }
    /// Unquoted identifiers are consumed whole: PostgreSQL and MySQL allow `$` inside them, so
    /// `price$9` names a column rather than referencing a parameter.
    fn skip_identifier(text: &str, index: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        if !is_identifier_start(bytes[index]) {
            return index;
        }
        let mut end = index + 1;
        while bytes.get(end).is_some_and(|byte| {
            is_identifier_start(*byte) || byte.is_ascii_digit() || (*byte == b'$' && !config.sqlite)
        }) {
            end += 1;
        }
        end
    }
    fn is_identifier_start(byte: u8) -> bool {
        byte == b'_' || byte.is_ascii_alphabetic() || !byte.is_ascii()
    }
    fn skip_quoted_or_block(text: &str, index: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        match bytes[index] {
            b'\'' | b'"' | b'`' => {
                let quote = bytes[index];
                let backslash = quote != b'`'
                    && (config.mysql
                        || (config.postgres
                            && quote == b'\''
                            && escape_string_prefix(text, index)));
                quote_end(bytes, index + 1, quote, backslash).0
            }
            b'[' if config.sqlite => text[index + 1..]
                .find(']')
                .map_or(text.len(), |end| index + end + 2),
            b'$' if config.postgres => dollar_delimiter(text, index).map_or(index, |delimiter| {
                text[index + delimiter.len()..]
                    .find(&delimiter)
                    .map_or(text.len(), |end| {
                        index + delimiter.len() + end + delimiter.len()
                    })
            }),
            b'/' if bytes[index..].starts_with(b"/*") => skip_block_comment(text, index, config),
            _ => skip_identifier(text, index, config),
        }
    }
    fn skip_block_comment(text: &str, start: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        let mut depth = 0;
        let mut index = start;
        while index + 1 < bytes.len() {
            if bytes[index..].starts_with(b"/*") && (config.postgres || depth == 0) {
                depth += 1;
                index += 2;
            } else if bytes[index..].starts_with(b"*/") {
                depth -= 1;
                index += 2;
                if depth == 0 {
                    return index;
                }
            } else {
                index += 1;
            }
        }
        text.len()
    }
    #[derive(Clone, Copy)]
    struct LexerConfig {
        placeholders: Placeholders,
        postgres: bool,
        mysql: bool,
        sqlite: bool,
    }
    impl LexerConfig {
        fn new(placeholders: Placeholders) -> Self {
            Self {
                placeholders,
                postgres: placeholders == Placeholders::Numbered,
                mysql: placeholders == Placeholders::Question,
                sqlite: placeholders == Placeholders::NumberedSqlite,
            }
        }
    }
    #[derive(Default)]
    struct LexState {
        quote: Option<u8>,
        backslash: bool,
        comment_depth: usize,
        dollar: Option<String>,
    }
    impl LexState {
        fn open(&self) -> bool {
            self.quote.is_some() || self.comment_depth > 0 || self.dollar.is_some()
        }
    }
    fn line_end_state(line: &str, mut state: LexState, config: LexerConfig) -> LexState {
        let bytes = line.as_bytes();
        let mut index = 0;
        while index < bytes.len() {
            if let Some(delimiter) = &state.dollar {
                let Some(end) = line[index..].find(delimiter) else {
                    return state;
                };
                index += end + delimiter.len();
                state.dollar = None;
                continue;
            }
            if state.comment_depth > 0 {
                while index < bytes.len() && state.comment_depth > 0 {
                    if config.postgres && bytes[index..].starts_with(b"/*") {
                        state.comment_depth += 1;
                        index += 2;
                    } else if bytes[index..].starts_with(b"*/") {
                        state.comment_depth -= 1;
                        index += 2;
                    } else {
                        index += 1;
                    }
                }
                continue;
            }
            if let Some(quote) = state.quote {
                if quote == b'[' {
                    let Some(end) = line[index..].find(']') else {
                        return state;
                    };
                    index += end + 1;
                    state.quote = None;
                    continue;
                }
                let (end, closed) = quote_end(bytes, index, quote, state.backslash);
                if !closed {
                    return state;
                }
                index = end;
                state.quote = None;
                continue;
            }
            if starts_line_comment(line, index, config) {
                return state;
            }
            if bytes[index..].starts_with(b"/*") {
                state.comment_depth = 1;
                index += 2;
                continue;
            }
            match bytes[index] {
                b'\'' | b'"' | b'`' => {
                    let quote = bytes[index];
                    state.quote = Some(quote);
                    state.backslash = quote != b'`'
                        && (config.mysql
                            || (config.postgres
                                && quote == b'\''
                                && escape_string_prefix(line, index)));
                    index += 1;
                }
                b'[' if config.sqlite => {
                    state.quote = Some(b'[');
                    index += 1;
                }
                b'$' if config.postgres => {
                    if let Some(delimiter) = dollar_delimiter(line, index) {
                        index += delimiter.len();
                        state.dollar = Some(delimiter);
                    } else {
                        index += 1;
                    }
                }
                _ => index = skip_identifier(line, index, config).max(index + 1),
            }
        }
        state
    }
    fn quote_end(bytes: &[u8], mut index: usize, quote: u8, backslash: bool) -> (usize, bool) {
        while index < bytes.len() {
            if backslash && bytes[index] == b'\\' {
                index += 2;
                continue;
            }
            if bytes[index] != quote {
                index += 1;
                continue;
            }
            if bytes.get(index + 1) == Some(&quote) {
                index += 2;
                continue;
            }
            return (index + 1, true);
        }
        (bytes.len(), false)
    }
    fn escape_string_prefix(text: &str, quote_index: usize) -> bool {
        if quote_index == 0 || !matches!(text.as_bytes()[quote_index - 1], b'e' | b'E') {
            return false;
        }
        if quote_index == 1 {
            return true;
        }
        let previous = text.as_bytes()[quote_index - 2];
        !(previous == b'_' || previous == b'$' || previous.is_ascii_alphanumeric())
    }
    fn dollar_delimiter(text: &str, start: usize) -> Option<String> {
        let bytes = text.as_bytes();
        let mut index = start + 1;
        while let Some(byte) = bytes.get(index) {
            if *byte == b'$' {
                return Some(text[start..=index].to_string());
            }
            let is_identifier = *byte == b'_'
                || byte.is_ascii_alphabetic()
                || (index > start + 1 && byte.is_ascii_digit());
            if !is_identifier {
                return None;
            }
            index += 1;
        }
        None
    }
}
pub const SEARCH_USERS: &str = r"SELECT id, email, phone
FROM users
WHERE
  email = $1 -- :if $1
  AND phone = $2 -- :if $2
  AND EXISTS ( -- :if $6
    SELECT 1 FROM orders -- :if $6
    WHERE -- :if $6
      orders.user_id = users.id -- :if $6
      AND orders.created_at >= $3 -- :if $6 -- :if $3
  ) -- :if $6
  AND id = ANY($4::bigint[]) -- :if $4
ORDER BY
  id ASC, -- :if $7
  id DESC, -- :if $8
  LENGTH(email) ASC, -- :if $9
  id DESC -- :if $9
LIMIT $5::int";
pub const SEARCH_USERS_VARIANTS: &[&str] = &[
    r"SELECT id, email, phone
FROM users
ORDER BY
  id ASC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
ORDER BY
  id DESC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id ASC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id DESC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $1::int",
    r"SELECT id, email, phone
FROM users
WHERE
  id = ANY($1::bigint[])
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  id = ANY($1::bigint[])
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  id = ANY($1::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($1::bigint[])
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($1::bigint[])
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($1::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $1
  )
  AND id = ANY($2::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND id = ANY($2::bigint[])
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND id = ANY($2::bigint[])
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND id = ANY($2::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id ASC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  phone = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id ASC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $2::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND id = ANY($2::bigint[])
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND id = ANY($2::bigint[])
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND id = ANY($2::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($2::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id ASC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $2
  )
  AND id = ANY($3::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id ASC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $3::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND id = ANY($3::bigint[])
ORDER BY
  id ASC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND id = ANY($3::bigint[])
ORDER BY
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND id = ANY($3::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id ASC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($3::bigint[])
ORDER BY
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
  )
  AND id = ANY($3::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
ORDER BY
  id ASC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
ORDER BY
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $4::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
  AND id = ANY($4::bigint[])
ORDER BY
  id ASC
LIMIT $5::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
  AND id = ANY($4::bigint[])
ORDER BY
  id DESC
LIMIT $5::int",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND phone = $2
  AND EXISTS (
    SELECT 1 FROM orders
    WHERE
      orders.user_id = users.id
      AND orders.created_at >= $3
  )
  AND id = ANY($4::bigint[])
ORDER BY
  LENGTH(email) ASC,
  id DESC
LIMIT $5::int",
];
static SEARCH_USERS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_USERS,
            dynfilter::Placeholders::Numbered,
            &[1usize, 2usize, 3usize, 4usize, 5usize],
            &[
                dynfilter::Clause {
                    header: 2usize,
                    connector: dynfilter::Connector::And,
                    items: &[3usize, 4usize, 5usize, 11usize],
                },
                dynfilter::Clause {
                    header: 7usize,
                    connector: dynfilter::Connector::And,
                    items: &[8usize, 9usize],
                },
                dynfilter::Clause {
                    header: 12usize,
                    connector: dynfilter::Connector::Comma,
                    items: &[13usize, 14usize, 15usize, 16usize],
                },
            ],
        )
    });
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SearchUsersSort {
    #[default]
    IdAsc,
    IdDesc,
    ShortestEmail,
}
#[derive(Debug, Clone, Default)]
pub struct SearchUsersParams<'a> {
    pub email: Option<&'a str>,
    pub phone: Option<&'a str>,
    pub orders_since: Option<&'a str>,
    pub ids: Option<&'a [i64]>,
    pub row_limit: i32,
    pub has_orders: bool,
    pub sort: SearchUsersSort,
}
pub struct SearchUsersRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl SearchUsersRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn search_users_query<'p>(
    params: &'p SearchUsersParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.email),
        dynfilter::Arg::from_option(&params.phone),
        dynfilter::Arg::from_option(&params.orders_since),
        dynfilter::Arg::from_option(&params.ids),
        dynfilter::Arg::Active,
        dynfilter::Arg::Flag(params.has_orders),
        dynfilter::Arg::Flag(matches!(params.sort, SearchUsersSort::IdAsc)),
        dynfilter::Arg::Flag(matches!(params.sort, SearchUsersSort::IdDesc)),
        dynfilter::Arg::Flag(matches!(params.sort, SearchUsersSort::ShortestEmail)),
    ];
    let (sql, binds) = SEARCH_USERS_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email as _,
            dynfilter::Bind::Arg(1usize) => &params.phone as _,
            dynfilter::Bind::Arg(2usize) => &params.orders_since as _,
            dynfilter::Bind::Arg(3usize) => &params.ids as _,
            dynfilter::Bind::Arg(4usize) => &params.row_limit as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn search_users(
    client: &mut impl postgres::GenericClient,
    params: SearchUsersParams<'_>,
) -> Result<Vec<SearchUsersRow>, postgres::Error> {
    let (sql, values) = search_users_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter().map(SearchUsersRow::from_row).collect()
}
pub fn search_users_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchUsersParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_users_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const COUNT_USERS: &str = r"SELECT COUNT(*) AS total
FROM users
WHERE
  email = $1 -- :if $1
  AND users.id = ANY($2::bigint[]) -- :if $2";
pub const COUNT_USERS_VARIANTS: &[&str] = &[
    r"SELECT COUNT(*) AS total
FROM users",
    r"SELECT COUNT(*) AS total
FROM users
WHERE
  users.id = ANY($1::bigint[])",
    r"SELECT COUNT(*) AS total
FROM users
WHERE
  email = $1",
    r"SELECT COUNT(*) AS total
FROM users
WHERE
  email = $1
  AND users.id = ANY($2::bigint[])",
];
static COUNT_USERS_DYN: std::sync::LazyLock<dynfilter::Compiled> = std::sync::LazyLock::new(|| {
    dynfilter::compile_with_arg_order(
        COUNT_USERS,
        dynfilter::Placeholders::Numbered,
        &[1usize, 2usize],
        &[dynfilter::Clause {
            header: 2usize,
            connector: dynfilter::Connector::And,
            items: &[3usize, 4usize],
        }],
    )
});
#[derive(Debug, Clone, Default)]
pub struct CountUsersParams<'a> {
    pub email: Option<&'a str>,
    pub ids: Option<&'a [i64]>,
}
pub struct CountUsersRow {
    pub total: i64,
}
impl CountUsersRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            total: row.try_get(0)?,
        })
    }
}
fn count_users_query<'p>(
    params: &'p CountUsersParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.email),
        dynfilter::Arg::from_option(&params.ids),
    ];
    let (sql, binds) = COUNT_USERS_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email as _,
            dynfilter::Bind::Arg(1usize) => &params.ids as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn count_users(
    client: &mut impl postgres::GenericClient,
    params: CountUsersParams<'_>,
) -> Result<CountUsersRow, postgres::Error> {
    let (sql, values) = count_users_query(&params);
    let row = client.query_one(sql.as_str(), &values)?;
    CountUsersRow::from_row(&row)
}
pub fn count_users_opt(
    client: &mut impl postgres::GenericClient,
    params: CountUsersParams<'_>,
) -> Result<Option<CountUsersRow>, postgres::Error> {
    let (sql, values) = count_users_query(&params);
    client
        .query_opt(sql.as_str(), &values)?
        .map(|row| CountUsersRow::from_row(&row))
        .transpose()
}
pub const TOUCH_USERS: &str = r"UPDATE users SET phone = phone
WHERE
  email = $1 -- :if $1
  AND users.id = ANY($2::bigint[]) -- :if $2";
pub const TOUCH_USERS_VARIANTS: &[&str] = &[
    r"UPDATE users SET phone = phone",
    r"UPDATE users SET phone = phone
WHERE
  users.id = ANY($1::bigint[])",
    r"UPDATE users SET phone = phone
WHERE
  email = $1",
    r"UPDATE users SET phone = phone
WHERE
  email = $1
  AND users.id = ANY($2::bigint[])",
];
static TOUCH_USERS_DYN: std::sync::LazyLock<dynfilter::Compiled> = std::sync::LazyLock::new(|| {
    dynfilter::compile_with_arg_order(
        TOUCH_USERS,
        dynfilter::Placeholders::Numbered,
        &[1usize, 2usize],
        &[dynfilter::Clause {
            header: 1usize,
            connector: dynfilter::Connector::And,
            items: &[2usize, 3usize],
        }],
    )
});
#[derive(Debug, Clone, Default)]
pub struct TouchUsersParams<'a> {
    pub email: Option<&'a str>,
    pub ids: Option<&'a [i64]>,
}
fn touch_users_query<'p>(
    params: &'p TouchUsersParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.email),
        dynfilter::Arg::from_option(&params.ids),
    ];
    let (sql, binds) = TOUCH_USERS_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email as _,
            dynfilter::Bind::Arg(1usize) => &params.ids as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn touch_users(
    client: &mut impl postgres::GenericClient,
    params: TouchUsersParams<'_>,
) -> Result<u64, postgres::Error> {
    let (sql, values) = touch_users_query(&params);
    client.execute(sql.as_str(), &values)
}
pub const LIST_ALL_USERS: &str = r"SELECT id, email, phone
FROM users
ORDER BY id";
pub struct ListAllUsersRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl ListAllUsersRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
pub fn prepare_list_all_users(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_ALL_USERS)
}
pub fn list_all_users(
    client: &mut impl postgres::GenericClient,
) -> Result<Vec<ListAllUsersRow>, postgres::Error> {
    self::list_all_users_with(client, LIST_ALL_USERS)
}
pub fn list_all_users_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<Vec<ListAllUsersRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    let rows = client.query(statement, values)?;
    rows.iter().map(ListAllUsersRow::from_row).collect()
}
pub fn list_all_users_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_all_users_iter_with(client, LIST_ALL_USERS)
}
pub fn list_all_users_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    client.query_raw(statement, values.iter().copied())
}
pub const SEARCH_USERS_BY_PROFILE: &str = r"SELECT id, email, phone
FROM users
WHERE
  email = $1 -- :if $1
  AND (profile @> $2::jsonb OR profile @> $2::jsonb) -- :if $2
ORDER BY id";
pub const SEARCH_USERS_BY_PROFILE_VARIANTS: &[&str] = &[
    r"SELECT id, email, phone
FROM users
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  (profile @> $1::jsonb OR profile @> $1::jsonb)
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
  AND (profile @> $2::jsonb OR profile @> $2::jsonb)
ORDER BY id",
];
static SEARCH_USERS_BY_PROFILE_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_USERS_BY_PROFILE,
            dynfilter::Placeholders::Numbered,
            &[1usize, 2usize],
            &[dynfilter::Clause {
                header: 2usize,
                connector: dynfilter::Connector::And,
                items: &[3usize, 4usize],
            }],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SearchUsersByProfileParams<'a> {
    pub email: Option<&'a str>,
    pub profile: Option<serde_json::Value>,
}
pub struct SearchUsersByProfileRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl SearchUsersByProfileRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn search_users_by_profile_query<'p>(
    params: &'p SearchUsersByProfileParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.email),
        dynfilter::Arg::from_option(&params.profile),
    ];
    let (sql, binds) = SEARCH_USERS_BY_PROFILE_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email as _,
            dynfilter::Bind::Arg(1usize) => &params.profile as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn search_users_by_profile(
    client: &mut impl postgres::GenericClient,
    params: SearchUsersByProfileParams<'_>,
) -> Result<Vec<SearchUsersByProfileRow>, postgres::Error> {
    let (sql, values) = search_users_by_profile_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter().map(SearchUsersByProfileRow::from_row).collect()
}
pub fn search_users_by_profile_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchUsersByProfileParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_users_by_profile_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const SET_USER_PHONE: &str = r"UPDATE users SET phone = $1
WHERE
  id = $2 -- :if $2";
pub const SET_USER_PHONE_VARIANTS: &[&str] = &[
    r"UPDATE users SET phone = $1",
    r"UPDATE users SET phone = $1
WHERE
  id = $2",
];
static SET_USER_PHONE_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SET_USER_PHONE,
            dynfilter::Placeholders::Numbered,
            &[1usize, 2usize],
            &[dynfilter::Clause {
                header: 1usize,
                connector: dynfilter::Connector::And,
                items: &[2usize],
            }],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SetUserPhoneParams<'a> {
    pub new_phone: &'a str,
    pub user_id: Option<i64>,
}
fn set_user_phone_query<'p>(
    params: &'p SetUserPhoneParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::Active,
        dynfilter::Arg::from_option(&params.user_id),
    ];
    let (sql, binds) = SET_USER_PHONE_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.new_phone as _,
            dynfilter::Bind::Arg(1usize) => &params.user_id as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn set_user_phone(
    client: &mut impl postgres::GenericClient,
    params: SetUserPhoneParams<'_>,
) -> Result<u64, postgres::Error> {
    let (sql, values) = set_user_phone_query(&params);
    client.execute(sql.as_str(), &values)
}
pub const GET_USER_BY_EMAIL: &str = r"SELECT id, email, phone
FROM users
WHERE
  email = $1 -- :if $1
ORDER BY id";
pub const GET_USER_BY_EMAIL_VARIANTS: &[&str] = &[
    r"SELECT id, email, phone
FROM users
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  email = $1
ORDER BY id",
];
static GET_USER_BY_EMAIL_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            GET_USER_BY_EMAIL,
            dynfilter::Placeholders::Numbered,
            &[1usize],
            &[dynfilter::Clause {
                header: 2usize,
                connector: dynfilter::Connector::And,
                items: &[3usize],
            }],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct GetUserByEmailParams<'a> {
    pub email: Option<&'a str>,
}
pub struct GetUserByEmailRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl GetUserByEmailRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn get_user_by_email_query<'p>(
    params: &'p GetUserByEmailParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [dynfilter::Arg::from_option(&params.email)];
    let (sql, binds) = GET_USER_BY_EMAIL_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn get_user_by_email(
    client: &mut impl postgres::GenericClient,
    params: GetUserByEmailParams<'_>,
) -> Result<GetUserByEmailRow, postgres::Error> {
    let (sql, values) = get_user_by_email_query(&params);
    let row = client.query_one(sql.as_str(), &values)?;
    GetUserByEmailRow::from_row(&row)
}
pub fn get_user_by_email_opt(
    client: &mut impl postgres::GenericClient,
    params: GetUserByEmailParams<'_>,
) -> Result<Option<GetUserByEmailRow>, postgres::Error> {
    let (sql, values) = get_user_by_email_query(&params);
    client
        .query_opt(sql.as_str(), &values)?
        .map(|row| GetUserByEmailRow::from_row(&row))
        .transpose()
}
pub const UPDATE_USER_EMAIL: &str = r"UPDATE users SET email = $1
WHERE
  id = $2
  AND email = $3 -- :if $3";
pub const UPDATE_USER_EMAIL_VARIANTS: &[&str] = &[
    r"UPDATE users SET email = $1
WHERE
  id = $2",
    r"UPDATE users SET email = $1
WHERE
  id = $2
  AND email = $3",
];
static UPDATE_USER_EMAIL_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            UPDATE_USER_EMAIL,
            dynfilter::Placeholders::Numbered,
            &[1usize, 2usize, 3usize],
            &[dynfilter::Clause {
                header: 1usize,
                connector: dynfilter::Connector::And,
                items: &[2usize, 3usize],
            }],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct UpdateUserEmailParams<'a> {
    pub new_email: &'a str,
    pub id: i64,
    pub email: Option<&'a str>,
}
fn update_user_email_query<'p>(
    params: &'p UpdateUserEmailParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::Active,
        dynfilter::Arg::Active,
        dynfilter::Arg::from_option(&params.email),
    ];
    let (sql, binds) = UPDATE_USER_EMAIL_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.new_email as _,
            dynfilter::Bind::Arg(1usize) => &params.id as _,
            dynfilter::Bind::Arg(2usize) => &params.email as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn update_user_email(
    client: &mut impl postgres::GenericClient,
    params: UpdateUserEmailParams<'_>,
) -> Result<(), postgres::Error> {
    let (sql, values) = update_user_email_query(&params);
    client.execute(sql.as_str(), &values).map(|_| ())
}
pub const LIST_USERS_BY_SCOPE: &str = r"SELECT id, email, phone
FROM users
WHERE
  TRUE -- :if $2
  AND EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id) -- :if $3
  AND NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id) -- :if $4
  AND users.id >= $1 -- :if $1
  AND users.phone <> '' -- :if $5
ORDER BY
  users.id DESC, -- :if $6
  users.id ASC, -- :if $7
  users.email ASC";
pub const LIST_USERS_BY_SCOPE_VARIANTS: &[&str] = &[
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.id >= $1
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.id >= $1
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  TRUE
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id DESC,
  users.email ASC",
    r"SELECT id, email, phone
FROM users
WHERE
  NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id)
  AND users.id >= $1
  AND users.phone <> ''
ORDER BY
  users.id ASC,
  users.email ASC",
];
static LIST_USERS_BY_SCOPE_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_USERS_BY_SCOPE,
            dynfilter::Placeholders::Numbered,
            &[1usize],
            &[
                dynfilter::Clause {
                    header: 2usize,
                    connector: dynfilter::Connector::And,
                    items: &[3usize, 4usize, 5usize, 6usize, 7usize],
                },
                dynfilter::Clause {
                    header: 8usize,
                    connector: dynfilter::Connector::Comma,
                    items: &[9usize, 10usize, 11usize],
                },
            ],
        )
    });
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ListUsersByScopeScope {
    #[default]
    Everyone,
    WithOrders,
    WithoutOrders,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ListUsersByScopeOrder {
    Newest,
    #[default]
    Oldest,
}
#[derive(Debug, Clone, Default)]
pub struct ListUsersByScopeParams {
    pub min_id: Option<i64>,
    pub scope: ListUsersByScopeScope,
    pub with_phone: bool,
    pub order: ListUsersByScopeOrder,
}
pub struct ListUsersByScopeRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl ListUsersByScopeRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn list_users_by_scope_query(
    params: &ListUsersByScopeParams,
) -> (
    String,
    Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.min_id),
        dynfilter::Arg::Flag(matches!(params.scope, ListUsersByScopeScope::Everyone)),
        dynfilter::Arg::Flag(matches!(params.scope, ListUsersByScopeScope::WithOrders)),
        dynfilter::Arg::Flag(matches!(params.scope, ListUsersByScopeScope::WithoutOrders)),
        dynfilter::Arg::Flag(params.with_phone),
        dynfilter::Arg::Flag(matches!(params.order, ListUsersByScopeOrder::Newest)),
        dynfilter::Arg::Flag(matches!(params.order, ListUsersByScopeOrder::Oldest)),
    ];
    let (sql, binds) = LIST_USERS_BY_SCOPE_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.min_id as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn list_users_by_scope(
    client: &mut impl postgres::GenericClient,
    params: ListUsersByScopeParams,
) -> Result<Vec<ListUsersByScopeRow>, postgres::Error> {
    let (sql, values) = list_users_by_scope_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter().map(ListUsersByScopeRow::from_row).collect()
}
pub fn list_users_by_scope_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: ListUsersByScopeParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = list_users_by_scope_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const SEARCH_USERS_WITH_ORDERS: &str = r"SELECT u.id, u.email, u.phone
FROM users u
JOIN orders o ON o.user_id = u.id AND o.created_at >= $1 -- :if $1
WHERE
  u.phone <> '' -- :if $2
ORDER BY
  o.created_at DESC, -- :if $1
  u.id ASC";
pub const SEARCH_USERS_WITH_ORDERS_VARIANTS: &[&str] = &[
    r"SELECT u.id, u.email, u.phone
FROM users u
ORDER BY
  u.id ASC",
    r"SELECT u.id, u.email, u.phone
FROM users u
WHERE
  u.phone <> ''
ORDER BY
  u.id ASC",
    r"SELECT u.id, u.email, u.phone
FROM users u
JOIN orders o ON o.user_id = u.id AND o.created_at >= $1
ORDER BY
  o.created_at DESC,
  u.id ASC",
    r"SELECT u.id, u.email, u.phone
FROM users u
JOIN orders o ON o.user_id = u.id AND o.created_at >= $1
WHERE
  u.phone <> ''
ORDER BY
  o.created_at DESC,
  u.id ASC",
];
static SEARCH_USERS_WITH_ORDERS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_USERS_WITH_ORDERS,
            dynfilter::Placeholders::Numbered,
            &[1usize],
            &[
                dynfilter::Clause {
                    header: 3usize,
                    connector: dynfilter::Connector::And,
                    items: &[4usize],
                },
                dynfilter::Clause {
                    header: 5usize,
                    connector: dynfilter::Connector::Comma,
                    items: &[6usize, 7usize],
                },
            ],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SearchUsersWithOrdersParams<'a> {
    pub orders_since: Option<&'a str>,
    pub with_phone: bool,
}
pub struct SearchUsersWithOrdersRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl SearchUsersWithOrdersRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn search_users_with_orders_query<'p>(
    params: &'p SearchUsersWithOrdersParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.orders_since),
        dynfilter::Arg::Flag(params.with_phone),
    ];
    let (sql, binds) = SEARCH_USERS_WITH_ORDERS_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.orders_since as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn search_users_with_orders(
    client: &mut impl postgres::GenericClient,
    params: SearchUsersWithOrdersParams<'_>,
) -> Result<Vec<SearchUsersWithOrdersRow>, postgres::Error> {
    let (sql, values) = search_users_with_orders_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter()
        .map(SearchUsersWithOrdersRow::from_row)
        .collect()
}
pub fn search_users_with_orders_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchUsersWithOrdersParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_users_with_orders_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const SEARCH_USERS_BY_PATTERN: &str = r"SELECT id, email, phone
FROM users
WHERE
  id > 0
  AND (

    FALSE
    OR email LIKE $1 -- :if $1
    OR phone LIKE $2 -- :if $2
  )
ORDER BY id";
pub const SEARCH_USERS_BY_PATTERN_VARIANTS: &[&str] = &[
    r"SELECT id, email, phone
FROM users
WHERE
  id > 0
  AND (

    FALSE
  )
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  id > 0
  AND (

    FALSE
    OR phone LIKE $1
  )
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  id > 0
  AND (

    FALSE
    OR email LIKE $1
  )
ORDER BY id",
    r"SELECT id, email, phone
FROM users
WHERE
  id > 0
  AND (

    FALSE
    OR email LIKE $1
    OR phone LIKE $2
  )
ORDER BY id",
];
static SEARCH_USERS_BY_PATTERN_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_USERS_BY_PATTERN,
            dynfilter::Placeholders::Numbered,
            &[1usize, 2usize],
            &[dynfilter::Clause {
                header: 5usize,
                connector: dynfilter::Connector::Or,
                items: &[6usize, 7usize, 8usize],
            }],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SearchUsersByPatternParams<'a> {
    pub email_pattern: Option<&'a str>,
    pub phone_pattern: Option<&'a str>,
}
pub struct SearchUsersByPatternRow {
    pub id: i64,
    pub email: String,
    pub phone: String,
}
impl SearchUsersByPatternRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
            phone: row.try_get(2)?,
        })
    }
}
fn search_users_by_pattern_query<'p>(
    params: &'p SearchUsersByPatternParams<'_>,
) -> (
    String,
    Vec<&'p (dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [
        dynfilter::Arg::from_option(&params.email_pattern),
        dynfilter::Arg::from_option(&params.phone_pattern),
    ];
    let (sql, binds) = SEARCH_USERS_BY_PATTERN_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.email_pattern as _,
            dynfilter::Bind::Arg(1usize) => &params.phone_pattern as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn search_users_by_pattern(
    client: &mut impl postgres::GenericClient,
    params: SearchUsersByPatternParams<'_>,
) -> Result<Vec<SearchUsersByPatternRow>, postgres::Error> {
    let (sql, values) = search_users_by_pattern_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter().map(SearchUsersByPatternRow::from_row).collect()
}
pub fn search_users_by_pattern_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchUsersByPatternParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_users_by_pattern_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const SEARCH_USERS_BY_LAST_ORDER: &str = r"SELECT u.id, u.email
FROM users u
JOIN ( -- :if $1
  SELECT user_id, max(created_at) AS last_order_at -- :if $1
  FROM orders -- :if $1
  GROUP BY user_id -- :if $1
) o ON o.user_id = u.id -- :if $1
WHERE
  u.id > 0
  AND last_order_at >= '2024-06-01' -- :if $1
ORDER BY
  coalesce(last_order_at, '') DESC, -- :if $1
  u.id ASC";
pub const SEARCH_USERS_BY_LAST_ORDER_VARIANTS: &[&str] = &[
    r"SELECT u.id, u.email
FROM users u
WHERE
  u.id > 0
ORDER BY
  u.id ASC",
    r"SELECT u.id, u.email
FROM users u
JOIN (
  SELECT user_id, max(created_at) AS last_order_at
  FROM orders
  GROUP BY user_id
) o ON o.user_id = u.id
WHERE
  u.id > 0
  AND last_order_at >= '2024-06-01'
ORDER BY
  coalesce(last_order_at, '') DESC,
  u.id ASC",
];
static SEARCH_USERS_BY_LAST_ORDER_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_USERS_BY_LAST_ORDER,
            dynfilter::Placeholders::Numbered,
            &[],
            &[
                dynfilter::Clause {
                    header: 7usize,
                    connector: dynfilter::Connector::And,
                    items: &[8usize, 9usize],
                },
                dynfilter::Clause {
                    header: 10usize,
                    connector: dynfilter::Connector::Comma,
                    items: &[11usize, 12usize],
                },
            ],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SearchUsersByLastOrderParams {
    pub with_orders: bool,
}
pub struct SearchUsersByLastOrderRow {
    pub id: i64,
    pub email: String,
}
impl SearchUsersByLastOrderRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            email: row.try_get(1)?,
        })
    }
}
fn search_users_by_last_order_query(
    params: &SearchUsersByLastOrderParams,
) -> (
    String,
    Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [dynfilter::Arg::Flag(params.with_orders)];
    let (sql, binds) = SEARCH_USERS_BY_LAST_ORDER_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|_| -> &(dyn postgres::types::ToSql + ::std::marker::Sync) {
            unreachable!("dynfilter bind plan referenced an unknown argument")
        })
        .collect();
    (sql, values)
}
pub fn search_users_by_last_order(
    client: &mut impl postgres::GenericClient,
    params: SearchUsersByLastOrderParams,
) -> Result<Vec<SearchUsersByLastOrderRow>, postgres::Error> {
    let (sql, values) = search_users_by_last_order_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter()
        .map(SearchUsersByLastOrderRow::from_row)
        .collect()
}
pub fn search_users_by_last_order_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchUsersByLastOrderParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_users_by_last_order_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const QUERIES: &[(&str, &str)] = &[
    ("SearchUsers", SEARCH_USERS),
    ("CountUsers", COUNT_USERS),
    ("TouchUsers", TOUCH_USERS),
    ("ListAllUsers", LIST_ALL_USERS),
    ("SearchUsersByProfile", SEARCH_USERS_BY_PROFILE),
    ("SetUserPhone", SET_USER_PHONE),
    ("GetUserByEmail", GET_USER_BY_EMAIL),
    ("UpdateUserEmail", UPDATE_USER_EMAIL),
    ("ListUsersByScope", LIST_USERS_BY_SCOPE),
    ("SearchUsersWithOrders", SEARCH_USERS_WITH_ORDERS),
    ("SearchUsersByPattern", SEARCH_USERS_BY_PATTERN),
    ("SearchUsersByLastOrder", SEARCH_USERS_BY_LAST_ORDER),
];
