//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.1

#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "order_status")]
pub enum OrderStatus {
    #[postgres(name = "pending")]
    Pending,
    #[postgres(name = "processing")]
    Processing,
    #[postgres(name = "shipped")]
    Shipped,
    #[postgres(name = "delivered")]
    Delivered,
    #[postgres(name = "cancelled")]
    Cancelled,
}
pub const CREATE_USER: &str = r"INSERT INTO users (
    username, email, hashed_password, full_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, email, hashed_password, full_name, created_at, updated_at";
#[derive(Debug, Clone, Default)]
pub struct CreateUserParams<'a> {
    pub username: &'a str,
    pub email: &'a str,
    pub hashed_password: &'a str,
    pub full_name: Option<&'a str>,
}
pub struct CreateUserRow {
    pub id: uuid::Uuid,
    pub username: String,
    pub email: String,
    pub hashed_password: String,
    pub full_name: Option<String>,
    pub created_at: chrono::DateTime<chrono::Local>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
impl CreateUserRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            username: row.try_get(1)?,
            email: row.try_get(2)?,
            hashed_password: row.try_get(3)?,
            full_name: row.try_get(4)?,
            created_at: row.try_get(5)?,
            updated_at: row.try_get(6)?,
        })
    }
}
pub fn prepare_create_user(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_USER)
}
pub fn create_user(
    client: &mut impl postgres::GenericClient,
    params: CreateUserParams<'_>,
) -> Result<CreateUserRow, postgres::Error> {
    self::create_user_with(client, CREATE_USER, params)
}
pub fn create_user_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateUserParams<'_>,
) -> Result<CreateUserRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.username,
        &params.email,
        &params.hashed_password,
        &params.full_name,
    ];
    let row = client.query_one(statement, values)?;
    CreateUserRow::from_row(&row)
}
pub fn create_user_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateUserParams<'_>,
) -> Result<Option<CreateUserRow>, postgres::Error> {
    self::create_user_opt_with(client, CREATE_USER, params)
}
pub fn create_user_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateUserParams<'_>,
) -> Result<Option<CreateUserRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.username,
        &params.email,
        &params.hashed_password,
        &params.full_name,
    ];
    client
        .query_opt(statement, values)?
        .map(|row| CreateUserRow::from_row(&row))
        .transpose()
}
pub const GET_USER_BY_EMAIL: &str = r"SELECT id, username, email, hashed_password, full_name, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1";
pub struct GetUserByEmailRow {
    pub id: uuid::Uuid,
    pub username: String,
    pub email: String,
    pub hashed_password: String,
    pub full_name: Option<String>,
    pub created_at: chrono::DateTime<chrono::Local>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
impl GetUserByEmailRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            username: row.try_get(1)?,
            email: row.try_get(2)?,
            hashed_password: row.try_get(3)?,
            full_name: row.try_get(4)?,
            created_at: row.try_get(5)?,
            updated_at: row.try_get(6)?,
        })
    }
}
pub fn prepare_get_user_by_email(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_USER_BY_EMAIL)
}
pub fn get_user_by_email(
    client: &mut impl postgres::GenericClient,
    email: &str,
) -> Result<GetUserByEmailRow, postgres::Error> {
    self::get_user_by_email_with(client, GET_USER_BY_EMAIL, email)
}
pub fn get_user_by_email_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    email: &str,
) -> Result<GetUserByEmailRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&email];
    let row = client.query_one(statement, values)?;
    GetUserByEmailRow::from_row(&row)
}
pub fn get_user_by_email_opt(
    client: &mut impl postgres::GenericClient,
    email: &str,
) -> Result<Option<GetUserByEmailRow>, postgres::Error> {
    self::get_user_by_email_opt_with(client, GET_USER_BY_EMAIL, email)
}
pub fn get_user_by_email_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    email: &str,
) -> Result<Option<GetUserByEmailRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&email];
    client
        .query_opt(statement, values)?
        .map(|row| GetUserByEmailRow::from_row(&row))
        .transpose()
}
pub const LIST_USERS: &str = r"SELECT id, username, email, full_name, created_at FROM users
ORDER BY created_at DESC
LIMIT $2::int
OFFSET $1::int";
#[derive(Debug, Clone, Default)]
pub struct ListUsersParams {
    pub offset: i32,
    pub limit: i32,
}
pub struct ListUsersRow {
    pub id: uuid::Uuid,
    pub username: String,
    pub email: String,
    pub full_name: Option<String>,
    pub created_at: chrono::DateTime<chrono::Local>,
}
impl ListUsersRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            username: row.try_get(1)?,
            email: row.try_get(2)?,
            full_name: row.try_get(3)?,
            created_at: row.try_get(4)?,
        })
    }
}
pub fn prepare_list_users(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_USERS)
}
pub fn list_users(
    client: &mut impl postgres::GenericClient,
    params: ListUsersParams,
) -> Result<Vec<ListUsersRow>, postgres::Error> {
    self::list_users_with(client, LIST_USERS, params)
}
pub fn list_users_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListUsersParams,
) -> Result<Vec<ListUsersRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.offset, &params.limit];
    let rows = client.query(statement, values)?;
    rows.iter().map(ListUsersRow::from_row).collect()
}
pub fn list_users_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: ListUsersParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_users_iter_with(client, LIST_USERS, params)
}
pub fn list_users_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListUsersParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.offset, &params.limit];
    client.query_raw(statement, values.iter().copied())
}
pub const CREATE_PRODUCT: &str = r"INSERT INTO products (
    category_id, name, description, price, stock_quantity, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, category_id, name, description, price, stock_quantity, attributes, created_at, updated_at";
#[derive(Debug, Clone, Default)]
pub struct CreateProductParams<'a> {
    pub category_id: i32,
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub price: i32,
    pub stock_quantity: i32,
    pub attributes: Option<serde_json::Value>,
}
pub struct CreateProductRow {
    pub id: uuid::Uuid,
    pub category_id: i32,
    pub name: String,
    pub description: Option<String>,
    pub price: i32,
    pub stock_quantity: i32,
    pub attributes: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
impl CreateProductRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            category_id: row.try_get(1)?,
            name: row.try_get(2)?,
            description: row.try_get(3)?,
            price: row.try_get(4)?,
            stock_quantity: row.try_get(5)?,
            attributes: row.try_get(6)?,
            created_at: row.try_get(7)?,
            updated_at: row.try_get(8)?,
        })
    }
}
pub fn prepare_create_product(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_PRODUCT)
}
pub fn create_product(
    client: &mut impl postgres::GenericClient,
    params: CreateProductParams<'_>,
) -> Result<CreateProductRow, postgres::Error> {
    self::create_product_with(client, CREATE_PRODUCT, params)
}
pub fn create_product_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateProductParams<'_>,
) -> Result<CreateProductRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.category_id,
        &params.name,
        &params.description,
        &params.price,
        &params.stock_quantity,
        &params.attributes,
    ];
    let row = client.query_one(statement, values)?;
    CreateProductRow::from_row(&row)
}
pub fn create_product_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateProductParams<'_>,
) -> Result<Option<CreateProductRow>, postgres::Error> {
    self::create_product_opt_with(client, CREATE_PRODUCT, params)
}
pub fn create_product_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateProductParams<'_>,
) -> Result<Option<CreateProductRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.category_id,
        &params.name,
        &params.description,
        &params.price,
        &params.stock_quantity,
        &params.attributes,
    ];
    client
        .query_opt(statement, values)?
        .map(|row| CreateProductRow::from_row(&row))
        .transpose()
}
pub const GET_PRODUCT_WITH_CATEGORY: &str = r"SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock_quantity,
    p.attributes,
    p.created_at,
    c.name as category_name,
    c.slug as category_slug
FROM
    products p
JOIN
    categories c ON p.category_id = c.id
WHERE
    p.id = $1";
pub struct GetProductWithCategoryRow {
    pub id: uuid::Uuid,
    pub name: String,
    pub description: Option<String>,
    pub price: i32,
    pub stock_quantity: i32,
    pub attributes: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub category_name: String,
    pub category_slug: String,
}
impl GetProductWithCategoryRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            description: row.try_get(2)?,
            price: row.try_get(3)?,
            stock_quantity: row.try_get(4)?,
            attributes: row.try_get(5)?,
            created_at: row.try_get(6)?,
            category_name: row.try_get(7)?,
            category_slug: row.try_get(8)?,
        })
    }
}
pub fn prepare_get_product_with_category(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_PRODUCT_WITH_CATEGORY)
}
pub fn get_product_with_category(
    client: &mut impl postgres::GenericClient,
    id: uuid::Uuid,
) -> Result<GetProductWithCategoryRow, postgres::Error> {
    self::get_product_with_category_with(client, GET_PRODUCT_WITH_CATEGORY, id)
}
pub fn get_product_with_category_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: uuid::Uuid,
) -> Result<GetProductWithCategoryRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    let row = client.query_one(statement, values)?;
    GetProductWithCategoryRow::from_row(&row)
}
pub fn get_product_with_category_opt(
    client: &mut impl postgres::GenericClient,
    id: uuid::Uuid,
) -> Result<Option<GetProductWithCategoryRow>, postgres::Error> {
    self::get_product_with_category_opt_with(client, GET_PRODUCT_WITH_CATEGORY, id)
}
pub fn get_product_with_category_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: uuid::Uuid,
) -> Result<Option<GetProductWithCategoryRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client
        .query_opt(statement, values)?
        .map(|row| GetProductWithCategoryRow::from_row(&row))
        .transpose()
}
pub const SEARCH_PRODUCTS: &str = r"SELECT
    p.id, p.category_id, p.name, p.description, p.price, p.stock_quantity, p.attributes, p.created_at, p.updated_at,
    (SELECT AVG(r.rating) FROM reviews r WHERE r.product_id = p.id) as average_rating
FROM products p
WHERE
    (p.name ILIKE $1 OR p.description ILIKE $1)
AND
    p.category_id = ANY($2::int[])
AND
    p.price >= $3
AND
    p.price <= $4
AND
    p.stock_quantity > 0
ORDER BY
    p.created_at DESC
LIMIT $6::int
OFFSET $5::int";
#[derive(Debug, Clone, Default)]
pub struct SearchProductsParams<'a> {
    pub name: Option<&'a str>,
    pub category_ids: &'a [i32],
    pub min_price: Option<i32>,
    pub max_price: Option<i32>,
    pub offset: i32,
    pub limit: i32,
}
pub struct SearchProductsRow {
    pub id: uuid::Uuid,
    pub category_id: i32,
    pub name: String,
    pub description: Option<String>,
    pub price: i32,
    pub stock_quantity: i32,
    pub attributes: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub average_rating: f64,
}
impl SearchProductsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            category_id: row.try_get(1)?,
            name: row.try_get(2)?,
            description: row.try_get(3)?,
            price: row.try_get(4)?,
            stock_quantity: row.try_get(5)?,
            attributes: row.try_get(6)?,
            created_at: row.try_get(7)?,
            updated_at: row.try_get(8)?,
            average_rating: row.try_get(9)?,
        })
    }
}
pub fn prepare_search_products(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(SEARCH_PRODUCTS)
}
pub fn search_products(
    client: &mut impl postgres::GenericClient,
    params: SearchProductsParams<'_>,
) -> Result<Vec<SearchProductsRow>, postgres::Error> {
    self::search_products_with(client, SEARCH_PRODUCTS, params)
}
pub fn search_products_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: SearchProductsParams<'_>,
) -> Result<Vec<SearchProductsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.name,
        &params.category_ids,
        &params.min_price,
        &params.max_price,
        &params.offset,
        &params.limit,
    ];
    let rows = client.query(statement, values)?;
    rows.iter().map(SearchProductsRow::from_row).collect()
}
pub fn search_products_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchProductsParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::search_products_iter_with(client, SEARCH_PRODUCTS, params)
}
pub fn search_products_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: SearchProductsParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.name,
        &params.category_ids,
        &params.min_price,
        &params.max_price,
        &params.offset,
        &params.limit,
    ];
    client.query_raw(statement, values.iter().copied())
}
pub const GET_PRODUCTS_WITH_SPECIFIC_ATTRIBUTE: &str = r"SELECT id, category_id, name, description, price, stock_quantity, attributes, created_at, updated_at FROM products
WHERE attributes @> $1::jsonb";
pub struct GetProductsWithSpecificAttributeRow {
    pub id: uuid::Uuid,
    pub category_id: i32,
    pub name: String,
    pub description: Option<String>,
    pub price: i32,
    pub stock_quantity: i32,
    pub attributes: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
impl GetProductsWithSpecificAttributeRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            category_id: row.try_get(1)?,
            name: row.try_get(2)?,
            description: row.try_get(3)?,
            price: row.try_get(4)?,
            stock_quantity: row.try_get(5)?,
            attributes: row.try_get(6)?,
            created_at: row.try_get(7)?,
            updated_at: row.try_get(8)?,
        })
    }
}
pub fn prepare_get_products_with_specific_attribute(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_PRODUCTS_WITH_SPECIFIC_ATTRIBUTE)
}
pub fn get_products_with_specific_attribute(
    client: &mut impl postgres::GenericClient,
    column_1: serde_json::Value,
) -> Result<Vec<GetProductsWithSpecificAttributeRow>, postgres::Error> {
    self::get_products_with_specific_attribute_with(
        client,
        GET_PRODUCTS_WITH_SPECIFIC_ATTRIBUTE,
        column_1,
    )
}
pub fn get_products_with_specific_attribute_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    column_1: serde_json::Value,
) -> Result<Vec<GetProductsWithSpecificAttributeRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&column_1];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(GetProductsWithSpecificAttributeRow::from_row)
        .collect()
}
pub fn get_products_with_specific_attribute_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    column_1: serde_json::Value,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::get_products_with_specific_attribute_iter_with(
        client,
        GET_PRODUCTS_WITH_SPECIFIC_ATTRIBUTE,
        column_1,
    )
}
pub fn get_products_with_specific_attribute_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    column_1: serde_json::Value,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&column_1];
    client.query_raw(statement, values.iter().copied())
}
pub const UPDATE_PRODUCT_STOCK: &str = r"UPDATE products
SET stock_quantity = stock_quantity + $2
WHERE id = $1";
#[derive(Debug, Clone, Default)]
pub struct UpdateProductStockParams {
    pub id: uuid::Uuid,
    pub add_quantity: i32,
}
pub fn prepare_update_product_stock(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(UPDATE_PRODUCT_STOCK)
}
pub fn update_product_stock(
    client: &mut impl postgres::GenericClient,
    params: UpdateProductStockParams,
) -> Result<(), postgres::Error> {
    self::update_product_stock_with(client, UPDATE_PRODUCT_STOCK, params)
}
pub fn update_product_stock_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: UpdateProductStockParams,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.id, &params.add_quantity];
    client.execute(statement, values).map(|_| ())
}
pub const CREATE_ORDER: &str = r"INSERT INTO orders (user_id, status, total_amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, status, total_amount, ordered_at";
#[derive(Debug, Clone)]
pub struct CreateOrderParams {
    pub user_id: uuid::Uuid,
    pub status: OrderStatus,
    pub total_amount: i32,
}
pub struct CreateOrderRow {
    pub id: i64,
    pub user_id: uuid::Uuid,
    pub status: OrderStatus,
    pub total_amount: i32,
    pub ordered_at: chrono::DateTime<chrono::Utc>,
}
impl CreateOrderRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            user_id: row.try_get(1)?,
            status: row.try_get(2)?,
            total_amount: row.try_get(3)?,
            ordered_at: row.try_get(4)?,
        })
    }
}
pub fn prepare_create_order(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_ORDER)
}
pub fn create_order(
    client: &mut impl postgres::GenericClient,
    params: CreateOrderParams,
) -> Result<CreateOrderRow, postgres::Error> {
    self::create_order_with(client, CREATE_ORDER, params)
}
pub fn create_order_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateOrderParams,
) -> Result<CreateOrderRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.user_id, &params.status, &params.total_amount];
    let row = client.query_one(statement, values)?;
    CreateOrderRow::from_row(&row)
}
pub fn create_order_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateOrderParams,
) -> Result<Option<CreateOrderRow>, postgres::Error> {
    self::create_order_opt_with(client, CREATE_ORDER, params)
}
pub fn create_order_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateOrderParams,
) -> Result<Option<CreateOrderRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.user_id, &params.status, &params.total_amount];
    client
        .query_opt(statement, values)?
        .map(|row| CreateOrderRow::from_row(&row))
        .transpose()
}
pub const CREATE_ORDER_ITEM: &str = r"INSERT INTO order_items (order_id, product_id, quantity, price_at_purchase)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_at_purchase";
#[derive(Debug, Clone, Default)]
pub struct CreateOrderItemParams {
    pub order_id: i64,
    pub product_id: uuid::Uuid,
    pub quantity: i32,
    pub price_at_purchase: i32,
}
pub struct CreateOrderItemRow {
    pub id: i64,
    pub order_id: i64,
    pub product_id: uuid::Uuid,
    pub quantity: i32,
    pub price_at_purchase: i32,
}
impl CreateOrderItemRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            order_id: row.try_get(1)?,
            product_id: row.try_get(2)?,
            quantity: row.try_get(3)?,
            price_at_purchase: row.try_get(4)?,
        })
    }
}
pub fn prepare_create_order_item(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_ORDER_ITEM)
}
pub fn create_order_item(
    client: &mut impl postgres::GenericClient,
    params: CreateOrderItemParams,
) -> Result<CreateOrderItemRow, postgres::Error> {
    self::create_order_item_with(client, CREATE_ORDER_ITEM, params)
}
pub fn create_order_item_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateOrderItemParams,
) -> Result<CreateOrderItemRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.order_id,
        &params.product_id,
        &params.quantity,
        &params.price_at_purchase,
    ];
    let row = client.query_one(statement, values)?;
    CreateOrderItemRow::from_row(&row)
}
pub fn create_order_item_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateOrderItemParams,
) -> Result<Option<CreateOrderItemRow>, postgres::Error> {
    self::create_order_item_opt_with(client, CREATE_ORDER_ITEM, params)
}
pub fn create_order_item_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateOrderItemParams,
) -> Result<Option<CreateOrderItemRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.order_id,
        &params.product_id,
        &params.quantity,
        &params.price_at_purchase,
    ];
    client
        .query_opt(statement, values)?
        .map(|row| CreateOrderItemRow::from_row(&row))
        .transpose()
}
pub const GET_ORDER_DETAILS: &str = r"SELECT
    o.id as order_id,
    o.status,
    o.total_amount,
    o.ordered_at,
    u.id as user_id,
    u.username,
    u.email
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.id = $1";
pub struct GetOrderDetailsRow {
    pub order_id: i64,
    pub status: OrderStatus,
    pub total_amount: i32,
    pub ordered_at: chrono::DateTime<chrono::Utc>,
    pub user_id: uuid::Uuid,
    pub username: String,
    pub email: String,
}
impl GetOrderDetailsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            order_id: row.try_get(0)?,
            status: row.try_get(1)?,
            total_amount: row.try_get(2)?,
            ordered_at: row.try_get(3)?,
            user_id: row.try_get(4)?,
            username: row.try_get(5)?,
            email: row.try_get(6)?,
        })
    }
}
pub fn prepare_get_order_details(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_ORDER_DETAILS)
}
pub fn get_order_details(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<GetOrderDetailsRow, postgres::Error> {
    self::get_order_details_with(client, GET_ORDER_DETAILS, id)
}
pub fn get_order_details_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<GetOrderDetailsRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    let row = client.query_one(statement, values)?;
    GetOrderDetailsRow::from_row(&row)
}
pub fn get_order_details_opt(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<Option<GetOrderDetailsRow>, postgres::Error> {
    self::get_order_details_opt_with(client, GET_ORDER_DETAILS, id)
}
pub fn get_order_details_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<Option<GetOrderDetailsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client
        .query_opt(statement, values)?
        .map(|row| GetOrderDetailsRow::from_row(&row))
        .transpose()
}
pub const LIST_ORDER_ITEMS_BY_ORDER_ID: &str = r"SELECT
    oi.quantity,
    oi.price_at_purchase,
    p.id as product_id,
    p.name as product_name
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = $1";
pub struct ListOrderItemsByOrderIdRow {
    pub quantity: i32,
    pub price_at_purchase: i32,
    pub product_id: uuid::Uuid,
    pub product_name: String,
}
impl ListOrderItemsByOrderIdRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            quantity: row.try_get(0)?,
            price_at_purchase: row.try_get(1)?,
            product_id: row.try_get(2)?,
            product_name: row.try_get(3)?,
        })
    }
}
pub fn prepare_list_order_items_by_order_id(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_ORDER_ITEMS_BY_ORDER_ID)
}
pub fn list_order_items_by_order_id(
    client: &mut impl postgres::GenericClient,
    order_id: i64,
) -> Result<Vec<ListOrderItemsByOrderIdRow>, postgres::Error> {
    self::list_order_items_by_order_id_with(client, LIST_ORDER_ITEMS_BY_ORDER_ID, order_id)
}
pub fn list_order_items_by_order_id_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    order_id: i64,
) -> Result<Vec<ListOrderItemsByOrderIdRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&order_id];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(ListOrderItemsByOrderIdRow::from_row)
        .collect()
}
pub fn list_order_items_by_order_id_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    order_id: i64,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_order_items_by_order_id_iter_with(client, LIST_ORDER_ITEMS_BY_ORDER_ID, order_id)
}
pub fn list_order_items_by_order_id_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    order_id: i64,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&order_id];
    client.query_raw(statement, values.iter().copied())
}
pub const CREATE_REVIEW: &str = r"INSERT INTO reviews (user_id, product_id, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, product_id, rating, comment, created_at";
#[derive(Debug, Clone, Default)]
pub struct CreateReviewParams<'a> {
    pub user_id: uuid::Uuid,
    pub product_id: uuid::Uuid,
    pub rating: i32,
    pub comment: Option<&'a str>,
}
pub struct CreateReviewRow {
    pub id: i64,
    pub user_id: uuid::Uuid,
    pub product_id: uuid::Uuid,
    pub rating: i32,
    pub comment: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}
impl CreateReviewRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            user_id: row.try_get(1)?,
            product_id: row.try_get(2)?,
            rating: row.try_get(3)?,
            comment: row.try_get(4)?,
            created_at: row.try_get(5)?,
        })
    }
}
pub fn prepare_create_review(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_REVIEW)
}
pub fn create_review(
    client: &mut impl postgres::GenericClient,
    params: CreateReviewParams<'_>,
) -> Result<CreateReviewRow, postgres::Error> {
    self::create_review_with(client, CREATE_REVIEW, params)
}
pub fn create_review_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateReviewParams<'_>,
) -> Result<CreateReviewRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.user_id,
        &params.product_id,
        &params.rating,
        &params.comment,
    ];
    let row = client.query_one(statement, values)?;
    CreateReviewRow::from_row(&row)
}
pub fn create_review_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateReviewParams<'_>,
) -> Result<Option<CreateReviewRow>, postgres::Error> {
    self::create_review_opt_with(client, CREATE_REVIEW, params)
}
pub fn create_review_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateReviewParams<'_>,
) -> Result<Option<CreateReviewRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.user_id,
        &params.product_id,
        &params.rating,
        &params.comment,
    ];
    client
        .query_opt(statement, values)?
        .map(|row| CreateReviewRow::from_row(&row))
        .transpose()
}
pub const GET_PRODUCT_AVERAGE_RATING: &str = r"SELECT
    product_id,
    AVG(rating)::float as average_rating,
    COUNT(id) as review_count
FROM reviews
WHERE product_id = $1
GROUP BY product_id";
pub struct GetProductAverageRatingRow {
    pub product_id: uuid::Uuid,
    pub average_rating: f64,
    pub review_count: i64,
}
impl GetProductAverageRatingRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            product_id: row.try_get(0)?,
            average_rating: row.try_get(1)?,
            review_count: row.try_get(2)?,
        })
    }
}
pub fn prepare_get_product_average_rating(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_PRODUCT_AVERAGE_RATING)
}
pub fn get_product_average_rating(
    client: &mut impl postgres::GenericClient,
    product_id: uuid::Uuid,
) -> Result<GetProductAverageRatingRow, postgres::Error> {
    self::get_product_average_rating_with(client, GET_PRODUCT_AVERAGE_RATING, product_id)
}
pub fn get_product_average_rating_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    product_id: uuid::Uuid,
) -> Result<GetProductAverageRatingRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&product_id];
    let row = client.query_one(statement, values)?;
    GetProductAverageRatingRow::from_row(&row)
}
pub fn get_product_average_rating_opt(
    client: &mut impl postgres::GenericClient,
    product_id: uuid::Uuid,
) -> Result<Option<GetProductAverageRatingRow>, postgres::Error> {
    self::get_product_average_rating_opt_with(client, GET_PRODUCT_AVERAGE_RATING, product_id)
}
pub fn get_product_average_rating_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    product_id: uuid::Uuid,
) -> Result<Option<GetProductAverageRatingRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&product_id];
    client
        .query_opt(statement, values)?
        .map(|row| GetProductAverageRatingRow::from_row(&row))
        .transpose()
}
pub const GET_CATEGORY_SALES_RANKING: &str = r"SELECT
    c.id as category_id,
    c.name as category_name,
    SUM(oi.quantity * oi.price_at_purchase) as total_sales,
    COUNT(DISTINCT o.id) as total_orders
FROM categories c
JOIN products p ON c.id = p.category_id
JOIN order_items oi ON p.id = oi.product_id
JOIN orders o ON oi.order_id = o.id
WHERE o.status IN ('delivered', 'shipped')
GROUP BY c.id, c.name
ORDER BY total_sales DESC";
pub struct GetCategorySalesRankingRow {
    pub category_id: i32,
    pub category_name: String,
    pub total_sales: i64,
    pub total_orders: i64,
}
impl GetCategorySalesRankingRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            category_id: row.try_get(0)?,
            category_name: row.try_get(1)?,
            total_sales: row.try_get(2)?,
            total_orders: row.try_get(3)?,
        })
    }
}
pub fn prepare_get_category_sales_ranking(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_CATEGORY_SALES_RANKING)
}
pub fn get_category_sales_ranking(
    client: &mut impl postgres::GenericClient,
) -> Result<Vec<GetCategorySalesRankingRow>, postgres::Error> {
    self::get_category_sales_ranking_with(client, GET_CATEGORY_SALES_RANKING)
}
pub fn get_category_sales_ranking_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<Vec<GetCategorySalesRankingRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(GetCategorySalesRankingRow::from_row)
        .collect()
}
pub fn get_category_sales_ranking_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::get_category_sales_ranking_iter_with(client, GET_CATEGORY_SALES_RANKING)
}
pub fn get_category_sales_ranking_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    client.query_raw(statement, values.iter().copied())
}
pub const DELETE_USER_AND_RELATED_DATA: &str = r"DELETE FROM users WHERE id = $1";
pub fn prepare_delete_user_and_related_data(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(DELETE_USER_AND_RELATED_DATA)
}
pub fn delete_user_and_related_data(
    client: &mut impl postgres::GenericClient,
    id: uuid::Uuid,
) -> Result<(), postgres::Error> {
    self::delete_user_and_related_data_with(client, DELETE_USER_AND_RELATED_DATA, id)
}
pub fn delete_user_and_related_data_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: uuid::Uuid,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client.execute(statement, values).map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("CreateUser", CREATE_USER),
    ("GetUserByEmail", GET_USER_BY_EMAIL),
    ("ListUsers", LIST_USERS),
    ("CreateProduct", CREATE_PRODUCT),
    ("GetProductWithCategory", GET_PRODUCT_WITH_CATEGORY),
    ("SearchProducts", SEARCH_PRODUCTS),
    (
        "GetProductsWithSpecificAttribute",
        GET_PRODUCTS_WITH_SPECIFIC_ATTRIBUTE,
    ),
    ("UpdateProductStock", UPDATE_PRODUCT_STOCK),
    ("CreateOrder", CREATE_ORDER),
    ("CreateOrderItem", CREATE_ORDER_ITEM),
    ("GetOrderDetails", GET_ORDER_DETAILS),
    ("ListOrderItemsByOrderID", LIST_ORDER_ITEMS_BY_ORDER_ID),
    ("CreateReview", CREATE_REVIEW),
    ("GetProductAverageRating", GET_PRODUCT_AVERAGE_RATING),
    ("GetCategorySalesRanking", GET_CATEGORY_SALES_RANKING),
    ("DeleteUserAndRelatedData", DELETE_USER_AND_RELATED_DATA),
];
