//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.1

pub trait RusqliteClient {
    fn connection(&self) -> &rusqlite::Connection;
}
impl RusqliteClient for rusqlite::Connection {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Savepoint<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
pub const GET_MAPPING: &str = r"SELECT
    aff_integer_val,
    aff_real_val,
    aff_text_val,
    aff_blob_val,
    int_val,
    integer_val,
    tinyint_val,
    smallint_val,
    mediumint_val,
    bigint_val,
    unsigned_big_int_val,
    int2_val,
    int8_val,
    character20_val,
    varchar255_val,
    varying_char255_val,
    nchar55_val,
    native_char70_val,
    nvarchar100_val,
    text_val,
    clob_val,
    real_val,
    double_val,
    double_precision_val,
    float_val,
    numeric_val,
    decimal10_5_val,
    boolean_val,
    date_val,
    time_val,
    datetime_val
FROM mapping";
pub struct GetMappingRow {
    pub aff_integer_val: i64,
    pub aff_real_val: f64,
    pub aff_text_val: String,
    pub aff_blob_val: Vec<u8>,
    pub int_val: i64,
    pub integer_val: i64,
    pub tinyint_val: i8,
    pub smallint_val: i16,
    pub mediumint_val: i32,
    pub bigint_val: i64,
    pub unsigned_big_int_val: i64,
    pub int_2_val: i16,
    pub int_8_val: i64,
    pub character_20_val: String,
    pub varchar_255_val: String,
    pub varying_char_255_val: String,
    pub nchar_55_val: String,
    pub native_char_70_val: String,
    pub nvarchar_100_val: String,
    pub text_val: String,
    pub clob_val: String,
    pub real_val: f64,
    pub double_val: f64,
    pub double_precision_val: f64,
    pub float_val: f64,
    pub numeric_val: f64,
    pub decimal_10_5_val: f64,
    pub boolean_val: bool,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub datetime_val: chrono::NaiveDateTime,
}
impl GetMappingRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            aff_integer_val: row.get(0)?,
            aff_real_val: row.get(1)?,
            aff_text_val: row.get(2)?,
            aff_blob_val: row.get(3)?,
            int_val: row.get(4)?,
            integer_val: row.get(5)?,
            tinyint_val: row.get(6)?,
            smallint_val: row.get(7)?,
            mediumint_val: row.get(8)?,
            bigint_val: row.get(9)?,
            unsigned_big_int_val: row.get(10)?,
            int_2_val: row.get(11)?,
            int_8_val: row.get(12)?,
            character_20_val: row.get(13)?,
            varchar_255_val: row.get(14)?,
            varying_char_255_val: row.get(15)?,
            nchar_55_val: row.get(16)?,
            native_char_70_val: row.get(17)?,
            nvarchar_100_val: row.get(18)?,
            text_val: row.get(19)?,
            clob_val: row.get(20)?,
            real_val: row.get(21)?,
            double_val: row.get(22)?,
            double_precision_val: row.get(23)?,
            float_val: row.get(24)?,
            numeric_val: row.get(25)?,
            decimal_10_5_val: row.get(26)?,
            boolean_val: row.get(27)?,
            date_val: row.get(28)?,
            time_val: row.get(29)?,
            datetime_val: row.get(30)?,
        })
    }
}
pub fn get_mapping(client: &impl RusqliteClient) -> rusqlite::Result<GetMappingRow> {
    let params = rusqlite::params![];
    let mut statement = client.connection().prepare_cached(GET_MAPPING)?;
    statement.query_row(params, GetMappingRow::from_row)
}
pub fn get_mapping_opt(client: &impl RusqliteClient) -> rusqlite::Result<Option<GetMappingRow>> {
    use rusqlite::OptionalExtension as _;
    let params = rusqlite::params![];
    let mut statement = client.connection().prepare_cached(GET_MAPPING)?;
    statement
        .query_row(params, GetMappingRow::from_row)
        .optional()
}
pub const INSERT_MAPPING: &str = r"INSERT INTO mapping (
    aff_integer_val,
    aff_real_val,
    aff_text_val,
    aff_blob_val,
    int_val,
    integer_val,
    tinyint_val,
    smallint_val,
    mediumint_val,
    bigint_val,
    unsigned_big_int_val,
    int2_val,
    int8_val,
    character20_val,
    varchar255_val,
    varying_char255_val,
    nchar55_val,
    native_char70_val,
    nvarchar100_val,
    text_val,
    clob_val,
    real_val,
    double_val,
    double_precision_val,
    float_val,
    numeric_val,
    decimal10_5_val,
    boolean_val,
    date_val,
    time_val,
    datetime_val
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)";
#[derive(Debug, Clone)]
pub struct InsertMappingParams<'a> {
    pub aff_integer_val: i64,
    pub aff_real_val: f64,
    pub aff_text_val: &'a str,
    pub aff_blob_val: &'a [u8],
    pub int_val: i64,
    pub integer_val: i64,
    pub tinyint_val: i8,
    pub smallint_val: i16,
    pub mediumint_val: i32,
    pub bigint_val: i64,
    pub unsigned_big_int_val: i64,
    pub int_2_val: i16,
    pub int_8_val: i64,
    pub character_20_val: &'a str,
    pub varchar_255_val: &'a str,
    pub varying_char_255_val: &'a str,
    pub nchar_55_val: &'a str,
    pub native_char_70_val: &'a str,
    pub nvarchar_100_val: &'a str,
    pub text_val: &'a str,
    pub clob_val: &'a str,
    pub real_val: f64,
    pub double_val: f64,
    pub double_precision_val: f64,
    pub float_val: f64,
    pub numeric_val: f64,
    pub decimal_10_5_val: f64,
    pub boolean_val: bool,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub datetime_val: chrono::NaiveDateTime,
}
pub fn insert_mapping(
    client: &impl RusqliteClient,
    params: InsertMappingParams<'_>,
) -> rusqlite::Result<()> {
    let params = rusqlite::params![
        params.aff_integer_val,
        params.aff_real_val,
        params.aff_text_val,
        params.aff_blob_val,
        params.int_val,
        params.integer_val,
        params.tinyint_val,
        params.smallint_val,
        params.mediumint_val,
        params.bigint_val,
        params.unsigned_big_int_val,
        params.int_2_val,
        params.int_8_val,
        params.character_20_val,
        params.varchar_255_val,
        params.varying_char_255_val,
        params.nchar_55_val,
        params.native_char_70_val,
        params.nvarchar_100_val,
        params.text_val,
        params.clob_val,
        params.real_val,
        params.double_val,
        params.double_precision_val,
        params.float_val,
        params.numeric_val,
        params.decimal_10_5_val,
        params.boolean_val,
        params.date_val,
        params.time_val,
        params.datetime_val
    ];
    let mut statement = client.connection().prepare_cached(INSERT_MAPPING)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(())
}
pub const GET_MAPPING_BY_CLIENT_AND_STATEMENT: &str = r"SELECT id_val FROM mapping
WHERE aff_text_val = ?1 AND text_val = ?2";
pub struct GetMappingByClientAndStatementRow {
    pub id_val: i64,
}
impl GetMappingByClientAndStatementRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id_val: row.get(0)?,
        })
    }
}
pub fn get_mapping_by_client_and_statement(
    client_: &impl RusqliteClient,
    client: &str,
    statement: &str,
) -> rusqlite::Result<Vec<GetMappingByClientAndStatementRow>> {
    let params = rusqlite::params![client, statement];
    let mut statement_ = client_
        .connection()
        .prepare_cached(GET_MAPPING_BY_CLIENT_AND_STATEMENT)?;
    statement_
        .query_map(params, GetMappingByClientAndStatementRow::from_row)?
        .collect()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetMapping", GET_MAPPING),
    ("InsertMapping", INSERT_MAPPING),
    (
        "GetMappingByClientAndStatement",
        GET_MAPPING_BY_CLIENT_AND_STATEMENT,
    ),
];
