//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

pub const GET_AUTHOR: &str = r"SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1";
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for GetAuthorRow {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
            bio: sqlx::Row::try_get(row, 2)?,
        })
    }
}
pub async fn get_author<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    id: i64,
) -> Result<GetAuthorRow, sqlx::Error> {
    let q = sqlx::query_as::<_, GetAuthorRow>(GET_AUTHOR);
    let q = q.bind(id);
    q.fetch_one(executor).await
}
pub async fn get_author_opt<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    id: i64,
) -> Result<Option<GetAuthorRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, GetAuthorRow>(GET_AUTHOR);
    let q = q.bind(id);
    q.fetch_optional(executor).await
}
pub const LIST_AUTHORS: &str = r"SELECT id, name, bio FROM authors
ORDER BY name";
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for ListAuthorsRow {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
            bio: sqlx::Row::try_get(row, 2)?,
        })
    }
}
pub async fn list_authors<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
) -> Result<Vec<ListAuthorsRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, ListAuthorsRow>(LIST_AUTHORS);
    q.fetch_all(executor).await
}
pub const COUNT_AUTHORS: &str = r"SELECT COUNT(*) FROM authors";
pub struct CountAuthorsRow {
    pub count: i64,
}
impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for CountAuthorsRow {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            count: sqlx::Row::try_get(row, 0)?,
        })
    }
}
pub async fn count_authors<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
) -> Result<CountAuthorsRow, sqlx::Error> {
    let q = sqlx::query_as::<_, CountAuthorsRow>(COUNT_AUTHORS);
    q.fetch_one(executor).await
}
pub async fn count_authors_opt<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
) -> Result<Option<CountAuthorsRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, CountAuthorsRow>(COUNT_AUTHORS);
    q.fetch_optional(executor).await
}
pub const CREATE_AUTHOR: &str = r"INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub async fn create_author<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    params: CreateAuthorParams<'_>,
) -> Result<<sqlx::Sqlite as sqlx::Database>::QueryResult, sqlx::Error> {
    let q = sqlx::query(CREATE_AUTHOR);
    let q = q.bind(params.name);
    let q = q.bind(params.bio);
    q.execute(executor).await
}
pub const DELETE_AUTHOR: &str = r"DELETE FROM authors
WHERE id = ?";
pub async fn delete_author<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    id: i64,
) -> Result<(), sqlx::Error> {
    let q = sqlx::query(DELETE_AUTHOR);
    let q = q.bind(id);
    q.execute(executor).await.map(|_| ())
}
pub const AUTHORS_BY_EXECUTOR: &str =
    r"SELECT id, name, bio FROM authors WHERE name = ?1 ORDER BY id";
pub struct AuthorsByExecutorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for AuthorsByExecutorRow {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
            bio: sqlx::Row::try_get(row, 2)?,
        })
    }
}
pub async fn authors_by_executor<'e>(
    executor_: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    executor: &str,
) -> Result<Vec<AuthorsByExecutorRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, AuthorsByExecutorRow>(AUTHORS_BY_EXECUTOR);
    let q = q.bind(executor);
    q.fetch_all(executor_).await
}
pub const AUTHORS_BY_Q: &str = r"SELECT id, name, bio FROM authors WHERE bio = ?1 ORDER BY id";
pub struct AuthorsByQRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for AuthorsByQRow {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
            bio: sqlx::Row::try_get(row, 2)?,
        })
    }
}
pub async fn authors_by_q<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Sqlite>,
    q: Option<&str>,
) -> Result<Vec<AuthorsByQRow>, sqlx::Error> {
    let q_ = sqlx::query_as::<_, AuthorsByQRow>(AUTHORS_BY_Q);
    let q_ = q_.bind(q);
    q_.fetch_all(executor).await
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetAuthor", GET_AUTHOR),
    ("ListAuthors", LIST_AUTHORS),
    ("CountAuthors", COUNT_AUTHORS),
    ("CreateAuthor", CREATE_AUTHOR),
    ("DeleteAuthor", DELETE_AUTHOR),
    ("AuthorsByExecutor", AUTHORS_BY_EXECUTOR),
    ("AuthorsByQ", AUTHORS_BY_Q),
];
