//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.2.0

pub const LIST_AUTHORS_BY_IDS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
ORDER BY id";
pub struct ListAuthorsByIDsRow {
    pub id: i64,
    pub name: String,
}
impl<'r> sqlx::FromRow<'r, sqlx::postgres::PgRow> for ListAuthorsByIDsRow {
    fn from_row(row: &'r sqlx::postgres::PgRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
        })
    }
}
pub async fn list_authors_by_ids<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
    ids: &[i64],
) -> Result<Vec<ListAuthorsByIDsRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, ListAuthorsByIDsRow>(LIST_AUTHORS_BY_IDS);
    let q = q.bind(ids);
    q.fetch_all(executor).await
}
pub const LIST_AUTHORS_BY_TWO_ID_LISTS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
   OR id = ANY($2::bigint[])
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByTwoIdListsParams<'a> {
    pub ids: &'a [i64],
    pub backup_ids: &'a [i64],
}
pub struct ListAuthorsByTwoIdListsRow {
    pub id: i64,
    pub name: String,
}
impl<'r> sqlx::FromRow<'r, sqlx::postgres::PgRow> for ListAuthorsByTwoIdListsRow {
    fn from_row(row: &'r sqlx::postgres::PgRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
        })
    }
}
pub async fn list_authors_by_two_id_lists<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, ListAuthorsByTwoIdListsRow>(LIST_AUTHORS_BY_TWO_ID_LISTS);
    let q = q.bind(params.ids);
    let q = q.bind(params.backup_ids);
    q.fetch_all(executor).await
}
pub const LIST_AUTHORS_BY_IDS_MIXED: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
  AND id >= $2
  AND NOT (id = ANY($3::bigint[]))
  AND name <> $4
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsMixedParams<'a> {
    pub ids: &'a [i64],
    pub min_id: i64,
    pub skip_ids: &'a [i64],
    pub excluded_name: &'a str,
}
pub struct ListAuthorsByIDsMixedRow {
    pub id: i64,
    pub name: String,
}
impl<'r> sqlx::FromRow<'r, sqlx::postgres::PgRow> for ListAuthorsByIDsMixedRow {
    fn from_row(row: &'r sqlx::postgres::PgRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            id: sqlx::Row::try_get(row, 0)?,
            name: sqlx::Row::try_get(row, 1)?,
        })
    }
}
pub async fn list_authors_by_ids_mixed<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, ListAuthorsByIDsMixedRow>(LIST_AUTHORS_BY_IDS_MIXED);
    let q = q.bind(params.ids);
    let q = q.bind(params.min_id);
    let q = q.bind(params.skip_ids);
    let q = q.bind(params.excluded_name);
    q.fetch_all(executor).await
}
pub const DELETE_AUTHORS_BY_IDS: &str = r"DELETE FROM authors
WHERE id = ANY($1::bigint[])";
pub async fn delete_authors_by_ids<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
    ids: &[i64],
) -> Result<(), sqlx::Error> {
    let q = sqlx::query(DELETE_AUTHORS_BY_IDS);
    let q = q.bind(ids);
    q.execute(executor).await.map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("ListAuthorsByIDs", LIST_AUTHORS_BY_IDS),
    ("ListAuthorsByTwoIDLists", LIST_AUTHORS_BY_TWO_ID_LISTS),
    ("ListAuthorsByIDsMixed", LIST_AUTHORS_BY_IDS_MIXED),
    ("DeleteAuthorsByIDs", DELETE_AUTHORS_BY_IDS),
];
