//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.2.0

pub trait RusqliteClient {
    fn connection(&self) -> &rusqlite::Connection;
}
impl RusqliteClient for rusqlite::Connection {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Savepoint<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
pub mod dynfilter {
    use std::collections::{HashMap, HashSet};
    use std::fmt::Write as _;
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Arg {
        Active,
        Inactive,
        Slice(Option<usize>),
        Flag(bool),
    }
    impl Arg {
        pub fn from_option<T>(value: &Option<T>) -> Self {
            value.as_ref().map_or(Self::Inactive, |_| Self::Active)
        }
        fn active(self) -> bool {
            match self {
                Self::Active => true,
                Self::Inactive => false,
                Self::Slice(length) => length.is_some(),
                Self::Flag(value) => value,
            }
        }
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Bind {
        Arg(usize),
        Elem(usize, usize),
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Placeholders {
        Numbered,
        NumberedSqlite,
        Question,
    }
    /// The engine's lexing rules: comment syntax, quoting, and escapes. Independent of the
    /// placeholder form, which only decides what `?` and `$n` mean.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Dialect {
        Postgres,
        MySql,
        Sqlite,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Connector {
        And,
        Or,
        Comma,
    }
    impl Connector {
        /// The text that leads every item but the first; a comma trails items instead.
        fn line_prefix(self) -> Option<&'static str> {
            match self {
                Self::And => Some("AND "),
                Self::Or => Some("OR "),
                Self::Comma => None,
            }
        }
    }
    /// Line indices into the annotated SQL: the clause header and the first line of each item.
    pub struct Clause<'a> {
        pub header: usize,
        pub connector: Connector,
        pub items: &'a [usize],
    }
    pub struct Compiled {
        segments: Vec<Segment>,
        connectors: Vec<Connector>,
        placeholders: Placeholders,
        /// Every distinct non-empty condition set, in first-segment order; `gate_state` reports
        /// one bit per entry.
        gates: Vec<Vec<usize>>,
        /// One past the highest argument index a placeholder names.
        arg_count: usize,
    }
    /// One enumerated control state of a prepared query: the text and bind plan `Compiled::build`
    /// would produce for every `args` whose `gate_state` is `gates`.
    pub struct State {
        pub gates: u128,
        pub sql: &'static str,
        pub binds: &'static [Bind],
    }
    /// Bare `?` placeholders take the next argument number not yet claimed, in field order.
    struct PlaceholderState<'a> {
        arg_order: &'a [usize],
        seen_arg_nums: HashSet<usize>,
    }
    impl PlaceholderState<'_> {
        /// A bare `?` is a bind only where the engine uses it; PostgreSQL's `?` is a JSON
        /// operator, so the argument order is never consulted for it.
        fn unnumbered(&self, placeholders: Placeholders) -> Option<usize> {
            match placeholders {
                Placeholders::Numbered => None,
                Placeholders::NumberedSqlite | Placeholders::Question => self
                    .arg_order
                    .iter()
                    .copied()
                    .find(|number| !self.seen_arg_nums.contains(number)),
            }
        }
    }
    #[derive(Clone, Copy)]
    enum Role {
        Plain,
        Header(usize),
        Item(usize),
    }
    struct Segment {
        parts: Vec<String>,
        arg_nums: Vec<usize>,
        cond_idxs: Vec<usize>,
        role: Role,
    }
    impl Segment {
        fn active(&self, args: &[Arg]) -> bool {
            active(&self.cond_idxs, args)
        }
    }
    impl Compiled {
        pub fn build(&self, args: &[Arg]) -> (String, Vec<Bind>) {
            let mut query = String::new();
            let mut writer = Writer {
                placeholders: self.placeholders,
                binds: Vec::new(),
                next_placeholder: 1,
                scalar_placeholders: vec![None; self.arg_count],
                slice_placeholders: vec![None; self.arg_count],
            };
            let mut pending_headers: Vec<Option<usize>> = vec![None; self.connectors.len()];
            for (index, segment) in self
                .segments
                .iter()
                .enumerate()
                .filter(|(_, segment)| segment.active(args))
            {
                match segment.role {
                    Role::Plain => writer.write(&mut query, segment, args, None),
                    Role::Header(clause) => pending_headers[clause] = Some(index),
                    Role::Item(clause) => match pending_headers[clause].take() {
                        Some(header) => {
                            writer.write(&mut query, &self.segments[header], args, None);
                            writer.write(&mut query, segment, args, None);
                        }
                        None => {
                            writer.write(&mut query, segment, args, Some(self.connectors[clause]))
                        }
                    },
                }
            }
            (query, writer.binds)
        }
        /// Which gates `args` activate, one bit per distinct condition set. Without slices, the
        /// text and bind plan `build` renders depend on `args` only through this value. `None`
        /// once the query has more than 128 gates.
        pub fn gate_state(&self, args: &[Arg]) -> Option<u128> {
            if self.gates.len() > u128::BITS as usize {
                return None;
            }
            Some(
                self.gates
                    .iter()
                    .enumerate()
                    .filter(|(_, gate)| active(gate, args))
                    .fold(0, |state, (bit, _)| state | (1 << bit)),
            )
        }
        /// Which gates `args` activate, one entry per distinct condition set, for any number of
        /// gates.
        pub fn active_gates(&self, args: &[Arg]) -> Vec<bool> {
            self.gates.iter().map(|gate| active(gate, args)).collect()
        }
        /// The enumerated state for `args`, from a table sorted by `gates`.
        pub fn state<'s>(&self, states: &'s [State], args: &[Arg]) -> Option<&'s State> {
            let gates = self.gate_state(args)?;
            states
                .binary_search_by_key(&gates, |state| state.gates)
                .ok()
                .map(|index| &states[index])
        }
    }
    fn active(conditions: &[usize], args: &[Arg]) -> bool {
        conditions
            .iter()
            .all(|index| args.get(*index).is_some_and(|arg| arg.active()))
    }
    /// Placeholder numbers already assigned, by argument index, so a numbered dialect reuses one
    /// for an argument bound in several places.
    struct Writer {
        placeholders: Placeholders,
        binds: Vec<Bind>,
        next_placeholder: usize,
        scalar_placeholders: Vec<Option<usize>>,
        slice_placeholders: Vec<Option<Vec<usize>>>,
    }
    impl Writer {
        fn write(
            &mut self,
            query: &mut String,
            segment: &Segment,
            args: &[Arg],
            connector: Option<Connector>,
        ) {
            let mut skip = 0;
            match connector.map(Connector::line_prefix) {
                Some(Some(prefix)) => {
                    let part = &segment.parts[0];
                    skip = part.len() - part.trim_start().len();
                    query.push_str(&part[..skip]);
                    query.push_str(prefix);
                }
                Some(None) => query.push(','),
                None => {}
            }
            for (index, part) in segment.parts.iter().enumerate() {
                let part = if index == 0 {
                    &part[skip..]
                } else {
                    part.as_str()
                };
                if let Some(before) = slice_prefix(part).filter(|_| index < segment.arg_nums.len())
                {
                    let arg_index = segment.arg_nums[index] - 1;
                    if let Some(Arg::Slice(Some(length))) = args.get(arg_index) {
                        query.push_str(before);
                        if self.placeholders == Placeholders::Question {
                            self.write_slice(query, arg_index, *length);
                        } else if let Some(numbers) = &self.slice_placeholders[arg_index] {
                            write_placeholders(query, self.placeholders, numbers);
                        } else {
                            let numbers = self.write_slice(query, arg_index, *length);
                            self.slice_placeholders[arg_index] = Some(numbers);
                        }
                        continue;
                    }
                    if args.get(arg_index).is_none() {
                        query.push_str(before);
                        query.push_str("NULL");
                        continue;
                    }
                }
                query.push_str(part);
                let Some(arg_number) = segment.arg_nums.get(index) else {
                    continue;
                };
                let arg_index = arg_number - 1;
                if self.placeholders != Placeholders::Question {
                    if let Some(number) = self.scalar_placeholders[arg_index] {
                        write_placeholder(query, self.placeholders, number);
                    } else {
                        write_placeholder(query, self.placeholders, self.next_placeholder);
                        self.scalar_placeholders[arg_index] = Some(self.next_placeholder);
                        self.next_placeholder += 1;
                        self.binds.push(Bind::Arg(arg_index));
                    }
                } else {
                    write_placeholder(query, self.placeholders, self.next_placeholder);
                    self.next_placeholder += 1;
                    self.binds.push(Bind::Arg(arg_index));
                }
            }
        }
        fn write_slice(
            &mut self,
            query: &mut String,
            arg_index: usize,
            length: usize,
        ) -> Vec<usize> {
            if length == 0 {
                query.push_str("NULL");
                return Vec::new();
            }
            let mut numbers = Vec::new();
            for element_index in 0..length {
                if element_index > 0 {
                    query.push(',');
                }
                let number = self.next_placeholder;
                write_placeholder(query, self.placeholders, number);
                self.next_placeholder += 1;
                if self.placeholders != Placeholders::Question {
                    numbers.push(number);
                }
                self.binds.push(Bind::Elem(arg_index, element_index));
            }
            numbers
        }
    }
    pub fn compile_with_arg_order(
        annotated_sql: &str,
        placeholders: Placeholders,
        dialect: Dialect,
        arg_order: &[usize],
        plan: &[Clause<'_>],
    ) -> Compiled {
        let config = LexerConfig::new(placeholders, dialect);
        let roles = line_roles(plan);
        let strips = connector_lines(plan);
        let mut segments = Vec::new();
        let mut static_sql = String::new();
        let mut placeholder_state = PlaceholderState {
            arg_order,
            seen_arg_nums: HashSet::new(),
        };
        let mut state = LexState::default();
        for (index, line) in annotated_sql.split('\n').enumerate() {
            let separator = if index == 0 { "" } else { "\n" };
            if state.open() {
                state = line_end_state(line, state, config);
                static_sql.push_str(separator);
                static_sql.push_str(line);
                continue;
            }
            let (conditions, cleaned) = extract_conditions(line, config);
            let role = roles.get(&index).copied();
            let strip = strips.get(&index).copied();
            if conditions.is_empty() && role.is_none() && strip.is_none() {
                state = line_end_state(line, state, config);
                static_sql.push_str(separator);
                static_sql.push_str(line);
                continue;
            }
            flush_static(
                &mut segments,
                &mut static_sql,
                &mut placeholder_state,
                config,
            );
            state = line_end_state(&cleaned, state, config);
            let cleaned = match strip {
                Some(connector) => strip_connector(&cleaned, connector),
                None => cleaned,
            };
            let (parts, arg_nums) = split_placeholders(
                &format!("{separator}{cleaned}"),
                &mut placeholder_state,
                config,
            );
            segments.push(Segment {
                parts,
                arg_nums,
                cond_idxs: conditions,
                role: role.unwrap_or(Role::Plain),
            });
        }
        flush_static(
            &mut segments,
            &mut static_sql,
            &mut placeholder_state,
            config,
        );
        let mut gates = Vec::<Vec<usize>>::new();
        for segment in &segments {
            if !segment.cond_idxs.is_empty() && !gates.contains(&segment.cond_idxs) {
                gates.push(segment.cond_idxs.clone());
            }
        }
        let arg_count = segments
            .iter()
            .flat_map(|segment| segment.arg_nums.iter().copied())
            .max()
            .unwrap_or(0);
        Compiled {
            segments,
            connectors: plan.iter().map(|clause| clause.connector).collect(),
            placeholders,
            gates,
            arg_count,
        }
    }
    fn line_roles(plan: &[Clause<'_>]) -> HashMap<usize, Role> {
        plan.iter()
            .enumerate()
            .flat_map(|(index, clause)| {
                std::iter::once((clause.header, Role::Header(index))).chain(
                    clause
                        .items
                        .iter()
                        .map(move |line| (*line, Role::Item(index))),
                )
            })
            .collect()
    }
    /// Lines whose connector text is removed at compile time and re-added by `build` only when an
    /// earlier item of the clause survives: `AND` leads every item but the first, and `,` trails
    /// every item but the last.
    fn connector_lines(plan: &[Clause<'_>]) -> HashMap<usize, Connector> {
        plan.iter()
            .flat_map(|clause| {
                let lines = match clause.connector {
                    Connector::And | Connector::Or => {
                        clause.items.iter().skip(1).copied().collect::<Vec<_>>()
                    }
                    Connector::Comma => clause.items.windows(2).map(|pair| pair[1] - 1).collect(),
                };
                lines.into_iter().map(move |line| (line, clause.connector))
            })
            .collect()
    }
    fn strip_connector(text: &str, connector: Connector) -> String {
        match connector.line_prefix() {
            Some(prefix) => {
                let indentation = text.len() - text.trim_start().len();
                let rest = &text[indentation..];
                format!(
                    "{}{}",
                    &text[..indentation],
                    rest.strip_prefix(prefix).unwrap_or(rest)
                )
            }
            None => {
                let trimmed = text.trim_end();
                trimmed.strip_suffix(',').unwrap_or(trimmed).to_string()
            }
        }
    }
    pub fn nilable<T>(slice: &[T]) -> Option<&[T]> {
        (!slice.is_empty()).then_some(slice)
    }
    fn flush_static(
        segments: &mut Vec<Segment>,
        static_sql: &mut String,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) {
        if static_sql.is_empty() {
            return;
        }
        let (parts, arg_nums) = split_placeholders(static_sql, placeholder_state, config);
        segments.push(Segment {
            parts,
            arg_nums,
            cond_idxs: Vec::new(),
            role: Role::Plain,
        });
        static_sql.clear();
    }
    fn write_placeholders(query: &mut String, placeholders: Placeholders, numbers: &[usize]) {
        if numbers.is_empty() {
            query.push_str("NULL");
            return;
        }
        for (index, number) in numbers.iter().enumerate() {
            if index > 0 {
                query.push(',');
            }
            write_placeholder(query, placeholders, *number);
        }
    }
    fn write_placeholder(query: &mut String, placeholders: Placeholders, number: usize) {
        match placeholders {
            Placeholders::Numbered | Placeholders::NumberedSqlite => {
                let _ = write!(query, "${number}");
            }
            Placeholders::Question => query.push('?'),
        }
    }
    fn slice_prefix(part: &str) -> Option<&str> {
        let start = part.rfind("/*SLICE:")?;
        part.ends_with("*/").then_some(&part[..start])
    }
    fn extract_conditions(line: &str, config: LexerConfig) -> (Vec<usize>, String) {
        let Some(start) = annotation_start(line, config) else {
            return (Vec::new(), line.to_string());
        };
        let mut conditions = Vec::new();
        let mut rest = &line[start..];
        while let Some(position) = rest.find(" -- :if $") {
            let after_marker = &rest[position + 9..];
            let digits = after_marker.bytes().take_while(u8::is_ascii_digit).count();
            if let Ok(number) = after_marker[..digits].parse::<usize>()
                && number > 0
            {
                conditions.push(number - 1);
            }
            rest = &rest[position + 1..];
        }
        (conditions, line[..start].trim_end().to_string())
    }
    /// The plugin strips ordinary line comments before appending gate markers, so the first line
    /// comment that is not a marker ends the search: prose mentioning a marker never gates a line.
    fn annotation_start(line: &str, config: LexerConfig) -> Option<usize> {
        let bytes = line.as_bytes();
        let mut index = 0;
        while index < bytes.len() {
            if bytes[index..].starts_with(b" -- :if $") {
                return Some(index);
            }
            if starts_line_comment(line, index, config) {
                return None;
            }
            let next = skip_quoted_or_block(line, index, config);
            index = if next > index { next } else { index + 1 };
        }
        None
    }
    fn split_placeholders(
        text: &str,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) -> (Vec<String>, Vec<usize>) {
        let bytes = text.as_bytes();
        let mut parts = Vec::new();
        let mut arg_nums = Vec::new();
        let mut part_start = 0;
        let mut index = 0;
        while index < bytes.len() {
            let next = skip_token(text, index, config);
            if next > index {
                index = next;
                continue;
            }
            if bytes[index] != b'$' && bytes[index] != b'?' {
                index += 1;
                continue;
            }
            let mut end = index + 1;
            while bytes.get(end).is_some_and(u8::is_ascii_digit) {
                end += 1;
            }
            let number = match (bytes[index], end > index + 1, config.placeholders) {
                (b'$', true, _) => parse_number(&text[index + 1..end]),
                (b'?', true, Placeholders::NumberedSqlite | Placeholders::Question) => {
                    parse_number(&text[index + 1..end])
                }
                (b'?', false, _) => placeholder_state.unnumbered(config.placeholders),
                _ => None,
            };
            let Some(number) = number.filter(|number| *number > 0) else {
                index = end;
                continue;
            };
            placeholder_state.seen_arg_nums.insert(number);
            parts.push(text[part_start..index].to_string());
            arg_nums.push(number);
            part_start = end;
            index = end;
        }
        parts.push(text[part_start..].to_string());
        (parts, arg_nums)
    }
    fn parse_number(text: &str) -> Option<usize> {
        text.parse().ok()
    }
    fn skip_token(text: &str, index: usize, config: LexerConfig) -> usize {
        if starts_line_comment(text, index, config) {
            return text[index..]
                .find('\n')
                .map_or(text.len(), |end| index + end);
        }
        skip_quoted_or_block(text, index, config)
    }
    /// MySQL also comments with `#`, and its `--` needs a following whitespace or control byte.
    fn starts_line_comment(text: &str, index: usize, config: LexerConfig) -> bool {
        let bytes = &text.as_bytes()[index..];
        if config.mysql && bytes.first() == Some(&b'#') {
            return true;
        }
        bytes.starts_with(b"--")
            && (!config.mysql
                || bytes
                    .get(2)
                    .is_none_or(|byte| byte.is_ascii_whitespace() || byte.is_ascii_control()))
    }
    /// Unquoted identifiers are consumed whole: PostgreSQL and MySQL allow `$` inside them, so
    /// `price$9` names a column rather than referencing a parameter.
    fn skip_identifier(text: &str, index: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        if !is_identifier_start(bytes[index]) {
            return index;
        }
        let mut end = index + 1;
        while bytes.get(end).is_some_and(|byte| {
            is_identifier_start(*byte) || byte.is_ascii_digit() || (*byte == b'$' && !config.sqlite)
        }) {
            end += 1;
        }
        end
    }
    fn is_identifier_start(byte: u8) -> bool {
        byte == b'_' || byte.is_ascii_alphabetic() || !byte.is_ascii()
    }
    fn skip_quoted_or_block(text: &str, index: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        match bytes[index] {
            b'\'' | b'"' | b'`' => {
                let quote = bytes[index];
                let backslash = quote != b'`'
                    && (config.mysql
                        || (config.postgres
                            && quote == b'\''
                            && escape_string_prefix(text, index)));
                quote_end(bytes, index + 1, quote, backslash).0
            }
            b'[' if config.sqlite => text[index + 1..]
                .find(']')
                .map_or(text.len(), |end| index + end + 2),
            b'$' if config.postgres => dollar_delimiter(text, index).map_or(index, |delimiter| {
                text[index + delimiter.len()..]
                    .find(&delimiter)
                    .map_or(text.len(), |end| {
                        index + delimiter.len() + end + delimiter.len()
                    })
            }),
            b'/' if bytes[index..].starts_with(b"/*") => skip_block_comment(text, index, config),
            _ => skip_identifier(text, index, config),
        }
    }
    fn skip_block_comment(text: &str, start: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        let mut depth = 0;
        let mut index = start;
        while index + 1 < bytes.len() {
            if bytes[index..].starts_with(b"/*") && (config.postgres || depth == 0) {
                depth += 1;
                index += 2;
            } else if bytes[index..].starts_with(b"*/") {
                depth -= 1;
                index += 2;
                if depth == 0 {
                    return index;
                }
            } else {
                index += 1;
            }
        }
        text.len()
    }
    #[derive(Clone, Copy)]
    struct LexerConfig {
        placeholders: Placeholders,
        postgres: bool,
        mysql: bool,
        sqlite: bool,
    }
    impl LexerConfig {
        fn new(placeholders: Placeholders, dialect: Dialect) -> Self {
            Self {
                placeholders,
                postgres: dialect == Dialect::Postgres,
                mysql: dialect == Dialect::MySql,
                sqlite: dialect == Dialect::Sqlite,
            }
        }
    }
    #[derive(Default)]
    struct LexState {
        quote: Option<u8>,
        backslash: bool,
        comment_depth: usize,
        dollar: Option<String>,
    }
    impl LexState {
        fn open(&self) -> bool {
            self.quote.is_some() || self.comment_depth > 0 || self.dollar.is_some()
        }
    }
    fn line_end_state(line: &str, mut state: LexState, config: LexerConfig) -> LexState {
        let bytes = line.as_bytes();
        let mut index = 0;
        while index < bytes.len() {
            if let Some(delimiter) = &state.dollar {
                let Some(end) = line[index..].find(delimiter) else {
                    return state;
                };
                index += end + delimiter.len();
                state.dollar = None;
                continue;
            }
            if state.comment_depth > 0 {
                while index < bytes.len() && state.comment_depth > 0 {
                    if config.postgres && bytes[index..].starts_with(b"/*") {
                        state.comment_depth += 1;
                        index += 2;
                    } else if bytes[index..].starts_with(b"*/") {
                        state.comment_depth -= 1;
                        index += 2;
                    } else {
                        index += 1;
                    }
                }
                continue;
            }
            if let Some(quote) = state.quote {
                if quote == b'[' {
                    let Some(end) = line[index..].find(']') else {
                        return state;
                    };
                    index += end + 1;
                    state.quote = None;
                    continue;
                }
                let (end, closed) = quote_end(bytes, index, quote, state.backslash);
                if !closed {
                    return state;
                }
                index = end;
                state.quote = None;
                continue;
            }
            if starts_line_comment(line, index, config) {
                return state;
            }
            if bytes[index..].starts_with(b"/*") {
                state.comment_depth = 1;
                index += 2;
                continue;
            }
            match bytes[index] {
                b'\'' | b'"' | b'`' => {
                    let quote = bytes[index];
                    state.quote = Some(quote);
                    state.backslash = quote != b'`'
                        && (config.mysql
                            || (config.postgres
                                && quote == b'\''
                                && escape_string_prefix(line, index)));
                    index += 1;
                }
                b'[' if config.sqlite => {
                    state.quote = Some(b'[');
                    index += 1;
                }
                b'$' if config.postgres => {
                    if let Some(delimiter) = dollar_delimiter(line, index) {
                        index += delimiter.len();
                        state.dollar = Some(delimiter);
                    } else {
                        index += 1;
                    }
                }
                _ => index = skip_identifier(line, index, config).max(index + 1),
            }
        }
        state
    }
    fn quote_end(bytes: &[u8], mut index: usize, quote: u8, backslash: bool) -> (usize, bool) {
        while index < bytes.len() {
            if backslash && bytes[index] == b'\\' {
                index += 2;
                continue;
            }
            if bytes[index] != quote {
                index += 1;
                continue;
            }
            if bytes.get(index + 1) == Some(&quote) {
                index += 2;
                continue;
            }
            return (index + 1, true);
        }
        (bytes.len(), false)
    }
    fn escape_string_prefix(text: &str, quote_index: usize) -> bool {
        if quote_index == 0 || !matches!(text.as_bytes()[quote_index - 1], b'e' | b'E') {
            return false;
        }
        if quote_index == 1 {
            return true;
        }
        let previous = text.as_bytes()[quote_index - 2];
        !(previous == b'_' || previous == b'$' || previous.is_ascii_alphanumeric())
    }
    fn dollar_delimiter(text: &str, start: usize) -> Option<String> {
        let bytes = text.as_bytes();
        let mut index = start + 1;
        while let Some(byte) = bytes.get(index) {
            if *byte == b'$' {
                return Some(text[start..=index].to_string());
            }
            let is_identifier = *byte == b'_'
                || byte.is_ascii_alphabetic()
                || (index > start + 1 && byte.is_ascii_digit());
            if !is_identifier {
                return None;
            }
            index += 1;
        }
        None
    }
}
pub const LIST_AUTHORS_BY_IDS: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?1)
ORDER BY id";
static LIST_AUTHORS_BY_IDS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_AUTHORS_BY_IDS,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[1usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsParams<'a> {
    pub ids: &'a [i64],
}
pub struct ListAuthorsByIDsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub fn list_authors_by_ids(
    client: &impl RusqliteClient,
    params: ListAuthorsByIDsParams<'_>,
) -> rusqlite::Result<Vec<ListAuthorsByIDsRow>> {
    let args = [dynfilter::Arg::Slice(Some(params.ids.len()))];
    let (sql, binds) = LIST_AUTHORS_BY_IDS_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Elem(0usize, element) => &params.ids[element],
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    statement
        .query_map(params, ListAuthorsByIDsRow::from_row)?
        .collect()
}
pub const LIST_AUTHORS_BY_TWO_ID_LISTS: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?1)
   OR id IN (/*SLICE:backup_ids*/?2)
ORDER BY id";
static LIST_AUTHORS_BY_TWO_ID_LISTS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_AUTHORS_BY_TWO_ID_LISTS,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[1usize, 2usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByTwoIdListsParams<'a> {
    pub ids: &'a [i64],
    pub backup_ids: &'a [i64],
}
pub struct ListAuthorsByTwoIdListsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByTwoIdListsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub fn list_authors_by_two_id_lists(
    client: &impl RusqliteClient,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> rusqlite::Result<Vec<ListAuthorsByTwoIdListsRow>> {
    let args = [
        dynfilter::Arg::Slice(Some(params.ids.len())),
        dynfilter::Arg::Slice(Some(params.backup_ids.len())),
    ];
    let (sql, binds) = LIST_AUTHORS_BY_TWO_ID_LISTS_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Elem(0usize, element) => &params.ids[element],
            dynfilter::Bind::Elem(1usize, element) => &params.backup_ids[element],
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    statement
        .query_map(params, ListAuthorsByTwoIdListsRow::from_row)?
        .collect()
}
pub const LIST_AUTHORS_BY_IDS_MIXED: &str = r"SELECT id, name
FROM authors
WHERE id IN (/*SLICE:ids*/?3)
  AND id >= ?
  AND id NOT IN (/*SLICE:skip_ids*/?4)
  AND name <> ?
ORDER BY id";
static LIST_AUTHORS_BY_IDS_MIXED_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_AUTHORS_BY_IDS_MIXED,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[3usize, 1usize, 4usize, 2usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsMixedParams<'a> {
    pub ids: &'a [i64],
    pub id: i64,
    pub skip_ids: &'a [i64],
    pub name: &'a str,
}
pub struct ListAuthorsByIDsMixedRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsMixedRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub fn list_authors_by_ids_mixed(
    client: &impl RusqliteClient,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> rusqlite::Result<Vec<ListAuthorsByIDsMixedRow>> {
    let args = [
        dynfilter::Arg::Active,
        dynfilter::Arg::Active,
        dynfilter::Arg::Slice(Some(params.ids.len())),
        dynfilter::Arg::Slice(Some(params.skip_ids.len())),
    ];
    let (sql, binds) = LIST_AUTHORS_BY_IDS_MIXED_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Elem(2usize, element) => &params.ids[element],
            dynfilter::Bind::Arg(0usize) => &params.id,
            dynfilter::Bind::Elem(3usize, element) => &params.skip_ids[element],
            dynfilter::Bind::Arg(1usize) => &params.name,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    statement
        .query_map(params, ListAuthorsByIDsMixedRow::from_row)?
        .collect()
}
pub const LIST_AUTHORS_BY_NAMED_IDS: &str = r"SELECT id, name
FROM authors
WHERE id >= ?1
  AND id IN (/*SLICE:ids*/?2)
  AND id <= ?3
ORDER BY id";
static LIST_AUTHORS_BY_NAMED_IDS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_AUTHORS_BY_NAMED_IDS,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[1usize, 2usize, 3usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByNamedIDsParams<'a> {
    pub min_id: i64,
    pub ids: &'a [i64],
    pub max_id: i64,
}
pub struct ListAuthorsByNamedIDsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByNamedIDsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
        })
    }
}
pub fn list_authors_by_named_ids(
    client: &impl RusqliteClient,
    params: ListAuthorsByNamedIDsParams<'_>,
) -> rusqlite::Result<Vec<ListAuthorsByNamedIDsRow>> {
    let args = [
        dynfilter::Arg::Active,
        dynfilter::Arg::Slice(Some(params.ids.len())),
        dynfilter::Arg::Active,
    ];
    let (sql, binds) = LIST_AUTHORS_BY_NAMED_IDS_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Arg(0usize) => &params.min_id,
            dynfilter::Bind::Elem(1usize, element) => &params.ids[element],
            dynfilter::Bind::Arg(2usize) => &params.max_id,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    statement
        .query_map(params, ListAuthorsByNamedIDsRow::from_row)?
        .collect()
}
pub const DELETE_AUTHORS_BY_IDS: &str = r"DELETE FROM authors
WHERE id IN (/*SLICE:ids*/?1)";
static DELETE_AUTHORS_BY_IDS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            DELETE_AUTHORS_BY_IDS,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[1usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct DeleteAuthorsByIDsParams<'a> {
    pub ids: &'a [i64],
}
pub fn delete_authors_by_ids(
    client: &impl RusqliteClient,
    params: DeleteAuthorsByIDsParams<'_>,
) -> rusqlite::Result<()> {
    let args = [dynfilter::Arg::Slice(Some(params.ids.len()))];
    let (sql, binds) = DELETE_AUTHORS_BY_IDS_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Elem(0usize, element) => &params.ids[element],
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(())
}
pub const LIST_AUTHOR_LABELS_BY_IDS: &str = r"SELECT id, '/*SLICE:ids*/?' AS label
FROM authors
WHERE id IN (/*SLICE:ids*/?1)
ORDER BY id";
static LIST_AUTHOR_LABELS_BY_IDS_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            LIST_AUTHOR_LABELS_BY_IDS,
            dynfilter::Placeholders::NumberedSqlite,
            dynfilter::Dialect::Sqlite,
            &[1usize],
            &[],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct ListAuthorLabelsByIDsParams<'a> {
    pub ids: &'a [i64],
}
pub struct ListAuthorLabelsByIDsRow {
    pub id: i64,
    pub label: String,
}
impl ListAuthorLabelsByIDsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            label: row.get(1)?,
        })
    }
}
pub fn list_author_labels_by_ids(
    client: &impl RusqliteClient,
    params: ListAuthorLabelsByIDsParams<'_>,
) -> rusqlite::Result<Vec<ListAuthorLabelsByIDsRow>> {
    let args = [dynfilter::Arg::Slice(Some(params.ids.len()))];
    let (sql, binds) = LIST_AUTHOR_LABELS_BY_IDS_DYN.build(&args);
    let values = binds.iter().copied().map(|bind| -> &dyn rusqlite::ToSql {
        match bind {
            dynfilter::Bind::Elem(0usize, element) => &params.ids[element],
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        }
    });
    let mut statement = client.connection().prepare(&sql)?;
    let params = rusqlite::params_from_iter(values);
    statement
        .query_map(params, ListAuthorLabelsByIDsRow::from_row)?
        .collect()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("ListAuthorsByIDs", LIST_AUTHORS_BY_IDS),
    ("ListAuthorsByTwoIDLists", LIST_AUTHORS_BY_TWO_ID_LISTS),
    ("ListAuthorsByIDsMixed", LIST_AUTHORS_BY_IDS_MIXED),
    ("ListAuthorsByNamedIDs", LIST_AUTHORS_BY_NAMED_IDS),
    ("DeleteAuthorsByIDs", DELETE_AUTHORS_BY_IDS),
    ("ListAuthorLabelsByIDs", LIST_AUTHOR_LABELS_BY_IDS),
];
