//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "mood")]
pub enum Mood {
    #[postgres(name = "sad")]
    Sad,
    #[postgres(name = "ok")]
    Ok,
    #[postgres(name = "happy")]
    Happy,
}
#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "s")]
pub enum S {
    #[postgres(name = "a")]
    A,
    #[postgres(name = "b")]
    B,
}
pub const GET_MAPPING: &str = r"SELECT
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val
FROM mapping";
pub struct GetMappingRow {
    pub bool_val: bool,
    pub bool_array_val: Vec<bool>,
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: u32,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: String,
    pub text_nullable_val: Option<String>,
    pub bytea_val: Vec<u8>,
    pub hstore_val: std::collections::HashMap<String, Option<String>>,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
}
impl GetMappingRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            bool_val: row.try_get(0)?,
            bool_array_val: row.try_get(1)?,
            char_val: row.try_get(2)?,
            smallint_val: row.try_get(3)?,
            int_val: row.try_get(4)?,
            int_nullable_val: row.try_get(5)?,
            oid_val: row.try_get(6)?,
            bigint_val: row.try_get(7)?,
            real_val: row.try_get(8)?,
            double_val: row.try_get(9)?,
            text_val: row.try_get(10)?,
            text_nullable_val: row.try_get(11)?,
            bytea_val: row.try_get(12)?,
            hstore_val: row.try_get(13)?,
            timestamp_val: row.try_get(14)?,
            timestamptz_val: row.try_get(15)?,
            date_val: row.try_get(16)?,
            time_val: row.try_get(17)?,
            inet_val: row.try_get(18)?,
            json_val: row.try_get(19)?,
            jsonb_val: row.try_get(20)?,
            uuid_val: row.try_get(21)?,
            enum_val: row.try_get(22)?,
            composite_val: row.try_get(23)?,
        })
    }
}
pub async fn prepare_get_mapping(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_MAPPING).await
}
pub async fn get_mapping(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<GetMappingRow, deadpool_postgres::tokio_postgres::Error> {
    self::get_mapping_with(client, GET_MAPPING).await
}
pub async fn get_mapping_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
) -> Result<GetMappingRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[];
    let row = client.query_one(statement, values).await?;
    GetMappingRow::from_row(&row)
}
pub async fn get_mapping_opt(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<Option<GetMappingRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_mapping_opt_with(client, GET_MAPPING).await
}
pub async fn get_mapping_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
) -> Result<Option<GetMappingRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| GetMappingRow::from_row(&row))
        .transpose()
}
pub const INSERT_MAPPING: &str = r"INSERT INTO mapping (
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)";
#[derive(Debug, Clone)]
pub struct InsertMappingParams<'a> {
    pub bool_val: bool,
    pub bool_array_val: &'a [bool],
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: u32,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: &'a str,
    pub text_nullable_val: Option<&'a str>,
    pub bytea_val: &'a [u8],
    pub hstore_val: std::collections::HashMap<String, Option<String>>,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
}
pub async fn prepare_insert_mapping(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(INSERT_MAPPING).await
}
pub async fn insert_mapping(
    client: &impl deadpool_postgres::GenericClient,
    params: InsertMappingParams<'_>,
) -> Result<(), deadpool_postgres::tokio_postgres::Error> {
    self::insert_mapping_with(client, INSERT_MAPPING, params).await
}
pub async fn insert_mapping_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    params: InsertMappingParams<'_>,
) -> Result<(), deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[
        &params.bool_val,
        &params.bool_array_val,
        &params.char_val,
        &params.smallint_val,
        &params.int_val,
        &params.int_nullable_val,
        &params.oid_val,
        &params.bigint_val,
        &params.real_val,
        &params.double_val,
        &params.text_val,
        &params.text_nullable_val,
        &params.bytea_val,
        &params.hstore_val,
        &params.timestamp_val,
        &params.timestamptz_val,
        &params.date_val,
        &params.time_val,
        &params.inet_val,
        &params.json_val,
        &params.jsonb_val,
        &params.uuid_val,
        &params.enum_val,
        &params.composite_val,
    ];
    client.execute(statement, values).await.map(|_| ())
}
pub const GET_BY_STATE: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
ORDER BY id";
pub struct GetByStateRow {
    pub id: i64,
    pub state: S,
}
impl GetByStateRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub async fn prepare_get_by_state(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_BY_STATE).await
}
pub async fn get_by_state(
    client: &impl deadpool_postgres::GenericClient,
    state: S,
) -> Result<Vec<GetByStateRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_by_state_with(client, GET_BY_STATE, state).await
}
pub async fn get_by_state_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    state: S,
) -> Result<Vec<GetByStateRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[&state];
    let rows = client.query(statement, values).await?;
    rows.iter().map(GetByStateRow::from_row).collect()
}
pub async fn get_by_state_stream(
    client: &impl deadpool_postgres::GenericClient,
    state: S,
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    self::get_by_state_stream_with(client, GET_BY_STATE, state).await
}
pub async fn get_by_state_stream_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    state: S,
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[&state];
    client.query_raw(statement, values.iter().copied()).await
}
pub const GET_ONE_BY_STATE: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
LIMIT 1";
pub struct GetOneByStateRow {
    pub id: i64,
    pub state: S,
}
impl GetOneByStateRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub async fn prepare_get_one_by_state(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_ONE_BY_STATE).await
}
pub async fn get_one_by_state(
    client: &impl deadpool_postgres::GenericClient,
    state: S,
) -> Result<GetOneByStateRow, deadpool_postgres::tokio_postgres::Error> {
    self::get_one_by_state_with(client, GET_ONE_BY_STATE, state).await
}
pub async fn get_one_by_state_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    state: S,
) -> Result<GetOneByStateRow, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[&state];
    let row = client.query_one(statement, values).await?;
    GetOneByStateRow::from_row(&row)
}
pub async fn get_one_by_state_opt(
    client: &impl deadpool_postgres::GenericClient,
    state: S,
) -> Result<Option<GetOneByStateRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_one_by_state_opt_with(client, GET_ONE_BY_STATE, state).await
}
pub async fn get_one_by_state_opt_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    state: S,
) -> Result<Option<GetOneByStateRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] = &[&state];
    client
        .query_opt(statement, values)
        .await?
        .map(|row| GetOneByStateRow::from_row(&row))
        .transpose()
}
pub const GET_BY_STATE_WITH_MINIMUM_ID: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
  AND id >= $2
ORDER BY id";
#[derive(Debug, Clone)]
pub struct GetByStateWithMinimumIdParams {
    pub state: S,
    pub minimum_id: i64,
}
pub struct GetByStateWithMinimumIdRow {
    pub id: i64,
    pub state: S,
}
impl GetByStateWithMinimumIdRow {
    pub fn from_row(
        row: &deadpool_postgres::tokio_postgres::Row,
    ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub async fn prepare_get_by_state_with_minimum_id(
    client: &impl deadpool_postgres::GenericClient,
) -> Result<deadpool_postgres::tokio_postgres::Statement, deadpool_postgres::tokio_postgres::Error>
{
    client.prepare_cached(GET_BY_STATE_WITH_MINIMUM_ID).await
}
pub async fn get_by_state_with_minimum_id(
    client: &impl deadpool_postgres::GenericClient,
    params: GetByStateWithMinimumIdParams,
) -> Result<Vec<GetByStateWithMinimumIdRow>, deadpool_postgres::tokio_postgres::Error> {
    self::get_by_state_with_minimum_id_with(client, GET_BY_STATE_WITH_MINIMUM_ID, params).await
}
pub async fn get_by_state_with_minimum_id_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    params: GetByStateWithMinimumIdParams,
) -> Result<Vec<GetByStateWithMinimumIdRow>, deadpool_postgres::tokio_postgres::Error> {
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] =
        &[&params.state, &params.minimum_id];
    let rows = client.query(statement, values).await?;
    rows.iter()
        .map(GetByStateWithMinimumIdRow::from_row)
        .collect()
}
pub async fn get_by_state_with_minimum_id_stream(
    client: &impl deadpool_postgres::GenericClient,
    params: GetByStateWithMinimumIdParams,
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    self::get_by_state_with_minimum_id_stream_with(client, GET_BY_STATE_WITH_MINIMUM_ID, params)
        .await
}
pub async fn get_by_state_with_minimum_id_stream_with(
    client: &impl deadpool_postgres::GenericClient,
    statement: &(impl deadpool_postgres::tokio_postgres::ToStatement + ?Sized + Sync + Send),
    params: GetByStateWithMinimumIdParams,
) -> Result<deadpool_postgres::tokio_postgres::RowStream, deadpool_postgres::tokio_postgres::Error>
{
    let values: &[&(dyn deadpool_postgres::tokio_postgres::types::ToSql + Sync)] =
        &[&params.state, &params.minimum_id];
    client.query_raw(statement, values.iter().copied()).await
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetMapping", GET_MAPPING),
    ("InsertMapping", INSERT_MAPPING),
    ("GetByState", GET_BY_STATE),
    ("GetOneByState", GET_ONE_BY_STATE),
    ("GetByStateWithMinimumID", GET_BY_STATE_WITH_MINIMUM_ID),
];
