//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.1

pub const GET_AUTHOR: &str = r"SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1";
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl GetAuthorRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub fn prepare_get_author(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_AUTHOR)
}
pub fn get_author(
    client: &mut impl postgres::GenericClient,
    get_author_with: i64,
) -> Result<GetAuthorRow, postgres::Error> {
    self::get_author_with(client, GET_AUTHOR, get_author_with)
}
pub fn get_author_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    get_author_with: i64,
) -> Result<GetAuthorRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&get_author_with];
    let row = client.query_one(statement, values)?;
    GetAuthorRow::from_row(&row)
}
pub fn get_author_opt(
    client: &mut impl postgres::GenericClient,
    get_author_with: i64,
) -> Result<Option<GetAuthorRow>, postgres::Error> {
    self::get_author_opt_with(client, GET_AUTHOR, get_author_with)
}
pub fn get_author_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    get_author_with: i64,
) -> Result<Option<GetAuthorRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&get_author_with];
    client
        .query_opt(statement, values)?
        .map(|row| GetAuthorRow::from_row(&row))
        .transpose()
}
pub const LIST_AUTHORS: &str = r"SELECT id, name, bio FROM authors
ORDER BY name";
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl ListAuthorsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub fn prepare_list_authors(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_AUTHORS)
}
pub fn list_authors(
    client: &mut impl postgres::GenericClient,
) -> Result<Vec<ListAuthorsRow>, postgres::Error> {
    self::list_authors_with(client, LIST_AUTHORS)
}
pub fn list_authors_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<Vec<ListAuthorsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    let rows = client.query(statement, values)?;
    rows.iter().map(ListAuthorsRow::from_row).collect()
}
pub fn list_authors_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_authors_iter_with(client, LIST_AUTHORS)
}
pub fn list_authors_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    client.query_raw(statement, values.iter().copied())
}
pub const COUNT_AUTHORS: &str = r"SELECT COUNT(*) FROM authors";
pub struct CountAuthorsRow {
    pub count: i64,
}
impl CountAuthorsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            count: row.try_get(0)?,
        })
    }
}
pub fn prepare_count_authors(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(COUNT_AUTHORS)
}
pub fn count_authors(
    client: &mut impl postgres::GenericClient,
) -> Result<CountAuthorsRow, postgres::Error> {
    self::count_authors_with(client, COUNT_AUTHORS)
}
pub fn count_authors_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<CountAuthorsRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    let row = client.query_one(statement, values)?;
    CountAuthorsRow::from_row(&row)
}
pub fn count_authors_opt(
    client: &mut impl postgres::GenericClient,
) -> Result<Option<CountAuthorsRow>, postgres::Error> {
    self::count_authors_opt_with(client, COUNT_AUTHORS)
}
pub fn count_authors_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<Option<CountAuthorsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    client
        .query_opt(statement, values)?
        .map(|row| CountAuthorsRow::from_row(&row))
        .transpose()
}
pub const CREATE_AUTHOR: &str = r"INSERT INTO authors (
          name, bio
) VALUES (
  $1, $2
)
RETURNING id, name, bio";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub struct CreateAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl CreateAuthorRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub fn prepare_create_author(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_AUTHOR)
}
pub fn create_author(
    client: &mut impl postgres::GenericClient,
    params: CreateAuthorParams<'_>,
) -> Result<CreateAuthorRow, postgres::Error> {
    self::create_author_with(client, CREATE_AUTHOR, params)
}
pub fn create_author_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateAuthorParams<'_>,
) -> Result<CreateAuthorRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.name, &params.bio];
    let row = client.query_one(statement, values)?;
    CreateAuthorRow::from_row(&row)
}
pub fn create_author_opt(
    client: &mut impl postgres::GenericClient,
    params: CreateAuthorParams<'_>,
) -> Result<Option<CreateAuthorRow>, postgres::Error> {
    self::create_author_opt_with(client, CREATE_AUTHOR, params)
}
pub fn create_author_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateAuthorParams<'_>,
) -> Result<Option<CreateAuthorRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.name, &params.bio];
    client
        .query_opt(statement, values)?
        .map(|row| CreateAuthorRow::from_row(&row))
        .transpose()
}
pub const DELETE_AUTHOR: &str = r"DELETE FROM authors
WHERE id = $1";
pub fn prepare_delete_author(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(DELETE_AUTHOR)
}
pub fn delete_author(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<(), postgres::Error> {
    self::delete_author_with(client, DELETE_AUTHOR, id)
}
pub fn delete_author_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client.execute(statement, values).map(|_| ())
}
pub const GET_KEYWORD_IDENT: &str = r"SELECT id, type FROM keyword_idents
WHERE type = $1 LIMIT 1";
pub struct GetKeywordIdentRow {
    pub id: i64,
    pub r#type: String,
}
impl GetKeywordIdentRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            r#type: row.try_get(1)?,
        })
    }
}
pub fn prepare_get_keyword_ident(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_KEYWORD_IDENT)
}
pub fn get_keyword_ident(
    client: &mut impl postgres::GenericClient,
    r#type: &str,
) -> Result<GetKeywordIdentRow, postgres::Error> {
    self::get_keyword_ident_with(client, GET_KEYWORD_IDENT, r#type)
}
pub fn get_keyword_ident_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    r#type: &str,
) -> Result<GetKeywordIdentRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&r#type];
    let row = client.query_one(statement, values)?;
    GetKeywordIdentRow::from_row(&row)
}
pub fn get_keyword_ident_opt(
    client: &mut impl postgres::GenericClient,
    r#type: &str,
) -> Result<Option<GetKeywordIdentRow>, postgres::Error> {
    self::get_keyword_ident_opt_with(client, GET_KEYWORD_IDENT, r#type)
}
pub fn get_keyword_ident_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    r#type: &str,
) -> Result<Option<GetKeywordIdentRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&r#type];
    client
        .query_opt(statement, values)?
        .map(|row| GetKeywordIdentRow::from_row(&row))
        .transpose()
}
pub const GET_AUTHORS_BY_NAME: &str = r"SELECT id, name, bio FROM authors
WHERE name = $1";
pub struct GetAuthorsByNameRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl GetAuthorsByNameRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
            bio: row.try_get(2)?,
        })
    }
}
pub fn prepare_get_authors_by_name(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_AUTHORS_BY_NAME)
}
pub fn get_authors_by_name(
    client: &mut impl postgres::GenericClient,
    name: &str,
) -> Result<GetAuthorsByNameRow, postgres::Error> {
    self::get_authors_by_name_with(client, GET_AUTHORS_BY_NAME, name)
}
pub fn get_authors_by_name_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    name: &str,
) -> Result<GetAuthorsByNameRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&name];
    let row = client.query_one(statement, values)?;
    GetAuthorsByNameRow::from_row(&row)
}
pub fn get_authors_by_name_opt(
    client: &mut impl postgres::GenericClient,
    name: &str,
) -> Result<Option<GetAuthorsByNameRow>, postgres::Error> {
    self::get_authors_by_name_opt_with(client, GET_AUTHORS_BY_NAME, name)
}
pub fn get_authors_by_name_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    name: &str,
) -> Result<Option<GetAuthorsByNameRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&name];
    client
        .query_opt(statement, values)?
        .map(|row| GetAuthorsByNameRow::from_row(&row))
        .transpose()
}
pub const CREATE_AUTHOR_WITH_ID: &str = r"INSERT INTO authors (id, name) VALUES ($1, $2)";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorWithIdParams<'a> {
    pub id: i64,
    pub name: &'a str,
}
pub fn prepare_create_author_with_id(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(CREATE_AUTHOR_WITH_ID)
}
pub fn create_author_with_id(
    client: &mut impl postgres::GenericClient,
    params: CreateAuthorWithIdParams<'_>,
) -> Result<u64, postgres::Error> {
    self::create_author_with_id_with(client, CREATE_AUTHOR_WITH_ID, params)
}
pub fn create_author_with_id_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: CreateAuthorWithIdParams<'_>,
) -> Result<u64, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.id, &params.name];
    client.execute(statement, values)
}
pub const TOUCH_AUTHORS: &str = r"UPDATE authors SET bio = bio
WHERE id >= $1";
pub fn prepare_touch_authors(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(TOUCH_AUTHORS)
}
pub fn touch_authors(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<u64, postgres::Error> {
    self::touch_authors_with(client, TOUCH_AUTHORS, id)
}
pub fn touch_authors_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<u64, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client.execute(statement, values)
}
pub const RENAME_AUTHORS_RETURNING_ID: &str = r"UPDATE authors SET name = $1
WHERE id >= $2
RETURNING id";
#[derive(Debug, Clone, Default)]
pub struct RenameAuthorsReturningIdParams<'a> {
    pub name: &'a str,
    pub id: i64,
}
pub fn prepare_rename_authors_returning_id(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(RENAME_AUTHORS_RETURNING_ID)
}
pub fn rename_authors_returning_id(
    client: &mut impl postgres::GenericClient,
    params: RenameAuthorsReturningIdParams<'_>,
) -> Result<u64, postgres::Error> {
    self::rename_authors_returning_id_with(client, RENAME_AUTHORS_RETURNING_ID, params)
}
pub fn rename_authors_returning_id_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: RenameAuthorsReturningIdParams<'_>,
) -> Result<u64, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.name, &params.id];
    client.execute(statement, values)
}
pub const DELETE_AUTHOR_RETURNING_ID: &str = r"DELETE FROM authors
WHERE id = $1
RETURNING id";
pub fn prepare_delete_author_returning_id(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(DELETE_AUTHOR_RETURNING_ID)
}
pub fn delete_author_returning_id(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<(), postgres::Error> {
    self::delete_author_returning_id_with(client, DELETE_AUTHOR_RETURNING_ID, id)
}
pub fn delete_author_returning_id_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client.execute(statement, values).map(|_| ())
}
pub const INSERT_TIMESTAMPS: &str = r"INSERT INTO timestamps (id, timestamp_val, timestamptz_val, nullable_timestamp)
VALUES ($1, $2, $3, $4)";
#[derive(Debug, Clone)]
pub struct InsertTimestampsParams {
    pub id: i64,
    pub timestamp_val: std::time::SystemTime,
    pub timestamptz_val: std::time::SystemTime,
    pub nullable_timestamp: Option<std::time::SystemTime>,
}
pub fn prepare_insert_timestamps(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(INSERT_TIMESTAMPS)
}
pub fn insert_timestamps(
    client: &mut impl postgres::GenericClient,
    params: InsertTimestampsParams,
) -> Result<(), postgres::Error> {
    self::insert_timestamps_with(client, INSERT_TIMESTAMPS, params)
}
pub fn insert_timestamps_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: InsertTimestampsParams,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.id,
        &params.timestamp_val,
        &params.timestamptz_val,
        &params.nullable_timestamp,
    ];
    client.execute(statement, values).map(|_| ())
}
pub const GET_TIMESTAMPS: &str = r"SELECT timestamp_val, timestamptz_val, nullable_timestamp
FROM timestamps
WHERE id = $1";
pub struct GetTimestampsRow {
    pub timestamp_val: std::time::SystemTime,
    pub timestamptz_val: std::time::SystemTime,
    pub nullable_timestamp: Option<std::time::SystemTime>,
}
impl GetTimestampsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            timestamp_val: row.try_get(0)?,
            timestamptz_val: row.try_get(1)?,
            nullable_timestamp: row.try_get(2)?,
        })
    }
}
pub fn prepare_get_timestamps(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_TIMESTAMPS)
}
pub fn get_timestamps(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<GetTimestampsRow, postgres::Error> {
    self::get_timestamps_with(client, GET_TIMESTAMPS, id)
}
pub fn get_timestamps_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<GetTimestampsRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    let row = client.query_one(statement, values)?;
    GetTimestampsRow::from_row(&row)
}
pub fn get_timestamps_opt(
    client: &mut impl postgres::GenericClient,
    id: i64,
) -> Result<Option<GetTimestampsRow>, postgres::Error> {
    self::get_timestamps_opt_with(client, GET_TIMESTAMPS, id)
}
pub fn get_timestamps_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    id: i64,
) -> Result<Option<GetTimestampsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&id];
    client
        .query_opt(statement, values)?
        .map(|row| GetTimestampsRow::from_row(&row))
        .transpose()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetAuthor", GET_AUTHOR),
    ("ListAuthors", LIST_AUTHORS),
    ("CountAuthors", COUNT_AUTHORS),
    ("CreateAuthor", CREATE_AUTHOR),
    ("DeleteAuthor", DELETE_AUTHOR),
    ("GetKeywordIdent", GET_KEYWORD_IDENT),
    ("GetAuthorsByName", GET_AUTHORS_BY_NAME),
    ("CreateAuthorWithID", CREATE_AUTHOR_WITH_ID),
    ("TouchAuthors", TOUCH_AUTHORS),
    ("RenameAuthorsReturningID", RENAME_AUTHORS_RETURNING_ID),
    ("DeleteAuthorReturningID", DELETE_AUTHOR_RETURNING_ID),
    ("InsertTimestamps", INSERT_TIMESTAMPS),
    ("GetTimestamps", GET_TIMESTAMPS),
];
