//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

pub const LIST_AUTHORS_BY_IDS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
ORDER BY id";
pub struct ListAuthorsByIDsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub async fn prepare_list_authors_by_ids(
    client: &impl tokio_postgres::GenericClient,
) -> Result<tokio_postgres::Statement, tokio_postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_IDS).await
}
pub async fn list_authors_by_ids(
    client: &impl tokio_postgres::GenericClient,
    ids: &[i64],
) -> Result<Vec<ListAuthorsByIDsRow>, tokio_postgres::Error> {
    self::list_authors_by_ids_with(client, LIST_AUTHORS_BY_IDS, ids).await
}
pub async fn list_authors_by_ids_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<Vec<ListAuthorsByIDsRow>, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    let rows = client.query(statement, values).await?;
    rows.iter().map(ListAuthorsByIDsRow::from_row).collect()
}
pub async fn list_authors_by_ids_stream(
    client: &impl tokio_postgres::GenericClient,
    ids: &[i64],
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    self::list_authors_by_ids_stream_with(client, LIST_AUTHORS_BY_IDS, ids).await
}
pub async fn list_authors_by_ids_stream_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    client.query_raw(statement, values.iter().copied()).await
}
pub const LIST_AUTHORS_BY_TWO_ID_LISTS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
   OR id = ANY($2::bigint[])
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByTwoIdListsParams<'a> {
    pub ids: &'a [i64],
    pub backup_ids: &'a [i64],
}
pub struct ListAuthorsByTwoIdListsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByTwoIdListsRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub async fn prepare_list_authors_by_two_id_lists(
    client: &impl tokio_postgres::GenericClient,
) -> Result<tokio_postgres::Statement, tokio_postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_TWO_ID_LISTS).await
}
pub async fn list_authors_by_two_id_lists(
    client: &impl tokio_postgres::GenericClient,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, tokio_postgres::Error> {
    self::list_authors_by_two_id_lists_with(client, LIST_AUTHORS_BY_TWO_ID_LISTS, params).await
}
pub async fn list_authors_by_two_id_lists_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.ids, &params.backup_ids];
    let rows = client.query(statement, values).await?;
    rows.iter()
        .map(ListAuthorsByTwoIdListsRow::from_row)
        .collect()
}
pub async fn list_authors_by_two_id_lists_stream(
    client: &impl tokio_postgres::GenericClient,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    self::list_authors_by_two_id_lists_stream_with(client, LIST_AUTHORS_BY_TWO_ID_LISTS, params)
        .await
}
pub async fn list_authors_by_two_id_lists_stream_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.ids, &params.backup_ids];
    client.query_raw(statement, values.iter().copied()).await
}
pub const LIST_AUTHORS_BY_IDS_MIXED: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
  AND id >= $2
  AND NOT (id = ANY($3::bigint[]))
  AND name <> $4
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsMixedParams<'a> {
    pub ids: &'a [i64],
    pub min_id: i64,
    pub skip_ids: &'a [i64],
    pub excluded_name: &'a str,
}
pub struct ListAuthorsByIDsMixedRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsMixedRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub async fn prepare_list_authors_by_ids_mixed(
    client: &impl tokio_postgres::GenericClient,
) -> Result<tokio_postgres::Statement, tokio_postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_IDS_MIXED).await
}
pub async fn list_authors_by_ids_mixed(
    client: &impl tokio_postgres::GenericClient,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, tokio_postgres::Error> {
    self::list_authors_by_ids_mixed_with(client, LIST_AUTHORS_BY_IDS_MIXED, params).await
}
pub async fn list_authors_by_ids_mixed_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.ids,
        &params.min_id,
        &params.skip_ids,
        &params.excluded_name,
    ];
    let rows = client.query(statement, values).await?;
    rows.iter()
        .map(ListAuthorsByIDsMixedRow::from_row)
        .collect()
}
pub async fn list_authors_by_ids_mixed_stream(
    client: &impl tokio_postgres::GenericClient,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    self::list_authors_by_ids_mixed_stream_with(client, LIST_AUTHORS_BY_IDS_MIXED, params).await
}
pub async fn list_authors_by_ids_mixed_stream_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.ids,
        &params.min_id,
        &params.skip_ids,
        &params.excluded_name,
    ];
    client.query_raw(statement, values.iter().copied()).await
}
pub const DELETE_AUTHORS_BY_IDS: &str = r"DELETE FROM authors
WHERE id = ANY($1::bigint[])";
pub async fn prepare_delete_authors_by_ids(
    client: &impl tokio_postgres::GenericClient,
) -> Result<tokio_postgres::Statement, tokio_postgres::Error> {
    client.prepare(DELETE_AUTHORS_BY_IDS).await
}
pub async fn delete_authors_by_ids(
    client: &impl tokio_postgres::GenericClient,
    ids: &[i64],
) -> Result<(), tokio_postgres::Error> {
    self::delete_authors_by_ids_with(client, DELETE_AUTHORS_BY_IDS, ids).await
}
pub async fn delete_authors_by_ids_with(
    client: &impl tokio_postgres::GenericClient,
    statement: &(
         impl tokio_postgres::ToStatement
         + ?::std::marker::Sized
         + ::std::marker::Sync
         + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<(), tokio_postgres::Error> {
    let values: &[&(dyn tokio_postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    client.execute(statement, values).await.map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("ListAuthorsByIDs", LIST_AUTHORS_BY_IDS),
    ("ListAuthorsByTwoIDLists", LIST_AUTHORS_BY_TWO_ID_LISTS),
    ("ListAuthorsByIDsMixed", LIST_AUTHORS_BY_IDS_MIXED),
    ("DeleteAuthorsByIDs", DELETE_AUTHORS_BY_IDS),
];
