//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

pub const LIST_AUTHORS_BY_IDS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
ORDER BY id";
pub struct ListAuthorsByIDsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub fn prepare_list_authors_by_ids(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_IDS)
}
pub fn list_authors_by_ids(
    client: &mut impl postgres::GenericClient,
    ids: &[i64],
) -> Result<Vec<ListAuthorsByIDsRow>, postgres::Error> {
    self::list_authors_by_ids_with(client, LIST_AUTHORS_BY_IDS, ids)
}
pub fn list_authors_by_ids_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<Vec<ListAuthorsByIDsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    let rows = client.query(statement, values)?;
    rows.iter().map(ListAuthorsByIDsRow::from_row).collect()
}
pub fn list_authors_by_ids_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    ids: &[i64],
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_authors_by_ids_iter_with(client, LIST_AUTHORS_BY_IDS, ids)
}
pub fn list_authors_by_ids_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    client.query_raw(statement, values.iter().copied())
}
pub const LIST_AUTHORS_BY_TWO_ID_LISTS: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
   OR id = ANY($2::bigint[])
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByTwoIdListsParams<'a> {
    pub ids: &'a [i64],
    pub backup_ids: &'a [i64],
}
pub struct ListAuthorsByTwoIdListsRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByTwoIdListsRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub fn prepare_list_authors_by_two_id_lists(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_TWO_ID_LISTS)
}
pub fn list_authors_by_two_id_lists(
    client: &mut impl postgres::GenericClient,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, postgres::Error> {
    self::list_authors_by_two_id_lists_with(client, LIST_AUTHORS_BY_TWO_ID_LISTS, params)
}
pub fn list_authors_by_two_id_lists_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<Vec<ListAuthorsByTwoIdListsRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.ids, &params.backup_ids];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(ListAuthorsByTwoIdListsRow::from_row)
        .collect()
}
pub fn list_authors_by_two_id_lists_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_authors_by_two_id_lists_iter_with(client, LIST_AUTHORS_BY_TWO_ID_LISTS, params)
}
pub fn list_authors_by_two_id_lists_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListAuthorsByTwoIdListsParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.ids, &params.backup_ids];
    client.query_raw(statement, values.iter().copied())
}
pub const LIST_AUTHORS_BY_IDS_MIXED: &str = r"SELECT id, name
FROM authors
WHERE id = ANY($1::bigint[])
  AND id >= $2
  AND NOT (id = ANY($3::bigint[]))
  AND name <> $4
ORDER BY id";
#[derive(Debug, Clone, Default)]
pub struct ListAuthorsByIDsMixedParams<'a> {
    pub ids: &'a [i64],
    pub min_id: i64,
    pub skip_ids: &'a [i64],
    pub excluded_name: &'a str,
}
pub struct ListAuthorsByIDsMixedRow {
    pub id: i64,
    pub name: String,
}
impl ListAuthorsByIDsMixedRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            name: row.try_get(1)?,
        })
    }
}
pub fn prepare_list_authors_by_ids_mixed(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(LIST_AUTHORS_BY_IDS_MIXED)
}
pub fn list_authors_by_ids_mixed(
    client: &mut impl postgres::GenericClient,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, postgres::Error> {
    self::list_authors_by_ids_mixed_with(client, LIST_AUTHORS_BY_IDS_MIXED, params)
}
pub fn list_authors_by_ids_mixed_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<Vec<ListAuthorsByIDsMixedRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.ids,
        &params.min_id,
        &params.skip_ids,
        &params.excluded_name,
    ];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(ListAuthorsByIDsMixedRow::from_row)
        .collect()
}
pub fn list_authors_by_ids_mixed_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::list_authors_by_ids_mixed_iter_with(client, LIST_AUTHORS_BY_IDS_MIXED, params)
}
pub fn list_authors_by_ids_mixed_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: ListAuthorsByIDsMixedParams<'_>,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.ids,
        &params.min_id,
        &params.skip_ids,
        &params.excluded_name,
    ];
    client.query_raw(statement, values.iter().copied())
}
pub const DELETE_AUTHORS_BY_IDS: &str = r"DELETE FROM authors
WHERE id = ANY($1::bigint[])";
pub fn prepare_delete_authors_by_ids(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(DELETE_AUTHORS_BY_IDS)
}
pub fn delete_authors_by_ids(
    client: &mut impl postgres::GenericClient,
    ids: &[i64],
) -> Result<(), postgres::Error> {
    self::delete_authors_by_ids_with(client, DELETE_AUTHORS_BY_IDS, ids)
}
pub fn delete_authors_by_ids_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    ids: &[i64],
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&ids];
    client.execute(statement, values).map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("ListAuthorsByIDs", LIST_AUTHORS_BY_IDS),
    ("ListAuthorsByTwoIDLists", LIST_AUTHORS_BY_TWO_ID_LISTS),
    ("ListAuthorsByIDsMixed", LIST_AUTHORS_BY_IDS_MIXED),
    ("DeleteAuthorsByIDs", DELETE_AUTHORS_BY_IDS),
];
