use prost::Message as _;
use std::io::{Read as _, Write};

pub(crate) mod plugin {
    include!(concat!(env!("OUT_DIR"), "/plugin.rs"));
}
mod config;
pub(crate) mod db_crates;
pub(crate) mod dynfilter;
mod error;
pub(crate) mod ident;
pub(crate) mod path_map;
pub(crate) mod query;
pub(crate) mod unique;
/// The inlined runtime doubles as the plugin's variant renderer, so generation and execution
/// share one implementation. Not every runtime item is used on the plugin side.
#[allow(dead_code)]
mod dynfilter_runtime {
    include!("db_crates/dynfilter_runtime.rs");

    mod tests {
        include!("db_crates/dynfilter_runtime_tests.rs");
    }
}
use config::{Config, apply_overrides};
pub(crate) use error::StackErrorResult;
pub use error::{Error, StackError, StackErrorExt};
pub(crate) use ident::{
    field_ident, normalize_str, validate_field_name, validate_type_name, value_ident,
};
use query::{Query, ReturningRows, RsType, collect_enums};
fn deserialize_codegen_request(data: &[u8]) -> Result<plugin::GenerateRequest, prost::DecodeError> {
    plugin::GenerateRequest::decode(data)
}

fn serialize_codegen_response(response: &plugin::GenerateResponse) -> Vec<u8> {
    response.encode_to_vec()
}

fn generate_comment(sqlc_version: &str) -> String {
    format!(
        r"//! Code generated by {}. SHOULD NOT EDIT.
//! sqlc version: {}
//! {} version: v{}",
        env!("CARGO_PKG_NAME"),
        sqlc_version,
        env!("CARGO_PKG_NAME"),
        env!("CARGO_PKG_VERSION"),
    )
}

pub fn try_main() -> Result<(), Error> {
    let mut stdin = std::io::stdin().lock();
    let mut buffer = Vec::new();
    stdin.read_to_end(&mut buffer)?;

    let request = deserialize_codegen_request(&buffer)?;
    let response = generate(&request, buffer)?;
    let serialized_response = serialize_codegen_response(&response);

    std::io::stdout().write_all(&serialized_response)?;

    Ok(())
}

/// Catalog enums and backend support items are emitted outside the per-query registry, so the
/// assembled file is the only place every top-level item is visible at once.
fn validate_unique_items(file: &syn::File) -> Result<(), Error> {
    let mut seen = std::collections::BTreeMap::new();
    for item in &file.items {
        let (kind, ident) = match item {
            syn::Item::Struct(item) => ("struct", &item.ident),
            syn::Item::Enum(item) => ("enum", &item.ident),
            syn::Item::Trait(item) => ("trait", &item.ident),
            syn::Item::Type(item) => ("type alias", &item.ident),
            syn::Item::Const(item) => ("const", &item.ident),
            syn::Item::Static(item) => ("static", &item.ident),
            syn::Item::Fn(item) => ("fn", &item.sig.ident),
            syn::Item::Mod(item) => ("module", &item.ident),
            _ => continue,
        };
        unique::insert_unique(&mut seen, ident.to_string(), kind).map_err(|first| {
            Error::any(
                format!("generated output defines `{ident}` twice ({first} and {kind}); rename the query, switch field, or database enum")
                    .into(),
            )
        })?;
    }
    Ok(())
}

fn generate(
    request: &plugin::GenerateRequest,
    input: Vec<u8>,
) -> Result<plugin::GenerateResponse, Error> {
    let config = if request.plugin_options.is_empty() {
        Config::default()
    } else {
        Config::from_option(&request.plugin_options)?
    };

    let mut db_type = config.db_crate.db_type_map();
    apply_overrides(&config, &mut db_type)?;

    let enum_derives = config
        .enum_derives
        .iter()
        .map(|d| syn::parse_str::<syn::Path>(d).map_err(|e| Error::any(e.into())))
        .collect::<Result<Vec<_>, _>>()?;

    let mut defined_enums = request
        .catalog
        .as_ref()
        .map(collect_enums)
        .transpose()?
        .unwrap_or_default();

    for e in &mut defined_enums {
        e.derives = enum_derives.clone();
    }

    for e in &defined_enums {
        db_type.insert_db_type(
            &e.name,
            RsType::new(
                syn::Type::Path(syn::TypePath {
                    attrs: Vec::new(),
                    qself: None,
                    path: e.ident().clone().into(),
                }),
                None,
                true,
            ),
        );
    }

    let returning_rows = request
        .queries
        .iter()
        .map(|q| {
            ReturningRows::from_query(
                &db_type,
                &config.return_row_attributes,
                request.catalog.as_ref(),
                q,
            )
        })
        .collect::<Result<Vec<_>, _>>()?;

    let settings = request
        .settings
        .as_ref()
        .ok_or_else(|| Error::any("dynamic filters require sqlc engine settings".into()))?;
    let dialect = dynfilter::Dialect::from_engine(&settings.engine)
        .map_err(|message| Error::any(message.into()))?;
    let catalog = request
        .catalog
        .as_ref()
        .map(dynfilter::resolve::Catalog::from_plugin)
        .unwrap_or_default();
    let queries = request
        .queries
        .iter()
        .map(|q| {
            Query::parse(
                &db_type,
                q,
                dialect,
                &catalog,
                config.db_crate.apply_static_slices(),
            )
        })
        .collect::<Result<Vec<_>, _>>()?;

    config.validate(&queries)?;
    let prepared = config
        .dynfilters
        .prepared
        .then(|| {
            dynfilter::prepared::Prepared::enumerate(&queries, config.db_crate, &config.dynfilters)
        })
        .transpose()?;

    let enums_ts = defined_enums
        .iter()
        .map(|e| config.db_crate.defined_enum(e))
        .collect::<Vec<_>>();
    let enums_tt = quote::quote! {#(#enums_ts)*};
    let embedded_tables_tt = db_crates::make_embedded_tables(&returning_rows)?;

    let init_tt = config.db_crate.init();
    let queries_tt = config.db_crate.generate_queries(
        &returning_rows,
        &queries,
        &db_crates::GenerateOptions {
            query_parameter_limit: config.query_parameter_limit,
            prepared: prepared.as_ref(),
        },
    )?;
    let tt = quote::quote! {
        #init_tt
        #enums_tt
        #embedded_tables_tt
        #queries_tt
    };
    let mut response = plugin::GenerateResponse::default();
    let ast = syn::parse2(tt).map_err(|e| Error::any(e.into()))?;
    validate_unique_items(&ast)?;
    let contents = format!(
        "{}\n\n{}",
        generate_comment(&request.sqlc_version),
        prettyplease::unparse(&ast)
    );
    let query_file = plugin::File {
        name: config.output,
        contents: contents.into(),
    };
    response.files.push(query_file);

    if config.debug {
        let req_txt = format!("{request:#?}");
        response.files.push(plugin::File {
            name: "input.txt".into(),
            contents: req_txt.into_bytes(),
        });

        response.files.push(plugin::File {
            name: "input.bin".into(),
            contents: input,
        });
    }

    Ok(response)
}

#[cfg(test)]
mod generate_tests;
