//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

#[derive(Debug, Clone, Copy, sqlx::Type)]
#[sqlx(type_name = "mood")]
pub enum Mood {
    #[sqlx(rename = "sad")]
    Sad,
    #[sqlx(rename = "ok")]
    Ok,
    #[sqlx(rename = "happy")]
    Happy,
}
pub const GET_MAPPING: &str = r"SELECT 
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val,

    money_val,
    ltree_val,
    lquery_val,
    cube_val,
    point_val,
    line_val,
    lseg_val,
    box_val,
    path_val,
    polygon_val,
    circle_val

FROM mapping";
pub struct GetMappingRow {
    pub bool_val: bool,
    pub bool_array_val: Vec<bool>,
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: sqlx::postgres::types::Oid,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: String,
    pub text_nullable_val: Option<String>,
    pub bytea_val: Vec<u8>,
    pub hstore_val: sqlx::postgres::types::PgHstore,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
    pub money_val: sqlx::postgres::types::PgMoney,
    pub ltree_val: sqlx::postgres::types::PgLTree,
    pub lquery_val: sqlx::postgres::types::PgLQuery,
    pub cube_val: sqlx::postgres::types::PgCube,
    pub point_val: sqlx::postgres::types::PgPoint,
    pub line_val: sqlx::postgres::types::PgLine,
    pub lseg_val: sqlx::postgres::types::PgLSeg,
    pub box_val: sqlx::postgres::types::PgBox,
    pub path_val: sqlx::postgres::types::PgPath,
    pub polygon_val: sqlx::postgres::types::PgPolygon,
    pub circle_val: sqlx::postgres::types::PgCircle,
}
impl<'r> sqlx::FromRow<'r, sqlx::postgres::PgRow> for GetMappingRow {
    fn from_row(row: &'r sqlx::postgres::PgRow) -> Result<Self, sqlx::Error> {
        Ok(Self {
            bool_val: sqlx::Row::try_get(row, 0)?,
            bool_array_val: sqlx::Row::try_get(row, 1)?,
            char_val: sqlx::Row::try_get(row, 2)?,
            smallint_val: sqlx::Row::try_get(row, 3)?,
            int_val: sqlx::Row::try_get(row, 4)?,
            int_nullable_val: sqlx::Row::try_get(row, 5)?,
            oid_val: sqlx::Row::try_get(row, 6)?,
            bigint_val: sqlx::Row::try_get(row, 7)?,
            real_val: sqlx::Row::try_get(row, 8)?,
            double_val: sqlx::Row::try_get(row, 9)?,
            text_val: sqlx::Row::try_get(row, 10)?,
            text_nullable_val: sqlx::Row::try_get(row, 11)?,
            bytea_val: sqlx::Row::try_get(row, 12)?,
            hstore_val: sqlx::Row::try_get(row, 13)?,
            timestamp_val: sqlx::Row::try_get(row, 14)?,
            timestamptz_val: sqlx::Row::try_get(row, 15)?,
            date_val: sqlx::Row::try_get(row, 16)?,
            time_val: sqlx::Row::try_get(row, 17)?,
            inet_val: sqlx::Row::try_get(row, 18)?,
            json_val: sqlx::Row::try_get(row, 19)?,
            jsonb_val: sqlx::Row::try_get(row, 20)?,
            uuid_val: sqlx::Row::try_get(row, 21)?,
            enum_val: sqlx::Row::try_get(row, 22)?,
            composite_val: sqlx::Row::try_get(row, 23)?,
            money_val: sqlx::Row::try_get(row, 24)?,
            ltree_val: sqlx::Row::try_get(row, 25)?,
            lquery_val: sqlx::Row::try_get(row, 26)?,
            cube_val: sqlx::Row::try_get(row, 27)?,
            point_val: sqlx::Row::try_get(row, 28)?,
            line_val: sqlx::Row::try_get(row, 29)?,
            lseg_val: sqlx::Row::try_get(row, 30)?,
            box_val: sqlx::Row::try_get(row, 31)?,
            path_val: sqlx::Row::try_get(row, 32)?,
            polygon_val: sqlx::Row::try_get(row, 33)?,
            circle_val: sqlx::Row::try_get(row, 34)?,
        })
    }
}
pub async fn get_mapping<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
) -> Result<GetMappingRow, sqlx::Error> {
    let q = sqlx::query_as::<_, GetMappingRow>(GET_MAPPING);
    q.fetch_one(executor).await
}
pub async fn get_mapping_opt<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
) -> Result<Option<GetMappingRow>, sqlx::Error> {
    let q = sqlx::query_as::<_, GetMappingRow>(GET_MAPPING);
    q.fetch_optional(executor).await
}
pub const INSERT_MAPPING: &str = r"INSERT INTO mapping
(
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val,
    money_val,
    ltree_val,
    lquery_val,
    cube_val,
    point_val,
    line_val,
    lseg_val,
    box_val,
    path_val,
    polygon_val,
    circle_val
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35
)";
#[derive(Debug, Clone)]
pub struct InsertMappingParams<'a> {
    pub bool_val: bool,
    pub bool_array_val: &'a [bool],
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: sqlx::postgres::types::Oid,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: &'a str,
    pub text_nullable_val: Option<&'a str>,
    pub bytea_val: &'a [u8],
    pub hstore_val: sqlx::postgres::types::PgHstore,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
    pub money_val: sqlx::postgres::types::PgMoney,
    pub ltree_val: sqlx::postgres::types::PgLTree,
    pub lquery_val: sqlx::postgres::types::PgLQuery,
    pub cube_val: sqlx::postgres::types::PgCube,
    pub point_val: sqlx::postgres::types::PgPoint,
    pub line_val: sqlx::postgres::types::PgLine,
    pub lseg_val: sqlx::postgres::types::PgLSeg,
    pub box_val: sqlx::postgres::types::PgBox,
    pub path_val: sqlx::postgres::types::PgPath,
    pub polygon_val: sqlx::postgres::types::PgPolygon,
    pub circle_val: sqlx::postgres::types::PgCircle,
}
pub async fn insert_mapping<'e>(
    executor: impl sqlx::Executor<'e, Database = sqlx::Postgres>,
    params: InsertMappingParams<'_>,
) -> Result<(), sqlx::Error> {
    let q = sqlx::query(INSERT_MAPPING);
    let q = q.bind(params.bool_val);
    let q = q.bind(params.bool_array_val);
    let q = q.bind(params.char_val);
    let q = q.bind(params.smallint_val);
    let q = q.bind(params.int_val);
    let q = q.bind(params.int_nullable_val);
    let q = q.bind(params.oid_val);
    let q = q.bind(params.bigint_val);
    let q = q.bind(params.real_val);
    let q = q.bind(params.double_val);
    let q = q.bind(params.text_val);
    let q = q.bind(params.text_nullable_val);
    let q = q.bind(params.bytea_val);
    let q = q.bind(params.hstore_val);
    let q = q.bind(params.timestamp_val);
    let q = q.bind(params.timestamptz_val);
    let q = q.bind(params.date_val);
    let q = q.bind(params.time_val);
    let q = q.bind(params.inet_val);
    let q = q.bind(params.json_val);
    let q = q.bind(params.jsonb_val);
    let q = q.bind(params.uuid_val);
    let q = q.bind(params.enum_val);
    let q = q.bind(params.composite_val);
    let q = q.bind(params.money_val);
    let q = q.bind(params.ltree_val);
    let q = q.bind(params.lquery_val);
    let q = q.bind(params.cube_val);
    let q = q.bind(params.point_val);
    let q = q.bind(params.line_val);
    let q = q.bind(params.lseg_val);
    let q = q.bind(params.box_val);
    let q = q.bind(params.path_val);
    let q = q.bind(params.polygon_val);
    let q = q.bind(params.circle_val);
    q.execute(executor).await.map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetMapping", GET_MAPPING),
    ("InsertMapping", INSERT_MAPPING),
];
