//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.2.0

pub trait RusqliteClient {
    fn connection(&self) -> &rusqlite::Connection;
}
impl RusqliteClient for rusqlite::Connection {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Savepoint<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
pub const GET_AUTHOR: &str = r"SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1";
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl GetAuthorRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn get_author(client: &impl RusqliteClient, id: i64) -> rusqlite::Result<GetAuthorRow> {
    let params = rusqlite::params![id];
    let mut statement = client.connection().prepare_cached(GET_AUTHOR)?;
    statement.query_row(params, GetAuthorRow::from_row)
}
pub fn get_author_opt(
    client: &impl RusqliteClient,
    id: i64,
) -> rusqlite::Result<Option<GetAuthorRow>> {
    use rusqlite::OptionalExtension as _;
    let params = rusqlite::params![id];
    let mut statement = client.connection().prepare_cached(GET_AUTHOR)?;
    statement
        .query_row(params, GetAuthorRow::from_row)
        .optional()
}
pub const LIST_AUTHORS: &str = r"SELECT id, name, bio FROM authors
ORDER BY name";
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl ListAuthorsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn list_authors(client: &impl RusqliteClient) -> rusqlite::Result<Vec<ListAuthorsRow>> {
    let params = rusqlite::params![];
    let mut statement = client.connection().prepare_cached(LIST_AUTHORS)?;
    statement
        .query_map(params, ListAuthorsRow::from_row)?
        .collect()
}
pub const COUNT_AUTHORS: &str = r"SELECT COUNT(*) FROM authors";
pub struct CountAuthorsRow {
    pub count: i64,
}
impl CountAuthorsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub fn count_authors(client: &impl RusqliteClient) -> rusqlite::Result<CountAuthorsRow> {
    let params = rusqlite::params![];
    let mut statement = client.connection().prepare_cached(COUNT_AUTHORS)?;
    statement.query_row(params, CountAuthorsRow::from_row)
}
pub fn count_authors_opt(
    client: &impl RusqliteClient,
) -> rusqlite::Result<Option<CountAuthorsRow>> {
    use rusqlite::OptionalExtension as _;
    let params = rusqlite::params![];
    let mut statement = client.connection().prepare_cached(COUNT_AUTHORS)?;
    statement
        .query_row(params, CountAuthorsRow::from_row)
        .optional()
}
pub const CREATE_AUTHOR: &str = r"INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub fn create_author(
    client: &impl RusqliteClient,
    params: CreateAuthorParams<'_>,
) -> rusqlite::Result<i64> {
    let params = rusqlite::params![params.name, params.bio];
    let mut statement = client.connection().prepare_cached(CREATE_AUTHOR)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(client.connection().last_insert_rowid())
}
pub const DELETE_AUTHOR: &str = r"DELETE FROM authors
WHERE id = ?";
pub fn delete_author(client: &impl RusqliteClient, id: i64) -> rusqlite::Result<()> {
    let params = rusqlite::params![id];
    let mut statement = client.connection().prepare_cached(DELETE_AUTHOR)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(())
}
pub const CREATE_AUTHOR_WITH_ID: &str = r"INSERT INTO authors (id, name) VALUES (?, ?)";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorWithIdParams<'a> {
    pub id: i64,
    pub name: &'a str,
}
pub fn create_author_with_id(
    client: &impl RusqliteClient,
    params: CreateAuthorWithIdParams<'_>,
) -> rusqlite::Result<i64> {
    let params = rusqlite::params![params.id, params.name];
    let mut statement = client.connection().prepare_cached(CREATE_AUTHOR_WITH_ID)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(client.connection().last_insert_rowid())
}
pub const CREATE_AUTHOR_RETURNING_ID: &str =
    r"INSERT INTO authors (name, bio) VALUES (?, ?) RETURNING id";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorReturningIdParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub fn create_author_returning_id(
    client: &impl RusqliteClient,
    params: CreateAuthorReturningIdParams<'_>,
) -> rusqlite::Result<i64> {
    let params = rusqlite::params![params.name, params.bio];
    let mut statement = client
        .connection()
        .prepare_cached(CREATE_AUTHOR_RETURNING_ID)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(client.connection().last_insert_rowid())
}
pub const RENAME_AUTHOR_RETURNING_ID: &str =
    r"UPDATE authors SET name = ? WHERE id = ? RETURNING id";
#[derive(Debug, Clone, Default)]
pub struct RenameAuthorReturningIdParams<'a> {
    pub name: &'a str,
    pub id: i64,
}
pub fn rename_author_returning_id(
    client: &impl RusqliteClient,
    params: RenameAuthorReturningIdParams<'_>,
) -> rusqlite::Result<u64> {
    let params = rusqlite::params![params.name, params.id];
    let mut statement = client
        .connection()
        .prepare_cached(RENAME_AUTHOR_RETURNING_ID)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(client.connection().changes())
}
pub const DELETE_AUTHOR_RETURNING_ID: &str = r"DELETE FROM authors WHERE id = ? RETURNING id";
pub fn delete_author_returning_id(client: &impl RusqliteClient, id: i64) -> rusqlite::Result<()> {
    let params = rusqlite::params![id];
    let mut statement = client
        .connection()
        .prepare_cached(DELETE_AUTHOR_RETURNING_ID)?;
    let mut rows = statement.query(params)?;
    while rows.next()?.is_some() {}
    Ok(())
}
pub const AUTHORS_BY_CLIENT: &str =
    r"SELECT id, name, bio FROM authors WHERE name = ?1 ORDER BY id";
pub struct AuthorsByClientRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl AuthorsByClientRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn authors_by_client(
    client_: &impl RusqliteClient,
    client: &str,
) -> rusqlite::Result<Vec<AuthorsByClientRow>> {
    let params = rusqlite::params![client];
    let mut statement = client_.connection().prepare_cached(AUTHORS_BY_CLIENT)?;
    statement
        .query_map(params, AuthorsByClientRow::from_row)?
        .collect()
}
pub const AUTHORS_BY_STATEMENT: &str =
    r"SELECT id, name, bio FROM authors WHERE bio = ?1 ORDER BY id";
pub struct AuthorsByStatementRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl AuthorsByStatementRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn authors_by_statement(
    client: &impl RusqliteClient,
    statement: Option<&str>,
) -> rusqlite::Result<Vec<AuthorsByStatementRow>> {
    let params = rusqlite::params![statement];
    let mut statement_ = client.connection().prepare_cached(AUTHORS_BY_STATEMENT)?;
    statement_
        .query_map(params, AuthorsByStatementRow::from_row)?
        .collect()
}
pub const AUTHORS_BY_PARAMS: &str =
    r"SELECT id, name, bio FROM authors WHERE name = ?1 ORDER BY id";
pub struct AuthorsByParamsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl AuthorsByParamsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn authors_by_params(
    client: &impl RusqliteClient,
    params: &str,
) -> rusqlite::Result<Vec<AuthorsByParamsRow>> {
    let params_ = rusqlite::params![params];
    let mut statement = client.connection().prepare_cached(AUTHORS_BY_PARAMS)?;
    statement
        .query_map(params_, AuthorsByParamsRow::from_row)?
        .collect()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetAuthor", GET_AUTHOR),
    ("ListAuthors", LIST_AUTHORS),
    ("CountAuthors", COUNT_AUTHORS),
    ("CreateAuthor", CREATE_AUTHOR),
    ("DeleteAuthor", DELETE_AUTHOR),
    ("CreateAuthorWithID", CREATE_AUTHOR_WITH_ID),
    ("CreateAuthorReturningID", CREATE_AUTHOR_RETURNING_ID),
    ("RenameAuthorReturningID", RENAME_AUTHOR_RETURNING_ID),
    ("DeleteAuthorReturningID", DELETE_AUTHOR_RETURNING_ID),
    ("AuthorsByClient", AUTHORS_BY_CLIENT),
    ("AuthorsByStatement", AUTHORS_BY_STATEMENT),
    ("AuthorsByParams", AUTHORS_BY_PARAMS),
];
pub fn prepare_dynfilter_variants(_client: &impl RusqliteClient) -> rusqlite::Result<()> {
    Ok(())
}
pub const DYNFILTER_VARIANT_COUNT: usize = 0;
