//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

pub trait RusqliteClient {
    fn connection(&self) -> &rusqlite::Connection;
}
impl RusqliteClient for rusqlite::Connection {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Savepoint<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
pub const GET_AUTHOR: &str = r"SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1";
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl GetAuthorRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn get_author(client: &impl RusqliteClient, id: i64) -> rusqlite::Result<GetAuthorRow> {
    let mut statement = client.connection().prepare_cached(GET_AUTHOR)?;
    let params = rusqlite::params![id];
    statement.query_row(params, GetAuthorRow::from_row)
}
pub fn get_author_opt(
    client: &impl RusqliteClient,
    id: i64,
) -> rusqlite::Result<Option<GetAuthorRow>> {
    use rusqlite::OptionalExtension as _;
    let mut statement = client.connection().prepare_cached(GET_AUTHOR)?;
    let params = rusqlite::params![id];
    statement
        .query_row(params, GetAuthorRow::from_row)
        .optional()
}
pub const LIST_AUTHORS: &str = r"SELECT id, name, bio FROM authors
ORDER BY name";
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
impl ListAuthorsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            name: row.get(1)?,
            bio: row.get(2)?,
        })
    }
}
pub fn list_authors(client: &impl RusqliteClient) -> rusqlite::Result<Vec<ListAuthorsRow>> {
    let mut statement = client.connection().prepare_cached(LIST_AUTHORS)?;
    let params = rusqlite::params![];
    statement
        .query_map(params, ListAuthorsRow::from_row)?
        .collect()
}
pub const COUNT_AUTHORS: &str = r"SELECT COUNT(*) FROM authors";
pub struct CountAuthorsRow {
    pub count: i64,
}
impl CountAuthorsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub fn count_authors(client: &impl RusqliteClient) -> rusqlite::Result<CountAuthorsRow> {
    let mut statement = client.connection().prepare_cached(COUNT_AUTHORS)?;
    let params = rusqlite::params![];
    statement.query_row(params, CountAuthorsRow::from_row)
}
pub fn count_authors_opt(
    client: &impl RusqliteClient,
) -> rusqlite::Result<Option<CountAuthorsRow>> {
    use rusqlite::OptionalExtension as _;
    let mut statement = client.connection().prepare_cached(COUNT_AUTHORS)?;
    let params = rusqlite::params![];
    statement
        .query_row(params, CountAuthorsRow::from_row)
        .optional()
}
pub const CREATE_AUTHOR: &str = r"INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)";
#[derive(Debug, Clone, Default)]
pub struct CreateAuthorParams<'a> {
    pub name: &'a str,
    pub bio: Option<&'a str>,
}
pub fn create_author(
    client: &impl RusqliteClient,
    params: CreateAuthorParams<'_>,
) -> rusqlite::Result<i64> {
    let mut statement = client.connection().prepare_cached(CREATE_AUTHOR)?;
    let params = rusqlite::params![params.name, params.bio];
    statement.execute(params)?;
    Ok(client.connection().last_insert_rowid())
}
pub const DELETE_AUTHOR: &str = r"DELETE FROM authors
WHERE id = ?";
pub fn delete_author(client: &impl RusqliteClient, id: i64) -> rusqlite::Result<()> {
    let mut statement = client.connection().prepare_cached(DELETE_AUTHOR)?;
    let params = rusqlite::params![id];
    statement.execute(params).map(|_| ())
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetAuthor", GET_AUTHOR),
    ("ListAuthors", LIST_AUTHORS),
    ("CountAuthors", COUNT_AUTHORS),
    ("CreateAuthor", CREATE_AUTHOR),
    ("DeleteAuthor", DELETE_AUTHOR),
];
