//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.1

#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "mood")]
pub enum Mood {
    #[postgres(name = "sad")]
    Sad,
    #[postgres(name = "ok")]
    Ok,
    #[postgres(name = "happy")]
    Happy,
}
#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "s")]
pub enum S {
    #[postgres(name = "a")]
    A,
    #[postgres(name = "b")]
    B,
}
#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "sync")]
pub enum Sync {
    #[postgres(name = "ready")]
    Ready,
}
pub mod dynfilter {
    use std::collections::{HashMap, HashSet};
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Arg {
        Active,
        Inactive,
        Slice(Option<usize>),
        Flag(bool),
    }
    impl Arg {
        pub fn from_option<T>(value: &Option<T>) -> Self {
            value.as_ref().map_or(Self::Inactive, |_| Self::Active)
        }
        fn active(self) -> bool {
            match self {
                Self::Active => true,
                Self::Inactive => false,
                Self::Slice(length) => length.is_some(),
                Self::Flag(value) => value,
            }
        }
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Bind {
        Arg(usize),
        Elem(usize, usize),
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Placeholders {
        Numbered,
        NumberedSqlite,
        Question,
    }
    pub struct Compiled {
        segments: Vec<Segment>,
        arg_count: usize,
        placeholders: Placeholders,
    }
    struct PlaceholderState<'a> {
        next_arg_num: usize,
        arg_order: Option<&'a [usize]>,
        seen_arg_nums: HashSet<usize>,
    }
    impl<'a> PlaceholderState<'a> {
        fn new(arg_order: Option<&'a [usize]>) -> Self {
            Self {
                next_arg_num: 1,
                arg_order,
                seen_arg_nums: HashSet::new(),
            }
        }
        fn unnumbered(&self, placeholders: Placeholders) -> Option<usize> {
            self.arg_order
                .map(|arg_order| {
                    arg_order
                        .iter()
                        .copied()
                        .find(|number| !self.seen_arg_nums.contains(number))
                })
                .unwrap_or_else(|| {
                    (placeholders == Placeholders::Question).then_some(self.next_arg_num)
                })
        }
        fn register(&mut self, number: usize, placeholders: Placeholders) {
            self.seen_arg_nums.insert(number);
            if placeholders == Placeholders::Question && number >= self.next_arg_num {
                self.next_arg_num = number + 1;
            }
        }
    }
    struct Segment {
        parts: Vec<String>,
        arg_nums: Vec<usize>,
        cond_idxs: Vec<usize>,
    }
    impl Compiled {
        pub fn build(&self, args: &[Arg]) -> (String, Vec<Bind>) {
            let mut query = String::new();
            let mut binds = Vec::new();
            let mut next_placeholder = 1;
            let mut scalar_placeholders = HashMap::new();
            let mut slice_placeholders: HashMap<usize, Vec<usize>> = HashMap::new();
            for segment in &self.segments {
                if segment
                    .cond_idxs
                    .iter()
                    .any(|index| !args.get(*index).is_some_and(|arg| arg.active()))
                {
                    continue;
                }
                for (index, part) in segment.parts.iter().enumerate() {
                    if let Some(before) =
                        slice_prefix(part).filter(|_| index < segment.arg_nums.len())
                    {
                        let arg_index = segment.arg_nums[index] - 1;
                        if let Some(Arg::Slice(Some(length))) = args.get(arg_index) {
                            query.push_str(before);
                            if self.placeholders == Placeholders::Question {
                                write_slice(
                                    &mut query,
                                    &mut binds,
                                    &mut next_placeholder,
                                    self.placeholders,
                                    arg_index,
                                    *length,
                                );
                            } else if let Some(numbers) = slice_placeholders.get(&arg_index) {
                                write_placeholders(&mut query, self.placeholders, numbers);
                            } else {
                                let numbers = write_slice(
                                    &mut query,
                                    &mut binds,
                                    &mut next_placeholder,
                                    self.placeholders,
                                    arg_index,
                                    *length,
                                );
                                slice_placeholders.insert(arg_index, numbers);
                            }
                            continue;
                        }
                        if args.get(arg_index).is_none() {
                            query.push_str(before);
                            query.push_str("NULL");
                            continue;
                        }
                    }
                    query.push_str(part);
                    let Some(arg_number) = segment.arg_nums.get(index) else {
                        continue;
                    };
                    let arg_index = arg_number - 1;
                    if self.placeholders != Placeholders::Question {
                        if let Some(number) = scalar_placeholders.get(&arg_index) {
                            write_placeholder(&mut query, self.placeholders, *number);
                        } else {
                            write_placeholder(&mut query, self.placeholders, next_placeholder);
                            scalar_placeholders.insert(arg_index, next_placeholder);
                            next_placeholder += 1;
                            binds.push(Bind::Arg(arg_index));
                        }
                    } else {
                        write_placeholder(&mut query, self.placeholders, next_placeholder);
                        next_placeholder += 1;
                        binds.push(Bind::Arg(arg_index));
                    }
                }
            }
            (finalize_query(query), binds)
        }
        pub fn arg_count(&self) -> usize {
            self.arg_count
        }
    }
    pub fn compile(annotated_sql: &str, placeholders: Placeholders) -> Compiled {
        compile_inner(annotated_sql, placeholders, None)
    }
    #[allow(dead_code)]
    pub fn compile_with_arg_order(
        annotated_sql: &str,
        placeholders: Placeholders,
        arg_order: &[usize],
    ) -> Compiled {
        compile_inner(annotated_sql, placeholders, Some(arg_order))
    }
    fn compile_inner(
        annotated_sql: &str,
        placeholders: Placeholders,
        arg_order: Option<&[usize]>,
    ) -> Compiled {
        let config = LexerConfig::new(annotated_sql, placeholders);
        let mut segments = Vec::new();
        let mut static_sql = String::new();
        let mut placeholder_state = PlaceholderState::new(arg_order);
        let mut first_line = true;
        let mut state = LexState::default();
        let mut lines = annotated_sql.split('\n').peekable();
        while let Some(line) = lines.next() {
            let separator = if first_line { "" } else { "\n" };
            first_line = false;
            if state.open() {
                state = line_end_state(line, state, config);
                static_sql.push_str(separator);
                static_sql.push_str(line);
                continue;
            }
            if let Some(mut conditions) = standalone_conditions(line) {
                flush_static(
                    &mut segments,
                    &mut static_sql,
                    &mut placeholder_state,
                    config,
                );
                if let Some(next_line) = lines.next() {
                    let (mut next_conditions, cleaned) = extract_conditions(next_line, config);
                    conditions.append(&mut next_conditions);
                    state = line_end_state(&cleaned, state, config);
                    let (parts, arg_nums) =
                        split_placeholders(&format!("\n{cleaned}"), &mut placeholder_state, config);
                    segments.push(Segment {
                        parts,
                        arg_nums,
                        cond_idxs: conditions,
                    });
                }
                continue;
            }
            let (conditions, cleaned) = extract_conditions(line, config);
            if !conditions.is_empty() {
                flush_static(
                    &mut segments,
                    &mut static_sql,
                    &mut placeholder_state,
                    config,
                );
                state = line_end_state(&cleaned, state, config);
                let (parts, arg_nums) = split_placeholders(
                    &format!("{separator}{cleaned}"),
                    &mut placeholder_state,
                    config,
                );
                segments.push(Segment {
                    parts,
                    arg_nums,
                    cond_idxs: conditions,
                });
                continue;
            }
            state = line_end_state(line, state, config);
            static_sql.push_str(separator);
            static_sql.push_str(line);
        }
        flush_static(
            &mut segments,
            &mut static_sql,
            &mut placeholder_state,
            config,
        );
        let arg_count = segments
            .iter()
            .flat_map(|segment| {
                segment
                    .arg_nums
                    .iter()
                    .map(|number| number - 1)
                    .chain(segment.cond_idxs.iter().copied())
            })
            .max()
            .map_or(0, |index| index + 1);
        Compiled {
            segments,
            arg_count,
            placeholders,
        }
    }
    pub fn nilable<T>(slice: &[T]) -> Option<&[T]> {
        (!slice.is_empty()).then_some(slice)
    }
    fn flush_static(
        segments: &mut Vec<Segment>,
        static_sql: &mut String,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) {
        if static_sql.is_empty() {
            return;
        }
        let (parts, arg_nums) = split_placeholders(static_sql, placeholder_state, config);
        segments.push(Segment {
            parts,
            arg_nums,
            cond_idxs: Vec::new(),
        });
        static_sql.clear();
    }
    fn write_slice(
        query: &mut String,
        binds: &mut Vec<Bind>,
        next_placeholder: &mut usize,
        placeholders: Placeholders,
        arg_index: usize,
        length: usize,
    ) -> Vec<usize> {
        if length == 0 {
            query.push_str("NULL");
            return Vec::new();
        }
        let mut numbers = Vec::with_capacity(length);
        for element_index in 0..length {
            if element_index > 0 {
                query.push(',');
            }
            let number = *next_placeholder;
            write_placeholder(query, placeholders, number);
            *next_placeholder += 1;
            numbers.push(number);
            binds.push(Bind::Elem(arg_index, element_index));
        }
        numbers
    }
    fn write_placeholders(query: &mut String, placeholders: Placeholders, numbers: &[usize]) {
        if numbers.is_empty() {
            query.push_str("NULL");
            return;
        }
        for (index, number) in numbers.iter().enumerate() {
            if index > 0 {
                query.push(',');
            }
            write_placeholder(query, placeholders, *number);
        }
    }
    fn write_placeholder(query: &mut String, placeholders: Placeholders, number: usize) {
        match placeholders {
            Placeholders::Numbered | Placeholders::NumberedSqlite => {
                query.push('$');
                query.push_str(&number.to_string());
            }
            Placeholders::Question => query.push('?'),
        }
    }
    fn slice_prefix(part: &str) -> Option<&str> {
        let start = part.rfind("/*SLICE:")?;
        part.ends_with("*/").then_some(&part[..start])
    }
    fn standalone_conditions(line: &str) -> Option<Vec<usize>> {
        let mut rest = line.trim();
        let mut conditions = Vec::new();
        while let Some(after_marker) = rest.strip_prefix("-- :if $") {
            let digits = after_marker.bytes().take_while(u8::is_ascii_digit).count();
            let number = after_marker[..digits].parse::<usize>().ok()?;
            if number == 0 {
                return None;
            }
            conditions.push(number - 1);
            rest = after_marker[digits..].trim_start();
        }
        (!conditions.is_empty() && rest.is_empty()).then_some(conditions)
    }
    fn extract_conditions(line: &str, config: LexerConfig) -> (Vec<usize>, String) {
        let Some(start) = annotation_start(line, config) else {
            return (Vec::new(), line.to_string());
        };
        let mut conditions = Vec::new();
        let mut rest = &line[start..];
        while let Some(position) = rest.find(" -- :if $") {
            let after_marker = &rest[position + 9..];
            let digits = after_marker.bytes().take_while(u8::is_ascii_digit).count();
            if let Ok(number) = after_marker[..digits].parse::<usize>()
                && number > 0
            {
                conditions.push(number - 1);
            }
            rest = &rest[position + 1..];
        }
        (conditions, line[..start].trim_end().to_string())
    }
    fn annotation_start(line: &str, config: LexerConfig) -> Option<usize> {
        let bytes = line.as_bytes();
        let mut index = 0;
        let mut in_line_comment = false;
        while index < bytes.len() {
            if line[index..].starts_with(" -- :if $") {
                return Some(index);
            }
            if in_line_comment {
                index += 1;
                continue;
            }
            if bytes[index..].starts_with(b"--") {
                in_line_comment = true;
                index += 2;
                continue;
            }
            let next = skip_quoted_or_block(line, index, config);
            index = if next > index { next } else { index + 1 };
        }
        None
    }
    fn split_placeholders(
        text: &str,
        placeholder_state: &mut PlaceholderState<'_>,
        config: LexerConfig,
    ) -> (Vec<String>, Vec<usize>) {
        let bytes = text.as_bytes();
        let mut parts = Vec::new();
        let mut arg_nums = Vec::new();
        let mut part_start = 0;
        let mut index = 0;
        while index < bytes.len() {
            let next = skip_token(text, index, config);
            if next > index {
                index = next;
                continue;
            }
            if bytes[index] != b'$' && bytes[index] != b'?' {
                index += 1;
                continue;
            }
            let mut end = index + 1;
            while bytes.get(end).is_some_and(u8::is_ascii_digit) {
                end += 1;
            }
            let number = match (bytes[index], end > index + 1, config.placeholders) {
                (b'$', true, _) => parse_number(&text[index + 1..end]),
                (b'?', true, Placeholders::NumberedSqlite)
                | (b'?', true, Placeholders::Question) => parse_number(&text[index + 1..end]),
                (b'?', false, _) => placeholder_state.unnumbered(config.placeholders),
                _ => None,
            };
            let Some(number) = number.filter(|number| *number > 0) else {
                index = end;
                continue;
            };
            placeholder_state.register(number, config.placeholders);
            parts.push(text[part_start..index].to_string());
            arg_nums.push(number);
            part_start = end;
            index = end;
        }
        parts.push(text[part_start..].to_string());
        (parts, arg_nums)
    }
    fn parse_number(text: &str) -> Option<usize> {
        text.parse().ok()
    }
    fn skip_token(text: &str, index: usize, config: LexerConfig) -> usize {
        if text.as_bytes()[index..].starts_with(b"--") {
            return text[index..]
                .find('\n')
                .map_or(text.len(), |end| index + end);
        }
        skip_quoted_or_block(text, index, config)
    }
    fn skip_quoted_or_block(text: &str, index: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        match bytes[index] {
            b'\'' | b'"' | b'`' => {
                let quote = bytes[index];
                let backslash = quote != b'`'
                    && (config.backslash_strings
                        || (config.postgres
                            && quote == b'\''
                            && escape_string_prefix(text, index)));
                quote_end(bytes, index + 1, quote, backslash).0
            }
            b'[' if is_bracket_identifier(text, index, config) => text[index + 1..]
                .find(']')
                .map_or(text.len(), |end| index + end + 2),
            b'$' if config.postgres => dollar_delimiter(text, index).map_or(index, |delimiter| {
                text[index + delimiter.len()..]
                    .find(&delimiter)
                    .map_or(text.len(), |end| {
                        index + delimiter.len() + end + delimiter.len()
                    })
            }),
            b'/' if bytes[index..].starts_with(b"/*") => skip_block_comment(text, index, config),
            _ => index,
        }
    }
    fn is_bracket_identifier(text: &str, start: usize, config: LexerConfig) -> bool {
        if config.bracket_identifiers {
            return true;
        }
        let Some(end) = text[start + 1..].find(']') else {
            return true;
        };
        let content = &text[start + 1..start + 1 + end];
        !content.strip_prefix('$').is_some_and(|number| {
            !number.is_empty() && number.bytes().all(|byte| byte.is_ascii_digit())
        })
    }
    fn skip_block_comment(text: &str, start: usize, config: LexerConfig) -> usize {
        let bytes = text.as_bytes();
        let mut depth = 0;
        let mut index = start;
        while index + 1 < bytes.len() {
            if bytes[index..].starts_with(b"/*") && (config.postgres || depth == 0) {
                depth += 1;
                index += 2;
            } else if bytes[index..].starts_with(b"*/") {
                depth -= 1;
                index += 2;
                if depth == 0 {
                    return index;
                }
            } else {
                index += 1;
            }
        }
        text.len()
    }
    #[derive(Clone, Copy)]
    struct LexerConfig {
        placeholders: Placeholders,
        postgres: bool,
        bracket_identifiers: bool,
        backslash_strings: bool,
    }
    impl LexerConfig {
        fn new(_sql: &str, placeholders: Placeholders) -> Self {
            Self {
                placeholders,
                postgres: placeholders == Placeholders::Numbered,
                bracket_identifiers: placeholders == Placeholders::NumberedSqlite,
                backslash_strings: placeholders == Placeholders::Question,
            }
        }
    }
    #[derive(Default)]
    struct LexState {
        quote: Option<u8>,
        backslash: bool,
        comment_depth: usize,
        dollar: Option<String>,
    }
    impl LexState {
        fn open(&self) -> bool {
            self.quote.is_some() || self.comment_depth > 0 || self.dollar.is_some()
        }
    }
    fn line_end_state(line: &str, mut state: LexState, config: LexerConfig) -> LexState {
        let bytes = line.as_bytes();
        let mut index = 0;
        while index < bytes.len() {
            if let Some(delimiter) = &state.dollar {
                let Some(end) = line[index..].find(delimiter) else {
                    return state;
                };
                index += end + delimiter.len();
                state.dollar = None;
                continue;
            }
            if state.comment_depth > 0 {
                while index < bytes.len() && state.comment_depth > 0 {
                    if config.postgres && bytes[index..].starts_with(b"/*") {
                        state.comment_depth += 1;
                        index += 2;
                    } else if bytes[index..].starts_with(b"*/") {
                        state.comment_depth -= 1;
                        index += 2;
                    } else {
                        index += 1;
                    }
                }
                continue;
            }
            if let Some(quote) = state.quote {
                if quote == b'[' {
                    let Some(end) = line[index..].find(']') else {
                        return state;
                    };
                    index += end + 1;
                    state.quote = None;
                    continue;
                }
                let (end, closed) = quote_end(bytes, index, quote, state.backslash);
                if !closed {
                    return state;
                }
                index = end;
                state.quote = None;
                continue;
            }
            if bytes[index..].starts_with(b"--") {
                return state;
            }
            if bytes[index..].starts_with(b"/*") {
                state.comment_depth = 1;
                index += 2;
                continue;
            }
            match bytes[index] {
                b'\'' | b'"' | b'`' => {
                    let quote = bytes[index];
                    state.quote = Some(quote);
                    state.backslash = quote != b'`'
                        && (config.backslash_strings
                            || (config.postgres
                                && quote == b'\''
                                && escape_string_prefix(line, index)));
                    index += 1;
                }
                b'[' if is_bracket_identifier(line, index, config) => {
                    state.quote = Some(b'[');
                    index += 1;
                }
                b'$' if config.postgres => {
                    if let Some(delimiter) = dollar_delimiter(line, index) {
                        index += delimiter.len();
                        state.dollar = Some(delimiter);
                    } else {
                        index += 1;
                    }
                }
                _ => index += 1,
            }
        }
        state
    }
    fn quote_end(bytes: &[u8], mut index: usize, quote: u8, backslash: bool) -> (usize, bool) {
        while index < bytes.len() {
            if backslash && bytes[index] == b'\\' {
                index += 2;
                continue;
            }
            if bytes[index] != quote {
                index += 1;
                continue;
            }
            if bytes.get(index + 1) == Some(&quote) {
                index += 2;
                continue;
            }
            return (index + 1, true);
        }
        (bytes.len(), false)
    }
    fn escape_string_prefix(text: &str, quote_index: usize) -> bool {
        if quote_index == 0 || !matches!(text.as_bytes()[quote_index - 1], b'e' | b'E') {
            return false;
        }
        if quote_index == 1 {
            return true;
        }
        let previous = text.as_bytes()[quote_index - 2];
        !(previous == b'_' || previous == b'$' || previous.is_ascii_alphanumeric())
    }
    fn dollar_delimiter(text: &str, start: usize) -> Option<String> {
        let bytes = text.as_bytes();
        let mut index = start + 1;
        while let Some(byte) = bytes.get(index) {
            if *byte == b'$' {
                return Some(text[start..=index].to_string());
            }
            let is_identifier = *byte == b'_'
                || byte.is_ascii_alphabetic()
                || (index > start + 1 && byte.is_ascii_digit());
            if !is_identifier {
                return None;
            }
            index += 1;
        }
        None
    }
    fn finalize_query(mut query: String) -> String {
        let mut lines = query.lines().map(str::to_string).collect::<Vec<_>>();
        let mut index = 0;
        while index < lines.len() {
            if !lines[index].trim().eq_ignore_ascii_case("ORDER BY") {
                index += 1;
                continue;
            }
            let fallback = lines[index + 1..]
                .iter()
                .position(|line| line.trim().eq_ignore_ascii_case("TRUE"))
                .map(|offset| index + offset + 1);
            let Some(fallback) = fallback else {
                index += 1;
                continue;
            };
            if fallback == index + 1 {
                lines.drain(index..=fallback);
                continue;
            }
            let previous = &mut lines[fallback - 1];
            let end = previous.trim_end_matches([' ', '\t']).len();
            if previous[..end].ends_with(',') {
                previous.remove(end - 1);
            }
            lines.remove(fallback);
            index += 1;
        }
        index = 0;
        while index < lines.len() {
            let trimmed = lines[index].trim();
            let next_is_query_suffix = lines.get(index + 1).is_none_or(|line| {
                ["ORDER", "LIMIT", "OFFSET", "FETCH", "RETURNING"]
                    .iter()
                    .any(|keyword| {
                        line.split_whitespace()
                            .next()
                            .is_some_and(|word| word.eq_ignore_ascii_case(keyword))
                    })
            });
            if ["ORDER BY", "WHERE", "GROUP BY", "HAVING"]
                .iter()
                .any(|keyword| trimmed.eq_ignore_ascii_case(keyword))
                && next_is_query_suffix
            {
                lines.remove(index);
                continue;
            }
            index += 1;
        }
        query = lines.join("\n");
        loop {
            let end = query.trim_end_matches([' ', '\t', '\n']).len();
            if end == 0 {
                return query;
            }
            let start = query[..end].rfind('\n').map_or(0, |index| index + 1);
            let trimmed = query[start..end].trim();
            if trimmed.ends_with(',') {
                let comma = query[start..end].rfind(',').unwrap();
                query.remove(start + comma);
                continue;
            }
            if ["ORDER BY", "WHERE", "GROUP BY", "HAVING"]
                .iter()
                .any(|keyword| trimmed.eq_ignore_ascii_case(keyword))
            {
                let new_end = query[..start].trim_end_matches([' ', '\t', '\n']).len();
                query.truncate(new_end);
                continue;
            }
            return query;
        }
    }
    #[cfg(test)]
    mod tests {
        use super::*;
        fn build(sql: &str, placeholders: Placeholders, args: &[Arg]) -> (String, Vec<Bind>) {
            compile(sql, placeholders).build(args)
        }
        #[test]
        fn drops_inactive_conditions_and_remaps_gaps() {
            let (sql, binds) = build(
                "SELECT * FROM t\nWHERE a = $1\n  AND b = $2 -- :if $2\n  AND c = $3",
                Placeholders::Numbered,
                &[Arg::Active, Arg::Inactive, Arg::Active],
            );
            assert_eq!(sql, "SELECT * FROM t\nWHERE a = $1\n  AND c = $2");
            assert_eq!(binds, [Bind::Arg(0), Bind::Arg(2)]);
        }
        #[test]
        fn keeps_multi_parameter_lines_only_when_all_are_active() {
            let sql = "SELECT * FROM t\nWHERE a = $1 -- :if $1 -- :if $2";
            assert_eq!(
                build(sql, Placeholders::Numbered, &[Arg::Active, Arg::Inactive]).0,
                "SELECT * FROM t"
            );
            assert_eq!(
                build(sql, Placeholders::Numbered, &[Arg::Active, Arg::Active]).0,
                "SELECT * FROM t\nWHERE a = $1"
            );
        }
        #[test]
        fn standalone_annotations_apply_to_the_next_line() {
            let (sql, binds) = build(
                "SELECT * FROM t\nWHERE a = $1\n-- :if $2\n  AND b = $2",
                Placeholders::Numbered,
                &[Arg::Active, Arg::Inactive],
            );
            assert_eq!(sql, "SELECT * FROM t\nWHERE a = $1");
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn numbered_placeholders_reuse_repeated_arguments() {
            let (sql, binds) = build(
                "SELECT * FROM t WHERE a = $1 OR b = $1",
                Placeholders::Numbered,
                &[Arg::Active],
            );
            assert_eq!(sql, "SELECT * FROM t WHERE a = $1 OR b = $1");
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn mysql_reemits_repeated_arguments() {
            let (sql, binds) = build(
                "SELECT * FROM t WHERE a = ? OR b = ?",
                Placeholders::Question,
                &[Arg::Active, Arg::Active],
            );
            assert_eq!(sql, "SELECT * FROM t WHERE a = ? OR b = ?");
            assert_eq!(binds, [Bind::Arg(0), Bind::Arg(1)]);
        }
        #[test]
        fn mysql_expands_numbered_slice_markers() {
            let (sql, binds) = build(
                "SELECT * FROM t WHERE kind = ? AND id IN (/*SLICE:ids*/?2) -- :if $2",
                Placeholders::Question,
                &[Arg::Active, Arg::Slice(Some(2))],
            );
            assert_eq!(sql, "SELECT * FROM t WHERE kind = ? AND id IN (?,?)");
            assert_eq!(binds, [Bind::Arg(0), Bind::Elem(1, 0), Bind::Elem(1, 1)]);
        }
        #[test]
        fn expands_slices_and_preserves_nil_empty_distinction() {
            let sql = "SELECT * FROM t\nWHERE name = ?1\n  AND id IN (/*SLICE:ids*/?2) -- :if $2";
            assert_eq!(
                build(
                    sql,
                    Placeholders::NumberedSqlite,
                    &[Arg::Active, Arg::Slice(None)],
                )
                .0,
                "SELECT * FROM t\nWHERE name = $1"
            );
            assert_eq!(
                build(
                    sql,
                    Placeholders::NumberedSqlite,
                    &[Arg::Active, Arg::Slice(Some(0))],
                ),
                (
                    "SELECT * FROM t\nWHERE name = $1\n  AND id IN (NULL)".into(),
                    vec![Bind::Arg(0)]
                )
            );
            assert_eq!(
                build(
                    sql,
                    Placeholders::NumberedSqlite,
                    &[Arg::Active, Arg::Slice(Some(2))],
                ),
                (
                    "SELECT * FROM t\nWHERE name = $1\n  AND id IN ($2,$3)".into(),
                    vec![Bind::Arg(0), Bind::Elem(1, 0), Bind::Elem(1, 1)]
                )
            );
        }
        #[test]
        fn repeated_numbered_slices_replay_expansion() {
            let (sql, binds) = build(
                "SELECT * FROM t WHERE id IN (/*SLICE:ids*/$1) OR parent_id IN (/*SLICE:ids*/$1)",
                Placeholders::Numbered,
                &[Arg::Slice(Some(2))],
            );
            assert_eq!(
                sql,
                "SELECT * FROM t WHERE id IN ($1,$2) OR parent_id IN ($1,$2)"
            );
            assert_eq!(binds, [Bind::Elem(0, 0), Bind::Elem(0, 1)]);
        }
        #[test]
        fn empty_repeated_slices_render_null_each_time() {
            assert_eq!(
                build("SELECT * FROM t WHERE id IN (/*SLICE:ids*/$1) OR parent_id IN (/*SLICE:ids*/$1)",
                Placeholders::NumberedSqlite, & [Arg::Slice(Some(0))],).0,
                "SELECT * FROM t WHERE id IN (NULL) OR parent_id IN (NULL)"
            );
        }
        #[test]
        fn missing_slice_argument_renders_null() {
            assert_eq!(
                build(
                    "SELECT * FROM t WHERE id IN (/*SLICE:ids*/?2) -- :if $1",
                    Placeholders::NumberedSqlite,
                    &[Arg::Active],
                ),
                ("SELECT * FROM t WHERE id IN (NULL)".into(), vec![])
            );
        }
        #[test]
        fn removes_trailing_order_by_and_where() {
            let (sql, binds) = build(
                "SELECT * FROM t\nWHERE\n  a = $1 -- :if $1\nORDER BY\n  id ASC, -- :if $2\n  id DESC -- :if $3\n  TRUE\nLIMIT 10",
                Placeholders::NumberedSqlite,
                &[Arg::Inactive, Arg::Flag(false), Arg::Flag(false)],
            );
            assert_eq!(sql, "SELECT * FROM t\nLIMIT 10");
            assert!(binds.is_empty());
        }
        #[test]
        fn removes_a_trailing_comma_after_toggling_order_by() {
            assert_eq!(
                build("SELECT * FROM t\nORDER BY\n  id ASC, -- :if $1\n  id DESC -- :if $2\n  TRUE\nLIMIT 10",
                Placeholders::Numbered, & [Arg::Flag(true), Arg::Flag(false)],).0,
                "SELECT * FROM t\nORDER BY\n  id ASC\nLIMIT 10"
            );
        }
        #[test]
        fn ignores_markers_in_literals_and_comments() {
            let (sql, binds) = build(
                "SELECT '?1', '$2' /* $3 */ FROM t WHERE a = $1 -- ignore $2",
                Placeholders::Numbered,
                &[Arg::Active],
            );
            assert_eq!(
                sql,
                "SELECT '?1', '$2' /* $3 */ FROM t WHERE a = $1 -- ignore $2"
            );
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn keeps_postgres_question_operators_as_text() {
            let (sql, binds) = build(
                "SELECT * FROM t WHERE json ? 'key' AND data?1 = 'x' AND a = $1",
                Placeholders::Numbered,
                &[Arg::Active],
            );
            assert_eq!(
                sql,
                "SELECT * FROM t WHERE json ? 'key' AND data?1 = 'x' AND a = $1"
            );
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn handles_postgres_dollar_quotes_escape_strings_and_nested_comments() {
            let (sql, binds) = build(
                "SELECT E'it\\'s $2', $tag$ -- :if $3 $tag$ /* outer /* inner */ $4 */ FROM t WHERE a = $1",
                Placeholders::Numbered,
                &[Arg::Active],
            );
            assert_eq!(
                sql,
                "SELECT E'it\\'s $2', $tag$ -- :if $3 $tag$ /* outer /* inner */ $4 */ FROM t WHERE a = $1"
            );
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn keeps_postgres_array_subscripts_as_placeholders() {
            let (sql, binds) = build(
                "SELECT tags[$1] FROM t WHERE a = $2",
                Placeholders::Numbered,
                &[Arg::Active, Arg::Active],
            );
            assert_eq!(sql, "SELECT tags[$1] FROM t WHERE a = $2");
            assert_eq!(binds, [Bind::Arg(0), Bind::Arg(1)]);
        }
        #[test]
        fn keeps_sqlite_bracket_identifiers_opaque() {
            let (sql, binds) = build(
                "SELECT [a?1b], [x$2y] FROM t WHERE a = ?1",
                Placeholders::NumberedSqlite,
                &[Arg::Active],
            );
            assert_eq!(sql, "SELECT [a?1b], [x$2y] FROM t WHERE a = $1");
            assert_eq!(binds, [Bind::Arg(0)]);
        }
        #[test]
        fn respects_mysql_backslash_escaped_strings() {
            let sql = "SELECT a FROM t\nWHERE cond = 1\n  AND name = 'O\\'Brien' AND status = ? -- :if $1";
            assert_eq!(
                build(sql, Placeholders::Question, &[Arg::Active]).0,
                "SELECT a FROM t\nWHERE cond = 1\n  AND name = 'O\\'Brien' AND status = ?"
            );
            assert_eq!(
                build(sql, Placeholders::Question, &[Arg::Inactive]).0,
                "SELECT a FROM t\nWHERE cond = 1"
            );
        }
        #[test]
        fn ignores_annotations_on_multiline_literal_continuations() {
            let (sql, binds) = build(
                "SELECT * FROM t\nWHERE note = 'hello\n-- :if $1\nworld' AND active = $2",
                Placeholders::Numbered,
                &[Arg::Inactive, Arg::Active],
            );
            assert_eq!(
                sql,
                "SELECT * FROM t\nWHERE note = 'hello\n-- :if $1\nworld' AND active = $1"
            );
            assert_eq!(binds, [Bind::Arg(1)]);
        }
        #[test]
        fn reports_the_highest_referenced_argument() {
            assert_eq!(
                compile("SELECT $1 -- :if $4", Placeholders::Numbered).arg_count(),
                4
            );
        }
        #[test]
        fn nilable_turns_only_empty_slices_into_none() {
            assert_eq!(nilable::<i64>(&[]), None);
            assert_eq!(nilable(&[1_i64]), Some(&[1][..]));
            assert_eq!(Arg::from_option(&Some(1)), Arg::Active);
            assert_eq!(Arg::from_option::<i64>(&None), Arg::Inactive);
        }
    }
}
pub const GET_MAPPING: &str = r"SELECT
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val
FROM mapping";
pub struct GetMappingRow {
    pub bool_val: bool,
    pub bool_array_val: Vec<bool>,
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: u32,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: String,
    pub text_nullable_val: Option<String>,
    pub bytea_val: Vec<u8>,
    pub hstore_val: std::collections::HashMap<String, Option<String>>,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
}
impl GetMappingRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            bool_val: row.try_get(0)?,
            bool_array_val: row.try_get(1)?,
            char_val: row.try_get(2)?,
            smallint_val: row.try_get(3)?,
            int_val: row.try_get(4)?,
            int_nullable_val: row.try_get(5)?,
            oid_val: row.try_get(6)?,
            bigint_val: row.try_get(7)?,
            real_val: row.try_get(8)?,
            double_val: row.try_get(9)?,
            text_val: row.try_get(10)?,
            text_nullable_val: row.try_get(11)?,
            bytea_val: row.try_get(12)?,
            hstore_val: row.try_get(13)?,
            timestamp_val: row.try_get(14)?,
            timestamptz_val: row.try_get(15)?,
            date_val: row.try_get(16)?,
            time_val: row.try_get(17)?,
            inet_val: row.try_get(18)?,
            json_val: row.try_get(19)?,
            jsonb_val: row.try_get(20)?,
            uuid_val: row.try_get(21)?,
            enum_val: row.try_get(22)?,
            composite_val: row.try_get(23)?,
        })
    }
}
pub fn prepare_get_mapping(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_MAPPING)
}
pub fn get_mapping(
    client: &mut impl postgres::GenericClient,
) -> Result<GetMappingRow, postgres::Error> {
    self::get_mapping_with(client, GET_MAPPING)
}
pub fn get_mapping_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<GetMappingRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    let row = client.query_one(statement, values)?;
    GetMappingRow::from_row(&row)
}
pub fn get_mapping_opt(
    client: &mut impl postgres::GenericClient,
) -> Result<Option<GetMappingRow>, postgres::Error> {
    self::get_mapping_opt_with(client, GET_MAPPING)
}
pub fn get_mapping_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
) -> Result<Option<GetMappingRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[];
    client
        .query_opt(statement, values)?
        .map(|row| GetMappingRow::from_row(&row))
        .transpose()
}
pub const INSERT_MAPPING: &str = r"INSERT INTO mapping (
    bool_val,
    bool_array_val,
    char_val,
    smallint_val,
    int_val,
    int_nullable_val,
    oid_val,
    bigint_val,
    real_val,
    double_val,
    text_val,
    text_nullable_val,
    bytea_val,
    hstore_val,
    timestamp_val,
    timestamptz_val,
    date_val,
    time_val,
    inet_val,
    json_val,
    jsonb_val,
    uuid_val,
    enum_val,
    composite_val
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)";
#[derive(Debug, Clone)]
pub struct InsertMappingParams<'a> {
    pub bool_val: bool,
    pub bool_array_val: &'a [bool],
    pub char_val: i8,
    pub smallint_val: i16,
    pub int_val: i32,
    pub int_nullable_val: Option<i32>,
    pub oid_val: u32,
    pub bigint_val: i64,
    pub real_val: f32,
    pub double_val: f64,
    pub text_val: &'a str,
    pub text_nullable_val: Option<&'a str>,
    pub bytea_val: &'a [u8],
    pub hstore_val: std::collections::HashMap<String, Option<String>>,
    pub timestamp_val: chrono::NaiveDateTime,
    pub timestamptz_val: chrono::DateTime<chrono::Utc>,
    pub date_val: chrono::NaiveDate,
    pub time_val: chrono::NaiveTime,
    pub inet_val: std::net::IpAddr,
    pub json_val: serde_json::Value,
    pub jsonb_val: serde_json::Value,
    pub uuid_val: uuid::Uuid,
    pub enum_val: Mood,
    pub composite_val: crate::Complex,
}
pub fn prepare_insert_mapping(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(INSERT_MAPPING)
}
pub fn insert_mapping(
    client: &mut impl postgres::GenericClient,
    params: InsertMappingParams<'_>,
) -> Result<(), postgres::Error> {
    self::insert_mapping_with(client, INSERT_MAPPING, params)
}
pub fn insert_mapping_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: InsertMappingParams<'_>,
) -> Result<(), postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[
        &params.bool_val,
        &params.bool_array_val,
        &params.char_val,
        &params.smallint_val,
        &params.int_val,
        &params.int_nullable_val,
        &params.oid_val,
        &params.bigint_val,
        &params.real_val,
        &params.double_val,
        &params.text_val,
        &params.text_nullable_val,
        &params.bytea_val,
        &params.hstore_val,
        &params.timestamp_val,
        &params.timestamptz_val,
        &params.date_val,
        &params.time_val,
        &params.inet_val,
        &params.json_val,
        &params.jsonb_val,
        &params.uuid_val,
        &params.enum_val,
        &params.composite_val,
    ];
    client.execute(statement, values).map(|_| ())
}
pub const GET_BY_STATE: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
ORDER BY id";
pub struct GetByStateRow {
    pub id: i64,
    pub state: S,
}
impl GetByStateRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub fn prepare_get_by_state(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_BY_STATE)
}
pub fn get_by_state(
    client: &mut impl postgres::GenericClient,
    state: S,
) -> Result<Vec<GetByStateRow>, postgres::Error> {
    self::get_by_state_with(client, GET_BY_STATE, state)
}
pub fn get_by_state_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: S,
) -> Result<Vec<GetByStateRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    let rows = client.query(statement, values)?;
    rows.iter().map(GetByStateRow::from_row).collect()
}
pub fn get_by_state_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    state: S,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::get_by_state_iter_with(client, GET_BY_STATE, state)
}
pub fn get_by_state_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: S,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    client.query_raw(statement, values.iter().copied())
}
pub const GET_ONE_BY_STATE: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
LIMIT 1";
pub struct GetOneByStateRow {
    pub id: i64,
    pub state: S,
}
impl GetOneByStateRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub fn prepare_get_one_by_state(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_ONE_BY_STATE)
}
pub fn get_one_by_state(
    client: &mut impl postgres::GenericClient,
    state: S,
) -> Result<GetOneByStateRow, postgres::Error> {
    self::get_one_by_state_with(client, GET_ONE_BY_STATE, state)
}
pub fn get_one_by_state_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: S,
) -> Result<GetOneByStateRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    let row = client.query_one(statement, values)?;
    GetOneByStateRow::from_row(&row)
}
pub fn get_one_by_state_opt(
    client: &mut impl postgres::GenericClient,
    state: S,
) -> Result<Option<GetOneByStateRow>, postgres::Error> {
    self::get_one_by_state_opt_with(client, GET_ONE_BY_STATE, state)
}
pub fn get_one_by_state_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: S,
) -> Result<Option<GetOneByStateRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    client
        .query_opt(statement, values)?
        .map(|row| GetOneByStateRow::from_row(&row))
        .transpose()
}
pub const GET_BY_STATE_WITH_MINIMUM_ID: &str = r"SELECT id, state FROM state_mappings
WHERE state = $1
  AND id >= $2
ORDER BY id";
#[derive(Debug, Clone)]
pub struct GetByStateWithMinimumIdParams {
    pub state: S,
    pub minimum_id: i64,
}
pub struct GetByStateWithMinimumIdRow {
    pub id: i64,
    pub state: S,
}
impl GetByStateWithMinimumIdRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub fn prepare_get_by_state_with_minimum_id(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_BY_STATE_WITH_MINIMUM_ID)
}
pub fn get_by_state_with_minimum_id(
    client: &mut impl postgres::GenericClient,
    params: GetByStateWithMinimumIdParams,
) -> Result<Vec<GetByStateWithMinimumIdRow>, postgres::Error> {
    self::get_by_state_with_minimum_id_with(client, GET_BY_STATE_WITH_MINIMUM_ID, params)
}
pub fn get_by_state_with_minimum_id_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: GetByStateWithMinimumIdParams,
) -> Result<Vec<GetByStateWithMinimumIdRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.state, &params.minimum_id];
    let rows = client.query(statement, values)?;
    rows.iter()
        .map(GetByStateWithMinimumIdRow::from_row)
        .collect()
}
pub fn get_by_state_with_minimum_id_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: GetByStateWithMinimumIdParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    self::get_by_state_with_minimum_id_iter_with(client, GET_BY_STATE_WITH_MINIMUM_ID, params)
}
pub fn get_by_state_with_minimum_id_iter_with<'c>(
    client: &'c mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    params: GetByStateWithMinimumIdParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] =
        &[&params.state, &params.minimum_id];
    client.query_raw(statement, values.iter().copied())
}
pub const GET_SYNC_ENTRY: &str = r"SELECT id, state FROM sync_mappings
WHERE state = $1";
pub struct GetSyncEntryRow {
    pub id: i64,
    pub state: Sync,
}
impl GetSyncEntryRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
pub fn prepare_get_sync_entry(
    client: &mut impl postgres::GenericClient,
) -> Result<postgres::Statement, postgres::Error> {
    client.prepare(GET_SYNC_ENTRY)
}
pub fn get_sync_entry(
    client: &mut impl postgres::GenericClient,
    state: Sync,
) -> Result<GetSyncEntryRow, postgres::Error> {
    self::get_sync_entry_with(client, GET_SYNC_ENTRY, state)
}
pub fn get_sync_entry_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: Sync,
) -> Result<GetSyncEntryRow, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    let row = client.query_one(statement, values)?;
    GetSyncEntryRow::from_row(&row)
}
pub fn get_sync_entry_opt(
    client: &mut impl postgres::GenericClient,
    state: Sync,
) -> Result<Option<GetSyncEntryRow>, postgres::Error> {
    self::get_sync_entry_opt_with(client, GET_SYNC_ENTRY, state)
}
pub fn get_sync_entry_opt_with(
    client: &mut impl postgres::GenericClient,
    statement: &(
         impl postgres::ToStatement + ?::std::marker::Sized + ::std::marker::Sync + ::std::marker::Send
     ),
    state: Sync,
) -> Result<Option<GetSyncEntryRow>, postgres::Error> {
    let values: &[&(dyn postgres::types::ToSql + ::std::marker::Sync)] = &[&state];
    client
        .query_opt(statement, values)?
        .map(|row| GetSyncEntryRow::from_row(&row))
        .transpose()
}
pub const SEARCH_SYNC_ENTRIES: &str = r"SELECT id, state FROM sync_mappings
WHERE TRUE
  AND state = $1 -- :if $1
ORDER BY id";
static SEARCH_SYNC_ENTRIES_DYN: std::sync::LazyLock<dynfilter::Compiled> =
    std::sync::LazyLock::new(|| {
        dynfilter::compile_with_arg_order(
            SEARCH_SYNC_ENTRIES,
            dynfilter::Placeholders::Numbered,
            &[1usize],
        )
    });
#[derive(Debug, Clone, Default)]
pub struct SearchSyncEntriesParams {
    pub state: Option<Sync>,
}
pub struct SearchSyncEntriesRow {
    pub id: i64,
    pub state: Sync,
}
impl SearchSyncEntriesRow {
    pub fn from_row(row: &postgres::Row) -> Result<Self, postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            state: row.try_get(1)?,
        })
    }
}
fn search_sync_entries_query(
    params: &SearchSyncEntriesParams,
) -> (
    String,
    Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)>,
) {
    let args = [dynfilter::Arg::from_option(&params.state)];
    let (sql, binds) = SEARCH_SYNC_ENTRIES_DYN.build(&args);
    let values: Vec<&(dyn postgres::types::ToSql + ::std::marker::Sync)> = binds
        .iter()
        .map(|bind| match bind {
            dynfilter::Bind::Arg(0usize) => &params.state as _,
            _ => unreachable!("dynfilter bind plan referenced an unknown argument"),
        })
        .collect();
    (sql, values)
}
pub fn search_sync_entries(
    client: &mut impl postgres::GenericClient,
    params: SearchSyncEntriesParams,
) -> Result<Vec<SearchSyncEntriesRow>, postgres::Error> {
    let (sql, values) = search_sync_entries_query(&params);
    let rows = client.query(sql.as_str(), &values)?;
    rows.iter().map(SearchSyncEntriesRow::from_row).collect()
}
pub fn search_sync_entries_iter<'c>(
    client: &'c mut impl postgres::GenericClient,
    params: SearchSyncEntriesParams,
) -> Result<postgres::RowIter<'c>, postgres::Error> {
    let (sql, values) = search_sync_entries_query(&params);
    client.query_raw(sql.as_str(), values)
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetMapping", GET_MAPPING),
    ("InsertMapping", INSERT_MAPPING),
    ("GetByState", GET_BY_STATE),
    ("GetOneByState", GET_ONE_BY_STATE),
    ("GetByStateWithMinimumID", GET_BY_STATE_WITH_MINIMUM_ID),
    ("GetSyncEntry", GET_SYNC_ENTRY),
    ("SearchSyncEntries", SEARCH_SYNC_ENTRIES),
];
