//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.12

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct Authors {
    pub id: i64,
    pub name: String,
}
pub struct Books {
    pub id: i64,
    pub author_id: i64,
    pub title: String,
}
pub struct GetReviewRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl GetReviewRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub struct GetReview {
    review_id: i64,
}
impl GetReview {
    pub const QUERY: &'static str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
WHERE r.id = ?1";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl GetReview {
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<GetReviewRow> {
        self.prepare(client)?
            .query_row(self.as_params(), GetReviewRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<GetReviewRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), GetReviewRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.review_id,)
    }
}
impl GetReview {
    pub const fn builder() -> GetReviewBuilder<'static, ((),)> {
        GetReviewBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetReviewBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetReviewBuilder<'a, ((),)> {
    pub fn review_id(self, review_id: i64) -> GetReviewBuilder<'a, (i64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        GetReviewBuilder {
            fields: (review_id,),
            _phantom,
        }
    }
}
impl<'a> GetReviewBuilder<'a, (i64,)> {
    pub fn build(self) -> GetReview {
        let (review_id,) = self.fields;
        GetReview { review_id }
    }
}
pub struct ListReviewsRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl ListReviewsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub struct ListReviews;
impl ListReviews {
    pub const QUERY: &'static str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
ORDER BY r.id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl ListReviews {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListReviewsRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), ListReviewsRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        ()
    }
}
impl ListReviews {
    pub const fn builder() -> ListReviewsBuilder<'static, ()> {
        ListReviewsBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListReviewsBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListReviewsBuilder<'a, ()> {
    pub fn build(self) -> ListReviews {
        let () = self.fields;
        ListReviews {}
    }
}
pub struct ListReviewsByMinimumRatingRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl ListReviewsByMinimumRatingRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub struct ListReviewsByMinimumRating {
    min_rating: Option<i64>,
}
impl ListReviewsByMinimumRating {
    pub const QUERY: &'static str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
WHERE r.rating >= ?1
ORDER BY r.id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl ListReviewsByMinimumRating {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListReviewsByMinimumRatingRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), ListReviewsByMinimumRatingRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.min_rating,)
    }
}
impl ListReviewsByMinimumRating {
    pub const fn builder() -> ListReviewsByMinimumRatingBuilder<'static, ((),)> {
        ListReviewsByMinimumRatingBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListReviewsByMinimumRatingBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListReviewsByMinimumRatingBuilder<'a, ((),)> {
    pub fn min_rating(
        self,
        min_rating: Option<i64>,
    ) -> ListReviewsByMinimumRatingBuilder<'a, (Option<i64>,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        ListReviewsByMinimumRatingBuilder {
            fields: (min_rating,),
            _phantom,
        }
    }
}
impl<'a> ListReviewsByMinimumRatingBuilder<'a, (Option<i64>,)> {
    pub fn build(self) -> ListReviewsByMinimumRating {
        let (min_rating,) = self.fields;
        ListReviewsByMinimumRating { min_rating }
    }
}
