//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.0

pub trait RusqliteClient {
    fn connection(&self) -> &rusqlite::Connection;
}
impl RusqliteClient for rusqlite::Connection {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
impl RusqliteClient for rusqlite::Savepoint<'_> {
    fn connection(&self) -> &rusqlite::Connection {
        self
    }
}
pub struct Authors {
    pub id: i64,
    pub name: String,
}
pub struct Books {
    pub id: i64,
    pub author_id: i64,
    pub title: String,
}
pub const GET_REVIEW: &str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
WHERE r.id = ?1";
#[derive(Debug, Clone, Default)]
pub struct GetReviewParams {
    pub review_id: i64,
}
pub struct GetReviewRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl GetReviewRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub fn get_review(
    client: &impl RusqliteClient,
    params: GetReviewParams,
) -> rusqlite::Result<GetReviewRow> {
    let mut statement = client.connection().prepare_cached(GET_REVIEW)?;
    let params = rusqlite::params![params.review_id];
    statement.query_row(params, GetReviewRow::from_row)
}
pub fn get_review_opt(
    client: &impl RusqliteClient,
    params: GetReviewParams,
) -> rusqlite::Result<Option<GetReviewRow>> {
    use rusqlite::OptionalExtension as _;
    let mut statement = client.connection().prepare_cached(GET_REVIEW)?;
    let params = rusqlite::params![params.review_id];
    statement
        .query_row(params, GetReviewRow::from_row)
        .optional()
}
pub const LIST_REVIEWS: &str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
ORDER BY r.id";
pub struct ListReviewsRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl ListReviewsRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub fn list_reviews(client: &impl RusqliteClient) -> rusqlite::Result<Vec<ListReviewsRow>> {
    let mut statement = client.connection().prepare_cached(LIST_REVIEWS)?;
    let params = rusqlite::params![];
    statement
        .query_map(params, ListReviewsRow::from_row)?
        .collect()
}
pub const LIST_REVIEWS_BY_MINIMUM_RATING: &str = r"SELECT r.id AS review_id, a.id, a.name, b.id, b.author_id, b.title, r.rating
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN authors a ON a.id = b.author_id
WHERE r.rating >= ?1
ORDER BY r.id";
#[derive(Debug, Clone, Default)]
pub struct ListReviewsByMinimumRatingParams {
    pub min_rating: Option<i64>,
}
pub struct ListReviewsByMinimumRatingRow {
    pub review_id: i64,
    pub authors: Authors,
    pub books: Books,
    pub rating: i64,
}
impl ListReviewsByMinimumRatingRow {
    pub fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            review_id: row.get(0)?,
            authors: Authors {
                id: row.get(1)?,
                name: row.get(2)?,
            },
            books: Books {
                id: row.get(3)?,
                author_id: row.get(4)?,
                title: row.get(5)?,
            },
            rating: row.get(6)?,
        })
    }
}
pub fn list_reviews_by_minimum_rating(
    client: &impl RusqliteClient,
    params: ListReviewsByMinimumRatingParams,
) -> rusqlite::Result<Vec<ListReviewsByMinimumRatingRow>> {
    let mut statement = client
        .connection()
        .prepare_cached(LIST_REVIEWS_BY_MINIMUM_RATING)?;
    let params = rusqlite::params![params.min_rating];
    statement
        .query_map(params, ListReviewsByMinimumRatingRow::from_row)?
        .collect()
}
pub const QUERIES: &[(&str, &str)] = &[
    ("GetReview", GET_REVIEW),
    ("ListReviews", LIST_REVIEWS),
    ("ListReviewsByMinimumRating", LIST_REVIEWS_BY_MINIMUM_RATING),
];
